### ISSUE TITLE
Load Faster

### ISSUE THREAD

**Issue by axiomteck** [pojome/elementor#1012]
can you add all the java scripts and any other stuff that can load on before footer that way pages load faster.

**Comment by netgain** [comment]
I am quite concerned about the amount of code & inline styles being stuffed into the head. The site isn't very big, but every page now has 29,000 characters BEFORE the <body> tag. It's a very real concern for performance and Google SERPs, because my most bloated competitor on the first page of Google only has 17,000 characters before their <body> tag. Isn't there some way to reduce the amount of code stuffed into the <head> section?

**Comment by KingYes** [comment]
Right now all JS scripts print before `<body>` tag get closed, and it's for performance.

Reference: http://stackoverflow.com/questions/2105327/should-jquery-code-go-in-header-or-footer

**Comment by pasog** [comment]
great plug in but very slow .. too much code ...
