### ISSUE TITLE
Basic form module

### ISSUE THREAD

**Issue by kadoogan55** [pojome/elementor#1025]
A very basic form module would be great in the free version. Just have the Name, Email, and Comment fields with a Submit button. This brings a new easy to use element to the free version of Elementor while advertising the fully editable form feature in the pro version.

**Comment by drawcard** [comment]
If you need a form for free, I suggest using something like Contact Form 7 and using the shortcode from that in your page with the Shortcodes module.

I suppose Elementor could offer that limited function for free, but the vast majority of forms are what you describe, so it doesn't make business sense. Elementor Pro is really worth the $ for the form module, let alone all the other great stuff it brings.

**Comment by kadoogan55** [comment]
I appreciate the advice, and that is what I would do under normal circumstances. The overall idea is to minimize the inclusion of other plugins and maintain the convenience of using Elementor. It also becomes a good advertisement for the full feature in the pro version.

**Comment by drawcard** [comment]
[Elementor's Youtube account](https://www.youtube.com/channel/UCt9kG_EDX8zwGSC1-ycJJVA) does a great job of advertising the Pro features, they have over 20 mins of demos on the Forms module for instance. I imagine it would be quite hard to release portions of the Pro code for demo purposes, and not have someone pirate the code / reverse engineer it to make it do everything else.

Not to be antagonistic, but that convenience you're describing sometimes comes with a price tag, in order to keep a project alive and make it the highest quality product for Pro and Free users alike. It's pretty amazing that Elementor Free currently exists with all of it's great features, when you compare it against other premium page builders. But Elementor Pro certainly makes life easier because of it's Pro features, and it's worth every dollar.

**Comment by agusmu** [comment]
@kadoogan55 I am building my own simple "Contact Form" widget using Elementor API for my themes. It is very easy to do without pirating Pro code, only using Elementor API.

After API docs is published, I believe there are many developers will build nice widgets for Elementor.

**Comment by netgain** [comment]
Except for its excellent UI for design, the form module in Pro is rather basic. What I would like to have is the design functionality in a more robust form plugin like Gravity Forms. My project needs "thank you" pages that display the submitted values, plus more advanced validation and multi-page forms with progress bars. It can actually be done, but not without custom coding.

**Comment by kadoogan55** [comment]
[drawcard](https://github.com/drawcard) it seems odd to me that any developer would not add a feature to their software for fear of it being pirated. Anything can (and likely will) be pirated. If this were truly something that would prevent a developer from creating software features, we wouldn't see anything getting done don't you think? Anyone wanting to pirate any Elementor code could simply buy a single licence and go to work.

All that being said, the free version of Elementor is pretty amazing - I just want it to be even more amazing.

And the price tag of the convenience I am asking for in particular can be found for free elsewhere, I would just like it to be included in Elementor.

I would really like to hear from the developer on this.

**Comment by joshmarom** [comment]
A form widget for Elementor free is currently not on our roadmap.
