### ISSUE TITLE
A front page bug?

### ISSUE THREAD

**Issue by paaljoachim** [pojome/elementor#1072]
I noticed that two of my locale test sites built with Desktop Server had what it seems like a bug.

![screen shot 2016-12-19 at 06 26 48](https://cloud.githubusercontent.com/assets/5323259/21369462/50613e68-c707-11e6-8f8e-200f46be7e30.png)

I made a Duplicator backup of the site:
https://www.dropbox.com/s/gmuo36dstjpqloa/20161219_lyckligarum_5859a830683a34903161220215248_archive.zip?dl=0

and the installer file:
https://www.dropbox.com/s/udw59qv67skyw3z/installer.php?dl=0

**Comment by joshmarom** [comment]
Seems like a css problem with the theme.
Which theme do you use?

**Comment by paaljoachim** [comment]
Hey Josh

That seems likely. It worked before an Elementor update.
I am using a child theme from Beans: http://www.getbeans.io/
But can switch over to another theme.

The main reason for me to create this issue and not send an e-mail to support is that if others have come across a similar problem that they could post in this thread. I am also thinking that if there is somekind of conflict that it might be something you guys might want to know about.

I am thinking you guys could sell a starter theme for Elementor for a small fee. As we all need a suitable theme to start out with in using Elementor. Even though most themes can be used it would be good to have a starter theme to go with it. It could also be a good doorway into your premium themes.

**Comment by dasigna** [comment]
... experienced one thing regarding themes and usage with elementor: the more themes 'do their own thing' and not always following wp common guidelines, the more issues occur.
but that seems to be kind of 'natural' in a way ...

dont know if theres a need for a basic 'elementor'-theme at the moment. maybe better way would be a kind of blank template with possibility of building own theme from scratch including header, footer etc. - on the other hand that might lead too far (?).

so until now theres one that fullfills most needs even in free version and works flawlessly with every project ive done so far together with elementor: generatepress.
if pojo would provide a basic theme like that, they mabe would double the work unnessesarily :-).

**Comment by netgain** [comment]
Since my project was to convert a mature site from an outdated CMS platform into Wordpress, I was able to make decisions without being tied to an existing theme. Through forums & social media I read that the Elementor and GeneratePress combination works well for creating lightweight pages that have a productive blend of functionality with near WYSIWYG capabilities. I can say that the combo has worked well so far.

After installing everything I haven't touched any of the GP theme. From a user's standpoint it's more like Elementor is already a theme rather than a plugin. You kinda forget that the theme is there.

Functionality-wise, both are new enough that it's not hard to come up with a wish list of new features. However it evolves, I hope that adding keeping the code reliable and lean remains a prerequisite for both awesome dev teams. From what I've read from the developer, GP Premium was built from the beginning with Google's need for speed in mind.

My site just launched this week and I am keeping a close watch on load times. So far I have run into some bugs and unicorn wishes, but have not encountered issues that I can attribute to a lack of compatibility between the GP theme & Elementor plugin.

**Comment by joshmarom** [comment]
I checked Beans theme with Elementor. I did not encounter any conflicts.
It must be an issue related with your child theme.
