### ISSUE TITLE
portfolio in PRO - image aspect ratio override and link [request]

### ISSUE THREAD

**Issue by dasigna** [pojome/elementor#1075]
for another one:

setting up portfolios in pro and encountering, that the aspect ratio-setting not always is appropriate...

e.g. currently trying to set up a automated list of sponsors logos with cpts and elementor portfolio which work absolutely fine so far. but one thing is quite frustrating - and thats the aspect-ratio-setting.
as logos dont follow any common aspect ratio its absolutely impossible to get all logos properly aligned and completely shown. there are always some parts cut off, which is not the best thing regarding logos (less concerning when it comes to images...).
so i wish there would be an option to disable or dismiss the aspect-ratio-setting and get the logos (images) fit into the defined box.
maybe let the aspect-ratio-setting be as it is for defining the 'viewport' for the single logos, but include a checkbox that forces the logos (or images) to fit within this 'viewport' regardless of their own aspect-ratio?

i hope i described it enough for clear understanding.

ps: image-gallery wont work for it, cause it cant be automated when applying a new one.
preparing all logos before upload to fit a certain aspect-ratio would work in priciple, but i think my customer would kill me if i tell him he has to do that every time ... ;-)

so the ability of overriding AR would really be great!

**Comment by dasigna** [comment]
ahhh - forgot something:

the custom post fields thing is coming into sight again with this:
if one could change the link from the native build-in-one to the 'post' (which isnt really one in this case) to a custom field with the url of the sponsor, this would be a major help! :-)

**Comment by joshmarom** [comment]
Without dismissing your request, I think this is a case where it would make sense to prepare the logo images in a uniform size in order to ensure an even looking result.
Personally, this is what I always did when I came across this kind of scenarios while working with a portfolio grid in premium themes.
Nevertheless, we will definitely discuss these issues and consider the possible solutions.
Thanks for the feedback.

**Comment by dasigna** [comment]
hi josh,

thanks for your reply.
the first thing that bothers me with this is, that e.g. the wp-gallery-setting for 'full image' definitely shows the complete image. another plugin of choice for post grids does this too, without cropping anything.
and in my opinion this should be able within elementor too - regardless of ratio setting.

the second thing about this is: there are maybe other places to use the same image (logo) again - if you prepare them especially for one place now, you likely have to do this twice or more.
in principle the most appropriate way in terms of perfect optical result - youre completely right with that. and i agree mostly. but users (customers) are not always into thinking the same way ... they more often like to get things easy done. and this thought has its own ritghts too.

so simply choosing how to show the images in best way by user would be definitely the best possibility.
and there has to be one that doesent crop them - regardless if they are even in meaning of ratios or not (even from my point of view).

just what i am thinking/experiencing. hopefully your internal discussion leads to the same result :-)

**Comment by netgain** [comment]
Resizing without cropping is a function of setting either a maximum height or a maximum width. It mainly applies to using either rows or columns. A newspaper site I work with has articles as blog posts and thumbnails (featured image) displayed in a vertical list format with thumbnail at left. Making a custom thumbnail image for each post would be highly impractical, especially since some images are going to be landscape and some will be portrait orientation. So, we customized it to specify maximum width for the thumbnail and the server creates a resized copy at the given width, with the image height calculated as the ratio to save the image properly resized without cropping. Looks good.

BEFORE that customization, the template was cropping each image into a square. Remember, this was a newspaper site. It had lots and lots of pictures of real local people. Lots of people got their heads chopped off or cropped at the nose. Uncontrolled cropping was quite frustrating for editors who work hard to get the right shot and just want to upload their photo knowing that it's going to appear where it needs to be.

**Comment by joshmarom** [comment]
Just following up on this, we have since introduced a masonry view which doesn't crop the image.
Do you guys think this fixes the issue for you?
