### ISSUE TITLE
Broken responsive in review mode

### ISSUE THREAD

**Issue by vanlong441** [pojome/elementor#1169]
I also use this plugin: Elementor Templater: ElemenTemplator.
My current Elementor Page Builder version is 1.0.9.

![screenshot_2017-01-13_09-41-41](https://cloud.githubusercontent.com/assets/1689356/21916711/eab81b06-d974-11e6-8e80-7abd7eec1714.png)

**Comment by dasigna** [comment]
same as here it seems: #1161

**Comment by arielk** [comment]
Can you please deactivate the all plugins (except Elementor), change to default theme and let me know if this solves the problem?

**Comment by vanlong441** [comment]
@arielk default theme + disable all Elementor plugins but the latest Elementor itself do not reproduce such problem. Can you suggest another way to go around this without losing the ability to go full width while building pages / posts?

**Comment by arielk** [comment]
Maybe @WPDevHQ the author of ElemenTemplator could help us here

**Comment by dasigna** [comment]
dont use the templater plugin but still have this problem with latest EL versions - have to investigate a little further i fear ...

**Comment by arielk** [comment]
@dasigna hoops.. can you please contact us by support@elementor.com, with complete login information to access your website and we will try to assist?

**Comment by arielk** [comment]
Thanks everyone for your report! we fixed it for the next version ...

**Comment by dasigna** [comment]
... hmmm. would be really great! :-)

but meanwhile i found its obviously kind of theme-related due to inline-css that wont be overridden.
wonder how it could be solved in this case, as i am having other issues too with this theme where e.g. text does not react to changes from within elementor...
its originally provided with visual composer and i dismissed it due to elementor.

so the question is if it still might be helpful to provide you with login to this?
