### ISSUE TITLE
Save reperate settings per viewport?

### ISSUE THREAD

**Issue by svtcode** [pojome/elementor#118]
Hi,

I was impressed with the quick pace that elementor enabled me to literally throw a page together and having things like font size sliders takes a lot of save/refresh/repeat time off the task. However, I think the full potential of that would be reached if the font and icon sizes could be saved individually for all viewports. A little checkmark on the respective device view saying "override viewport settings" would enable us to create perfectly aligned responsive websites in a lot less time.

I wanted to collect some opinions on that. Can someone think of a downside?

**Comment by yehudah** [comment]
Hi,

Can you give me more detailed example ?

**Comment by svtx** [comment]
Hi yehudah,

of course I can. Imaging you have a site that looks perfect in the desktop view because you've used the font size slider to adjust the paragraph so it is evened our nicely. Then you switch to the mobile or tablet preview and the font is just too big and not as nicely aligned anymore. So instead of calculating some random stuff, it would be cool to be able to change that section and save the viewport setting in addition to the desktop viewport setting. That way CSS Media Queries would be dealt with, giving the designer full control over responsive elements without ever having to touch code. Right now, only one setting is saved (desktop) and I think that's missing a huge opportunity to make Elementor even more powerful.

**Comment by pingram3541** [comment]
A custom css tool could be used for this but that requires some knowledge of css of course.  I'm going to open a new thread about converting my live customizer custom css tool to elementor!

**Comment by arielk** [comment]
Merged #141
