### ISSUE TITLE
CSS not loading unless logged in.

### ISSUE THREAD

**Issue by peepshow** [pojome/elementor#1186]
Hi there, I'm experiencing a new issue with Elementor.

## Description
The page specific CSS files stored in /uploads/elementor/css/ are not loading unless I am logged in to WP. Also when I FTP into my server the folder is completely empty as well. Bizarrely though they do load fine when logged, even with the /css/ directory empty of files.

I have tried using the **Regenerate CSS** utility that Elementor provides but still no luck. The file permissions are all set to 775 currently so that shouldn't be the cause.

I have also disabled plugins and removed caching, but still no luck.

### An example error message in console is the following:
`http://wordpress-6754-62331-167341.cloudwaysapps.com/wp-content/uploads/elementor/css/post-335.css?ver=1484616647 
Failed to load resource: the server responded with a status of 404 (Not Found)`

### The NGINX error log 
`2017/01/17 01:46:13 [error] 22360#22360: *159684 open() "/home/24032-62331.cloudwaysapps.com/tkhcegmcse/public_html/wp-content/uploads/elementor/css/post-418.css" failed (2: No such file or directory), client: 118.93.137.143, server: wordpress-6754-62331-167341.cloudwaysapps.com, request: "GET /wp-content/uploads/elementor/css/post-418.css?ver=1484616650 HTTP/1.1", host: "wordpress-6754-62331-167341.cloudwaysapps.com", referrer: "http://wordpress-6754-62331-167341.cloudwaysapps.com/"`

## Environment
				
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.10 (Debian)
	MySQL version: 5.5.53
	PHP Version: 5.6.29-0+deb8u1
	PHP Max Input Vars: 2500
	PHP Max Post Size: 128M
	GD Installed: Yes
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.7.1
	Site URL: http://wordpress-6754-62331-167341.cloudwaysapps.com
	Home URL: http://wordpress-6754-62331-167341.cloudwaysapps.com
	WP Multisite: No
	Max Upload Size: 128 MB
	Memory limit: 128M
	Permalink Structure: /%postname%/
	Language: en-NZ
	Timezone: Pacific/Auckland
	Debug Mode: Active

== Theme ==
	Name: Tree Adventures Sage 8
	Version: 8.4.2
	Author: Roots
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_NZ
	User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36

== Active Plugins ==
	Advanced Custom Fields
		Version: 4.4.11
		Author: Elliot Condon

	Advanced Custom Fields PRO
		Version: 5.5.3
		Author: Elliot Condon

	Akismet
		Version: 3.2
		Author: Automattic

	Custom Post Type UI
		Version: 1.5.0
		Author: WebDevStudios

	Debug Bar
		Version: 0.8.4
		Author: wordpressdotorg

	Elementor
		Version: 1.1.3
		Author: Elementor.com

	Elementor Pro
		Version: 1.0.8
		Author: Elementor.com

	EWWW Image Optimizer
		Version: 3.2.2
		Author: Shane Bishop

	Jetpack by WordPress.com
		Version: 4.4.2
		Author: Automattic

	Regenerate Thumbnails
		Version: 2.2.6
		Author: Alex Mills (Viper007Bond)

	Shortcodes Ultimate
		Version: 4.9.9
		Author: Vladimir Anokhin

	Simple Custom Post Order
		Version: 2.3
		Author: Sameer Humagain

	Soil
		Version: 3.7.0
		Author: Roots

	SVG Support
		Version: 2.3.1
		Author: Benbodhi

	W3 Total Cache
		Version: 0.9.5.1
		Author: Frederick Townes

	WP Migrate DB
		Version: 0.9.2
		Author: Delicious Brains

== Must-Use Plugins ==
	ManageWP - Worker Loader
		Version: 
		Author: ManageWP

**Comment by peepshow** [comment]
I also just found this message in the debug.log file
 
`[16-Jan-2017 03:16:14 UTC] PHP Notice:  Undefined index: time in /home/24032-62331.cloudwaysapps.com/tkhcegmcse/public_html/wp-content/plugins/elementor/includes/posts-css/post-css-file.php on line 175`

**Comment by arielk** [comment]
In order for us to look into this matter, please contact support@elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by jennypabon** [comment]
@peepshow did you find out solution? I'm getting the same error in one of my webs.

**Comment by douwjordaan** [comment]
I'm getting the same error over and over again. I can't work like this Elementor. Either sort it out or I will have to find a different solution. This has been going on from January 2017 - it is now January 2018. Someone please fix this before I chuck the whole system out the door.

**Comment by imakeinternet** [comment]
Here I am on 12/2/2019 still having the same problem described above.

**Comment by aTastyCookie** [comment]
2021 and the issue is here :(

**Comment by jluisfg** [comment]
2023 and I'm still getting this issue, has anyone been able to fix this?

**Comment by sumeru-digital** [comment]
This issue I got on our site two sites www.sumerudigital.com and www.web3acad.com when we did update. After lot of research I was able to find some workaround solution. I was able to fix this to the major extent. What I noticed that when you update elementor I saw it gets updated at two file locations. 
wp-content/uploads/elementor/
wp-content/uploads/plugins/elementor/
I dont know why the first one even exists or comes with elementor installation. Then I dug little more and looks like elementor creates it to save the form data or something. Link to post. https://elementor.com/help/form-widget-faq/ Though I have did not have used forms yet still it got created. 
Anyways, moving on I saw post css are maintained here in this folder wp-content/uploads/elementor/css/ 
**wp-content/uploads/elementor/** screenshot

![image](https://user-images.githubusercontent.com/58512318/213629058-325ca427-cfee-4817-bdb4-4a68c5908464.png)

**wp-content/uploads/plugins/elementor/assets/css** Screenshot
![image](https://user-images.githubusercontent.com/58512318/213630395-f2fd8dfb-b946-4b52-98ba-40230307ba19.png)


Also, the css are maintained in assets folder of wp-content/uploads/plugins/elementor/assets/css
and this is by design. 

When I log in to wp all pages look good. But, when I go to the pages public view some pages throw post-130.css not found. The error pattern is post#.css. So, I guess when you regenerate those post.css files in uploads folder (wp-content/uploads/elementor/css/) got deleted or something happened to this separately stored post level css files.. 

**Solution**
I just created the missing post file and named it as given in error i.e. post-130.css and copied other css files data into which has similar look of the missing page and it worked? I tested in public view and worked like a charm. I know this is not a good solution and work around. I thought it will help someone in distress like me. Thanks.

**Comment by wal-f** [comment]
I experienced a similar issue. Since others are, too, try clearing all caches: CDN, WP object cache, page caches, etc. I notice the issue reporter has W3 Total Cache installed, which provides an interface to purge many of these caches. Next go to _WP Admin > Elementor > Tools > General_ and click the _Regenerate Files & Data_ button. Finally, hard-reload a page on your site in your browser or clear its entire cache of the site. The former can ususally be done by holding down the Ctrl key when clicking reload. You can also visit it in a new Incognito/Private window, which should guarantee a fresh fetch of the page and its assets.

**Comment by dbmtrde** [comment]
2025... (!!!)

I'd like to add that this issue also affects several of my WordPress websites.

Sometimes the `post-XXXX.css` file physically exists but still returns a 404 — likely because the page was cached **before Elementor had a chance to regenerate the file**.  
In other cases, the file is **never generated at all**, even without any admin action. This suggests that Elementor deletes the CSS automatically in the background (e.g., via cron), but regeneration **never happens** if the first page request is intercepted by a caching system.

My **CSS print method is set to "external"**, as I prefer styles to be in separate files.  
The **Elementor CSS cache is disabled**, and although I use a caching plugin, I’ve tested this with all optimizations turned off — the problem still occurs.

This points to a deeper issue in how and when Elementor regenerates its CSS — particularly the reliance on an uncached frontend page load to trigger it.

**Honestly, I’m tired of having to manually click “Regenerate CSS” and clear caches every day or two.**  
That’s not sustainable for production websites.

👉 A reliable and immediate regeneration process — one that doesn't depend on `wp_cron` or frontend access — would go a long way toward solving this.  
I’d really appreciate it if the team could consider making CSS generation persistent and independent of caching behavior.
