### ISSUE TITLE
Suggestions - headings

### ISSUE THREAD

**Issue by rifleby** [pojome/elementor#1203]
Right now elementor have an issue with headings on mobile devices: it gets wayyy too small. Like if you make an h6 title on desktop; the size is ok but on mobile it gets crazy small. I know you can edit it with the responsive option but its too long to do this everytime and I think it would save a lot of time to add a global settings for heading. like you select h1,h2,h3,h4,h5,h6 size,line-height,etc on desktop/ipad/mobile and its saves for your entire project!

**Comment by drawcard** [comment]
This could be due to anything, from having the font size itself manually set by accident, to a conflict in your theme / plugin setup, or some other issue that can't be determined without a proper bug report. It sounds to me like there's a conflicting rule somewhere in your setup that needs to be ironed out. Try inspecting the heading code, to see where the small type style is originating from.

Adding global styles to Elementor is a bad idea, that's something that should be defined in the theme CSS files, rather than inside a content editor. Elementor simply sites on top of your theme styles, and overrides them when desired.

**Comment by arielk** [comment]
Like @drawcard wrote above, this option is more related to your theme, using Elementor you can change it to be more specific.

Thanks for your feedback!
