### ISSUE TITLE
Suggestion - add class to the element and not the parent!

### ISSUE THREAD

**Issue by rifleby** [pojome/elementor#1204]
I tried to add a class to a specific button(with the elementor add class) because I had some specific Jquery to do with that button, and I found out that the class isnt event targeting the button but a far parent. This is really odd and not at all convenient when doing custom script etc. I had to target that class .find or . children to make it work. After that Ive been doing some test to see if it might just be the buttons but it's for everything!! Everytime I add a class, it add it to a parent and not the element I added the class. 

Hope you fix this in future updates thanks!

**Comment by pingram3541** [comment]
This is currently designed for the most freedom and control based on how css actually works.  In the current css spec, one can only control styles of elements and their children and even siblings, but not parents.

If I add a custom class and it only assigns to the button element I would have no way to target it's wrapping containers of which I may need to add custom css for a specific purpose.  however `.my-custom-class button` is still very simple.

We would lose a lot of control because the entire style of an element is not just the primary element nested inside several layers deep but rather all those parent objects as well.

**Comment by arielk** [comment]
Sorry, but it is also designed for widgets that include multiple elements, then we do not plan to change this feature for now.

Thanks for your feedback!

**Comment by EricJammin** [comment]
This behavior is really strange and makes the custom CSS option not nearly as useful as it should be. Now you have to add multiple levels of parent and child selectors just to get a CSS class to effect the element you are trying to apply it to.

**Comment by pingram3541** [comment]
Let's see the button widget itself has the following nesting (some attributes removed for easier reading):
```
<div class="elementor-widget-button">
  <div class="elementor-widget-container">
    <div class="elementor-button-wrapper">
      <a href="#" class="elementor-button">
        <span class="elementor-button-content-wrapper">
          <span class="elementor-button-text">Button Text</span>
        </span>
      </a>
    </div>
  </div>
</div>
```
If they were to change the css class field to apply to the anchor only (i.e. a.elementor-button) we'd only be able to style "it" and it's children, the 2 span tags making problems much worse because no matter how much one tries, there is no way to target the parent elements within this element's custom css.

![Screen Shot 2019-04-17 at 8 05 02 PM](https://user-images.githubusercontent.com/319284/56334171-294f9180-614c-11e9-8320-c5c821c8bd91.png)

The way it is currently designed, it's not really that big of a deal to write:

```
selector a {
  rule: value;
}
```
Where the word "selector" will generate the unique top-level parent selector and result in the following on the front end:
```
.elementor-4308 .elementor-element.elementor-element-3a0e31e a {
  rule: value;
}
```
...targeting...
![Screen Shot 2019-04-17 at 8 06 21 PM](https://user-images.githubusercontent.com/319284/56334224-57cd6c80-614c-11e9-878e-20221c2b964c.png)

**Comment by violllettta** [comment]
Hi there, 

I don't understand the solution you are proposing. 

I have designed a custom button. I have used appearance>customize>additionalcss to target sitewide all the elementor buttons, mailpoet buttons, stripe payments buttons, etc. BUT My site has some pages with dark backgrounds where my button doesn't look great. For this reason I need a second colorway. 

However, as pointed out above, i can't apply the alternate class to the button widget using the advanced>cssclasses field. Instead I have to copy the whole custom css for the button into  advanced>customcss for every elementor button. Is this really the solution you are advocating? 

Is it possible to use the advanced>cssclasses field to target the actual element?  How?
