### ISSUE TITLE
Elementor won't work with WPML translations

### ISSUE THREAD

**Issue by Kurisutian** [pojome/elementor#1311]
Hi!
I'm using Elementor with WPML and so far I can only edit pages in the original language. Translations edited with Elementor lead to the pages main URL and the page is blank. I'm using a seperate folder URL for all my languages, even the default. 

More Information:

WP: v. 4.7.2
WPML: v. 3.6.3
Elementor: v. 1.2.3

Main language is English, translations will be German and French. Translations are currently set to be hidden for the frontend.

If any other information is required, please let me know what to provide.

Thanks!

**Comment by arielk** [comment]
if you set the "Language name added as a parameter" it works for you?

Maybe you can try to save the Permalinks in your site and let me know if it works for you.

Anyway, this issue is more suited for our official support forum. Please write to us in our official support forum: https://wordpress.org/support/plugin/elementor

You can also get help from our community on Facebook: https://www.facebook.com/groups/Elementors/

GitHub issues are intended for feature requests or bug reports.

**Comment by Kurisutian** [comment]
OK, here's an update to this issue:

In WPML it's possible to disable languages in order to not have partly translated content shown. Still in the admin area translations can be made. However, elementor seems to use something from the frontend and due to the fact that WPML disabled certain languages, elementor cannot access whatever is needed to edit the content. 
This means currently it is impossible to translate content with elementor if the language of the content is disabled. This would mean as long as I want to edit content I either have partly translated sites online or I cannot edit with elementor. Is there any known solution to this?
Thanks a lot!
