### ISSUE TITLE
Further updates on HTML/CSS and API

### ISSUE THREAD

**Issue by joelbqz** [pojome/elementor#1331]
Hi,

We are planning to use this pagebuilder for our themes in long-term, but we are a bit worried about updates on CSS/HTML Structure, grid or Elementor API that could break the theme in further updates. Can you advice us for a long-term compatibility?

Cheers!

**Comment by Nirvsoner** [comment]
Bump

**Comment by peepshow** [comment]
Same here, I keep finding the use of classes and CSS specificity changes from update to update.
So anything I override changing back to Elementor defaults. 

For example I added the Elementor SCSS files to my theme and modified some to better suit my approach, changing the the grid padding and font-size from px to em units among other things. But  the plugin updated and I have to go and do it all again, because for the 3rd time in a few weeks you've changed the way these classes are applied. 

I also tried wrapping the Elementor classes in a top level .my-theme class, but because of the excessive class nesting in Elementors SCSS, when the nesting changes I still loose all my settings and have to dig through the new SCSS and do it all again. 

Then has to be a better way.

**Comment by Nirvsoner** [comment]
Hi, any advice?

**Comment by bainternet** [comment]
We try to keep HTML/CSS changes to a minimum or none in the last 10's of updates. 

But if you must overwrite our styles with your custom ones, then the best approach would be to use higher level top wrapper CSS classes.

hope this answers your question.
