### ISSUE TITLE
Custom CSS classes not being applied (duplicate issue)

### ISSUE THREAD

**Issue by MasterPayne** [pojome/elementor#1401]
https://github.com/pojome/elementor/issues/707

Having a similar issue where child theme CSS style is not being applied to a HR element. I can see the class is appended to the element using Firebug, but the style is not applied on-page.

Also, there is an annoying 20px margin-bottom applied:

`.elementor-widget:not(:last-child) {
    margin-bottom: 20px;
}`

There is no control in the UI to remove this. Why?

**Comment by pingram3541** [comment]
Regarding the CSS, per your thread on WP.org, also like the linked thread author and no offense but I don't think you are using CSS properly. The idea of the CSS class being applied to the top most parent wrapper is the most flexible how CSS works because you can target any children from a parent but you can never target parents from children.

Applying the class to the heading or hr element directly would restrict us from being able to apply custom CSS as needed to style the whole Elementor block of components that make up the heading, hr or any other widget. If this request was actually put in place we'd have LESS freedom and control over our designs with Elementor.

Additionally it's about consistency across the components. Imagine a slider element, if the class applied only to the individual slides how do you then add custom CSS to the navigation arrows, the outer wrapper like a background color, border, shadows etc? Things higher up or siblings of the slides? We'd have to expect Elementor to provide some fairly unique IDs or classes and use those but is so much less intuitive and now makes us have to inspect the DOM every time we do this.

With your hr, why are you adding hr as an additional class?  Is that intentional for some reason? You might be thinking from the perspective of writing the rule out but remember you are adding classes to an html attribute not a stylesheet directly, 2 to be specific. So to target your "home-header hr" your custom CSS would need to be written ".home-header.hr hr { ... }", notice the two classes like you gave it, then a space, then the actual hr element? I.e. ".parent-class1.parent-class2 element"

As for the margin, most themes do this too for a better initial experience when laying out components. It's rare in your copy that you won't want *some* space between elements, especially text and heading elements and most often more than 20px which doesn't get in the way when adding more space via the provided margin and padding controls so it's easier to override this when necessary with some very simple css then to have to do the opposite and add margin every time because there isn't any.  I can tell you I've built many websites with Elementor and only had to override this specifically a few times and it was not a challenge or inconvenience by any means.

**Comment by MasterPayne** [comment]
Thanks a lot for the CSS clarifications! I'm by no means an expert.

Regarding the margins, I prefer to have creative control, and the 20px, while minimal, gets in the way of me aligning elements I want just under the header. As you pointed out, my only choice in specific cases is to override this with custom CSS.

**Comment by pingram3541** [comment]
Yeah, I just remember that with all elements it's as easy as adding:

```
.my-elementor-element-custom-class-name .elementor-widget:not(:last-child) {
  margin: 0;
}
```

Since I do so much work this is actually fairly quick fix when I need it because I know this rule applies for every element and its in my upper RAM =)

FYI, if you don't have Pro with the custom CSS capability I find it's extremely useful to add an html element with style tags at the very top of my Elementor design and then apply any custom css rules on the fly as I design then later move it out to my child theme files.

You can even give the html element a class name and hide it on the front end with the following:

```
body:not(.elementor-editor-active) .my-elementor-html-element-custom-class-name {
  display: none;
}
```

Best of success with your website designs =)

**Comment by pingram3541** [comment]
Thinking about this a little more, the element's padding and margin are still in full effect even when a rule like the following is applied.

```
body .elementor-widget:not(:last-child) {
    margin-bottom: 0 !important;
}
```

Adding the parent "body" element just give the rule that much more specificity along with the !important declaration.  You can add something like this to your theme's style.css and never have to worry about the default 20px margin again.  Simply use this rule on all your sites if you want =)

**Comment by arielk** [comment]
v1.5.0 released with control on the space between widgets, please update.
