### ISSUE TITLE
Does image element have external url option ?

### ISSUE THREAD

**Issue by timezstyle** [pojome/elementor#1411]

**Comment by drawcard** [comment]
You mean like this?

![image](https://cloud.githubusercontent.com/assets/1435638/23593161/1db51b62-025b-11e7-8252-ffc51aaf5c7d.png)

**Comment by timezstyle** [comment]
Nope,
like this  <img src="https://my_external_url">

**Comment by drawcard** [comment]
Oh right. For something like this I would probably use the HTML widget. It would still display as normal in the preview and on the frontend.

**Comment by timezstyle** [comment]
And image box widget?
We also need to write our custom HTML ?

**Comment by arielk** [comment]
Unfortunately it is not possible for now, but we may add this feature in the future.
There has been discussion you can follow it here: #413 

Thanks for the feedback!

**Comment by gioglifx** [comment]
Any thoughts as to when this will be implemented?   This is VERY useful for SEO and many other reasons and for the most part, pretty standards nowadays.  And if it's not sometime soon, what do you suggest in the mean time?

**Comment by drawcard** [comment]
You could use the HTML widget instead - just write the <img> tag into it:

![image](https://user-images.githubusercontent.com/1435638/37743474-2dea6358-2dba-11e8-9ea2-00e69b08079c.png)

Result:

![image](https://user-images.githubusercontent.com/1435638/37743468-252fb218-2dba-11e8-94a3-bc56a7b03479.png)

**Comment by DoviLilling** [comment]
@drawcard - not at all, the option should be available for any image object.
An example usecase: the ability to have a person's up-to-date social media profile picture in the testimonial.

**Comment by samheavyside** [comment]
> Unfortunately it is not possible for now, but we may add this feature in the future.
> There has been discussion you can follow it here: #413
> 
> Thanks for the feedback!

You closed this topic and referenced topic #413 as a "maybe in the future" waaaaaay on the 6th of March 2017. 

I have been following #413 for quite some time. Since the elementor dev team are contributing nothing but tumbleweeds and crickets in there, I attempted to re-ignite the conversation via a new topic (#11965).

If you (or a colleague) are in a position to comment on the likelihood of this being addressed in the future, please respond to some of the comments/requests on the open tickets (and no, I don't mean by closing them before they are resolved).

Thanks.
Sam

**Comment by rida4488** [comment]
> You mean like this?
> 
> ![image](https://cloud.githubusercontent.com/assets/1435638/23593161/1db51b62-025b-11e7-8252-ffc51aaf5c7d.png)



How can we add our custom link option with an image ????

**Comment by bensaine** [comment]
Bump for this in 2021

**Comment by nevertoday** [comment]
still no ?
