### ISSUE TITLE
Request "Shape Divider Top Full Colour"

### ISSUE THREAD

**Issue by Luxamman** [pojome/elementor#1427]
I really like the new shape divider, but i cant go the full way with it, because the shape divider on the top cannot have a full color - like plane white. Its always transparent and so the element/picture/background is visible as a the typical rectangle - at least on the top.

Can we get non-transparent colors please? 

PS: In the introduction video it seems to work with the fishes - but for me it only works on the bottom.

Ed1: And could it be, that the divider is not pixel perfect on the top? Seems its a little higher than the element itself. 
Ed2: Also (stupid) Edge Browser seems to have problems with the shape divider...
Ed3: The divider is also sometimes in the background - like with slideshows

Thanks a lot! Steven

#feature

**Comment by joshmarom** [comment]
-- I'm sorry, but I don't really understand the problem you have with "transparent shape".
All shapes are half opaque and half transparent.
The opaque part starts from the edge of the section and the transparent side is the side facing the inside of the section. the section's background is supposed to show through the transparent area of the shape.

-- Some browsers showed a very thin seam between the edge of the section to the edge shape under certain circumstances. In order to avoid that, we had to move the shape 1px over the edge.

-- Thanks for pointing out the issue with edge. We fixed it, and it will be resolved by the next update.

-- Slideshow is a widget, and like all widgets,  it will not appear behind the shape but rather above it.

**Comment by Luxamman** [comment]
- Iam working on a page with an angle and i have a section with 4 columns (http://luxam.at/downloads/screen1.png). As you can see, the bottom of the element/section has a nice white tilt, the top of it (in red) is always transparent. I cannot switch it to a full white, event when i copy the color from the bottom. Maybe it is, because the backgrounds are set in the columns, but why is it working on the bottom, but isn on the top? Hope you understand my problem now, thanks a lot!

- About the Slideshow/Widgets - maybe i can handle that with CSS classes and z-index

Thanks for your work!

**Comment by Luxamman** [comment]
Update:

- The "Bring to Front" works nice, thank you a lot! Also Edge Browser displays the shapes. Thanks!

- Since the update 1.3.2 the "Flip" option in the shape divider is making problems - in Elementor it looks good, than in Chrome to bottom shape is flipped horizontal and vertical, same in Firefox and in Edge also the top shape is vertical flipped. Do you think i need to rebuild it to overwrite old options or something like that?

**Comment by joshmarom** [comment]
Yes, we are aware of this "glitch".
We fixed it and it will be resolved by today's update. (v1.3.3)
Thank you for reporting.
