### ISSUE TITLE
Problem: Background image URLs in generated css are non-relative URLs

### ISSUE THREAD

**Issue by ehausen** [pojome/elementor#1453]
Background image URLS are non-relative URLs

Problem: When moving a site from dev to live server background image URLs still point to dev server because they are entered in css using absolute URLs like so:
`.elementor-10 .elementor-element.elementor-element-tptxy0p {
    background-image: url(http://test.server.com/website/wp-content/uploads/2017/03/bg-image.jpg);`

They should be in the database or pick-up the site URL variable from wp-config

But of course, the easiest solution is to use relative URLS:

`.elementor-10 .elementor-element.elementor-element-tptxy0p {
    background-image: url(/wp-content/uploads/2017/03/bg-image.jpg);`

**Comment by KingYes** [comment]
Just go to WordPress Admin -> Elementor -> Tools.
And press Regenerate Files to clear the cache..

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.

**Comment by stevebasford** [comment]
I'm still experiencing this issue after trying to regenerate files?

**Comment by paweltar** [comment]
I just want to let you know that I have the same issue with absolute URLs in CSS generated by Elementor. Let’s say that during development website has local URL `http://mywebsite.local` and when I push it to my hosting it is `http://mywebsite.com` – of course, it causes problems with all of the absolute URLs. Images are missing like in the post above.

I can add that I fixed it temporarily by going to WP Admin Dashboard > Elementor > Tools > Replace URL Tab and changing URL from the development one to the one used on a live site – but this solution is very very far from perfect, because of those reasons:

1. In the future, I will want to pull website from hosting to my computer to make some changes locally – I will need to replace the URLs once again to see the images during development on my computer and then remember to replace them again when I push my changes to the live site.

2. Local by Flywheel gives you option called “Live Link” – basically it uses Ngrok with random URL to let other people see the website while it’s still in development on a local computer. It gives you random URL like `http://079d4394.ngrok.io/`

Elementor is a really great tool but this is important to resolve this issue.

One more thing – In Replace URL Tab under Elementor Settings I tried to replace it from development URL to empty string “”. But it didn’t let me, unfortunately. Maybe this would be the way to fix it – by allowing URL to be replaced either by proper URL like it is now or by an empty string to make URLs relative?

@arielk I know this is an old thread, but I didn't want to start the new one as my problem is basically the same as the one described above - should I reopen this issue?

**Comment by muazzami** [comment]
same issue got me wondered whats wrong, especially when .local site is accessible via PC anyway so resources are all loading correctly within office however Mobile was showing missing images and it got me crazy unless I figured out background image path are not getting changed.
we use sync changes back and forth so there must be a way to overcome this or our Elementor Pro subscription going to be wasted.

**Comment by viettd** [comment]
Wp site done by another person using `http://1.2.3.4` then I come and update to `https:abc.com`
Tried `Regenerate Files` but after that the url in generated css files is `http://https://abc.com/`
`Replace URL` not working.
Just curious why not use relative path to avoid this kind of issue?

**Comment by martin6724** [comment]
Hey, did anyone come up with a fix for this? I had the same issue: background images and spacers not showing up in my ngrok tunnel link. I can't continue using elementorPRO unless I can safely show my clients a preview of local dev work. Any help or workaround would be greatly appreciated!!!

**Comment by acal** [comment]
I just encountered this when switching from staging to live for the first time. At first I performed a find and replace with the elementor tools which fixed a bunch of image urls. This fixed the images. The strange thing is that after doing this about a day later I noticed the bg images on a page or two reverted back to the staging URL somehow! I fixed this manually in the elementor editor. The next day it happened again! What is going on? How do we fix this?

**Comment by HartLarsson** [comment]
i've faced the sameproblem many time using "local by Flywheel" to developing loacal wp stites. 
The tool is great because you can provide a "live link" (as explained above) to show the status of the work to customers or partners. 
But because image urls in CSS are non-realtive the only trick is to add a special CSS file to fix all background images with the right live link base url. 
And this will change every time you activate the feature, forcing you changinf and editing the extra CSS every time.

So a question: why not use relative path in css in future?
Life will be more simple ;)

thanks

**Comment by dalmo3** [comment]
Just published my first site with ElementorPRO and this issue came up. Please change to relative paths.

**Comment by orthoZ** [comment]
Took me a while to figure out that the "replace url" would fix this. That's not very intuitive! This seems to have been an issue for a while. With many now using Let's Encrypt free SSL certs, it would seem this should get highter priority.

**Comment by ehausen** [comment]
This isssue is closed, but people seem to feel that there is something to fix. Should this be reopened? @arielk

**Comment by bainternet** [comment]
@ehausen 	

We are not aware of an ongoing issue with this, Elementor Uses full URLs for now and its not something that will change soon.

Using the provided tools and following [this guide](https://docs.elementor.com/article/467-site-migration), works just fine.

If you have a specific problem, feel free to open a new issue.

thanks.

**Comment by orthoZ** [comment]
Thanks for pointing to the guide. It certainly helps. However, since everything else, as new user, is pretty intuitive, finding out how to avoid mixed SSL content for background images was not easy. It took me many hours of searching to figure it out. Can I suggest that some you point to the [guide](https://docs.elementor.com/article/467-site-migration), somewhere so it it readily seen when adding background images? Maybe when adding a background image?

**Comment by joshfromcited** [comment]
We had a problem with this on our site, we deploy an instance of wordpress from a dev URL to a testing URL and then a production URL. You can only access the dev URL from our local network so we had images disappear on a public URL and could not edit the image locations. We also use Elastic Beanstalk with our hosting for scalability which causes some other complications.

We found a solution and I thought I'd share here to help others in a similar position.

For adding images as a section background, there is an option to make them Dynamic and select 'Featured Image'. Obviously you can only do this with one image per page.

There is also a plugin that helps you setup Featured Images with custom URLS.

By using the plugin and the Featured Image selection in Elementor we were able to make background images work without them being locked in to our dev environment.

Hope that helps, here is the plugin we used: https://wordpress.org/plugins/featured-image-from-url/

**Comment by mccambridge** [comment]
I just ran into this issue, too. It's a nonstandard way of handling things, and I wasted a lot of time trying to figure out what was going on. And I'm a developer. What about the poor non-devs trying to make this work?

How hare would it be to make the URL root-relative? I don't understand "its not something that will change soon". How hard can it be to drop the domain prefix?

**Comment by seancharris** [comment]
This issue is driving me nuts! I have lost 3-4 days of work just trying to test an elementor site locally on devices. I love elementor but it's becoming a deal breaker that I can't develop locally and test with devices. Does anyone know how to get relative urls running on background images? Is there a script or something out there? @bainternet Why can't elementor just reference a relative path here?

**Comment by seancharris** [comment]
I think I figured this out. Thanks @bainternet for sharing [The Elementor Migration Guide](https://docs.elementor.com/article/467-site-migration) ...

From the elementor migration guide:

> Background images are saved in a CSS file which has an absolute URL. To avoid migrating issues with the background images without having to write a script, you can define the  CSS Print Method to be inline instead of using external files, if you want. This can be done by going to Elementor > Settings > Advanced > CSS Print Method > Internal Embedding> CSS print method: inline, on your WP dashboard.

**Here's what got elementor background images working on local devices for me. I'm using Local WP with live links for device testing:**

1. In your local environment set the local Elementor css print method to "internal embedding" (Elementor > Settings > Advance)
2. Conduct a url rewrite (old environment URL to new environment URL)
3. Regenerate Elementor files (Elementor > Tools > General)

After I did this, in my local environment, my background images showed up in local devices. I then did a push to staging and prod (database included) to see if the background images were still visible and they were. Everything worked.

For production - Elementor cites performance enhancements when having Elementor's css print method set to "external". 

If you want to do this on prod, after you're done with your device testing, follow these steps:

1. In your prod environment set the local Elementor css print method to "external file" (Elementor > Settings > Advance)
2. Conduct a url rewrite (old environment URL to new environment URL)
3. Regenerate Elementor files (Elementor > Tools > General)

I think this should solve the Elementor background image conundrum when developing sites. Please let me know if I'm wrong here.

**Comment by pixelicous** [comment]
I just switched from site.domain.com to www.domain.com

Same web server and dB server.. Just url change

Change WordPress site url

Replaced urls, rereated css, flushed WordPress cache, flushed elementor cache, flushed nginx cache, reactivated license

Only when working with internally embedded css my background images work now. The css and styling, default colors and typography also don't work anymore if not embedded.. What can it be?

**Comment by breinkober** [comment]
Hey guys, simple Workaround because the tools from elementor didnt help:
Connect via FTP to your Website.

Go to the following folders: /wp-content/uploads/elementor/css

download them and search and replace the old background URLs

For me i had some css in another folder: /wp-content/uploads/ao_ccss

i changed background url there and i fixed the problem.
