### ISSUE TITLE
[Bug] Box Shadow Color "Opacity" only allows HEX to enter not RGBA (cuts after 7 chars)

### ISSUE THREAD

**Issue by Manuel-SG** [pojome/elementor#1547]
Nasty little bug in Elementor: Box Shadow Color "Opacity"

Hey there, please check and confirm. I just realised that there seems to be a bug in Elementor (at least since v1.17). The styling option "box shadow" is only accepting hex code (like #00000) and not RGBA Stuf (like rgba(0,0,0,0.4). You can not enter more than 7 chars - and you can only change default values by using the slider to change opacity.

Reproduction:
Go to a section or column for instance. Than go to "Style" --> "Background and Frame". Choose "Box Shadow" to "Yes". Click on Color and try to change the opacity / transparency of the color. It works with the slide control, but not with entering the numbers!
For instance, if I want to change
rgba(27,68,26,0.34)
to
rgba(27,68,26,0.25)
Than I can not change the value. I can delete .34 with backspace, but if I try to add .25 after deleting, Elementor does not "take the numbers".
Bug is still there in latest version (v1.4) without any plugins and with basetheme. In 2 different wordpress installments. One on php7 one on 5.6

Can you please fix this annoying bug? :-)

**Comment by cobicarmel** [comment]
It's an known issue with the native WordPress color picker. see #1026.

**Comment by Manuel-SG** [comment]
Well, good to know. But what I don´t understand is - I can edit the rgba field for "background color" for instance, without any problems.... same goes to "shape divider color" and so on. They look like all the same "color picker". So why is all working correct, except for the "box shadow" - if I got your answer right, than it should not work for changing ANY color opacity, shouldn't it ?

**Comment by drank** [comment]
I have to say this is NOT a issue with the native WordPress color picker.

The following Elementor files have a color control input element with the 'maxlength' attribute set to 7:
- includes/controls/box-shadow.php
- includes/controls/color.php
- includes/controls/text-shadow.php

When I manually set the maxlength to 25 (to accommodate an rgba value, e.g. 'rgba(255,255,255,0.85)') then everything works fine - i.e. I am able to manually set the transparency within the control. When it is set to 7 then all the above problems happen. The problem is every update of Elementor removes my fix.

So, it is not a problem with WordPress. Please set the maxlength to at least 25.

Thank you.
