### ISSUE TITLE
Elementor editor hidden when trying to edit page on Multisite mapped domain site

### ISSUE THREAD

**Issue by Thevarajah** [pojome/elementor#1597]
***This is an edited version originally posted on WordPress.org Forums *****

sorry a bit rough - but no time to tidy up

cannot get elementor editor to edit pages on multisite networked site once it has a domain mapped to it. Tried switching themes (2016), taking of plugins but did not work. It was working before but I’ve had this issue and had to recreate the site on my network. It worked until I mapped the domain. I’ve tested on sites which have mapped domains and the elementor seems to work but once a domain is mapped no editor panel available when trying to edit page. All is present in the backend to suggest

It works on other sites in my network that don’t have a domain name mapped. Is this a known issue – is there a way that it can be overcome without making my multisite unstable or unsecure (or both). Need to know if it can easily be resolved

I also tried to enable debug mode in config file but got an error (as sugested in forums)

see info of errors (if this may help) https://pastebin.com/XBqKbGDR

****system info from elementor plugin***

pastebin link https://pastebin.com/jzx4BRBA

**Comment by arielk** [comment]
In order for us to look into this matter, please send us your complete login information to access your website, to this email: support@elementor.com, and our support team will look into this as soon as possible.

**Comment by Pagester** [comment]
We ran into this problem back when Elementor first launched, it was down to the domain mapping plugin. My guess is your using the free one from the WP plugin directory ?

That one doesn't handle SSO which you need when you map a domain in multi-site. When you open Elementor on a mapped domain unless your client has logged in on that mapped domain Elementor won't load. You will also see UUID errors when you try access the Customizer as the domain you logged in under and the mapped domain won't match the session.

You'll need one of the paid domain mapping plugins to solve this as its not actually a problem exclusive to Elementor.

Also wether your install is sub-domain or sub directory makes no difference.

**Comment by Thevarajah** [comment]
Can you recommend any paid plug-ins? The only one other than the free one I've come across is the WPMU one, which is/was part of their suite of plugins which is membership (which is quite steep) every month. I've not had any other problems with plugins. I'm right in assuming that SSO is single sign-on, not sure how this relates to multisite handling of plugins, not come across this issue. What other plugins are affected by this issue.

**Comment by Pagester** [comment]
Yes correct, SSO is single sign on.

The WPMU one is the most stable, we use a customized version of it to suit our own install and I can confirm it works correctly. I'm not the biggest fan of their plugins but its one of the ones that does work consistently well. 

You can signup for a free month with them and then cancel and they allow you keep the plugin, its one of their marketing pitches at the moment.

This first surfaced with the Customizer and domain mapping where if you mapped a domain the Customizer would load blank with a UUID not found error, there are various tickets opened and closed for it on WP core, its ongoing with a while now.

Its caused by the user not being authenticated for the mapped domain as the user id has already been authenticated for the multi-site domain. The SSO function in the WPMU domain mapping plugin solves this problem. It doesn't address the root cause but it solves the problem.

You might run into problems with some of the caching plugins aswell

**Comment by Thevarajah** [comment]
will try that plugin suggested. Thanks.

**Comment by appscaptain** [comment]
Hi @Pagester Followed this thread. Experienced the same issue.
Wanted to use the WPMU plugin. But there another problem with WPMU Domain Mapping - it does not work with domain mapping in Polylang. Mercator (https://github.com/humanmade/Mercator) is the only domain mapping plugin that works with Polylang's domain mapping (eg .de for the german version and .com for the english version) - have tried all others.

See this thread:
https://wordpress.org/support/topic/domain-mapping-not-working-with-multisite/

Tried to switch from Mercator to WPMU's plugin - but it breaks this. 

So while WPMU fixes the elementor issue - it breaks Polylang instead. Any ideas on how to make everything work?
