### ISSUE TITLE
Do you plan to replace Theme Customizer panel?

### ISSUE THREAD

**Issue by edirpedro** [pojome/elementor#166]
I'm asking this because there is the Menu panel and there we have options to setup colors and fonts. A theme uses the Customizer or another Theme Options page to setup these options and I think Elementor conflicts with that setup.

My theme uses Customizer and has a section on that panel to setup colors and fonts, but opening the Elementor to edit the page, users can choose another setup of colors and fonts for that page. This sounds wrong to me. I can setup fonts as Default but i can't setup colors to use default theme settings, or hide those options on that panel. What do you think?

I think the Menu panel is for current page management only, like page attributes and other features from the WP side. Is this the plan for this panel?

**Comment by arielk** [comment]
No, we don't have such a plan to replace the customizer. The customizer is a tool meant for controlling the global setting of the site. Elementor is a page builder, and is dedicated for the soul purpose of editing and designing the page itself.

We call the area that controls colors and fonts "scheme". This controls all the default designs of Elementor. We built it as part of a set of features we will be adding in the future, like the template library we are currently working on.

Because users still want to their existing theme schemes, we will be adding further controls over this area, so you will be able to cancel it altogether for your site. In addition, we are thinking of maybe moving it to the customizer area, it might be a better location for this.

**Comment by LittleNeko1** [comment]
Hi,
Congrats for the amazing work you've done! We're testing Elementor for our next main website update, while evaluating how we could switch to it for the WP themes we create and sell. So far, all is good and promising. And it's super fast! :)
The only drawbacks (as theme author), is missing developper  API (but I read you are working on it), and this default setting panel.
We use the customizer to allow customization of default fonts properties / colors / etc.. ( Like many themes ). So it would be nice to be able to remove the whole "settings" panel and have widgets default to theme defaults for colors, font, etc ... (while keeping the option to change them individually).

Keep up the good work!

**Comment by yehudah** [comment]
Hello @LittleNeko1 ,

We working on such option, and I hope it will be in one of the next versions.

**Comment by LittleNeko1** [comment]
Awesome!

**Comment by edirpedro** [comment]
Thank you.
