### ISSUE TITLE
Make a new page option inside frontend builder

### ISSUE THREAD

**Issue by royhaarlem** [pojome/elementor#1662]
Hi guys, I got a request for a new option in Elementor.

When you’re building inside the Builder you can't make a new page, you have to go to the Wordpress dashboard and make there new pages.

Is it possible to create an option that you can create new pages inside the builder, so people don't have to go to the Wordpress dashboard. I bet a lot of users would like this option.

Greetings from Roy

**Comment by arielk** [comment]
@royhaarlem I like the idea, we will figure out how to include it in our roadmap, thanks.

**Comment by Basilakis** [comment]
Why not use the admin bar and create a new page from there, what can also have the /?elementor option? 
That is WordPress functionality and a simply function, instead of having something that is not elementor related.

@royhaarlem a developer could easily help you with that even have a promt box to add your page title :-)

**Comment by shilo-ey** [comment]
@royhaarlem 
This enhancement has been added to Elementor 2.3.0 using [Finder](https://elementor.com/blog/introducing-finder/)

Thanks for your feedback.
