### ISSUE TITLE
[Minor "issues"] 2 very little typos found

### ISSUE THREAD

**Issue by Ver3** [pojome/elementor#1754]
1. See screenshot of login form: There still is a space before "Username or Emailaddress" (and no way to change these texts)

2. See change log: "2017-05-18 v1.5.0" (not today's date)
https://elementor.com/pro/changelog/

Not to nitpick, just to help.

![image](https://cloud.githubusercontent.com/assets/20367733/26355648/c5095990-3fc9-11e7-9188-941063f3b9a2.png)

**Comment by carasmo** [comment]
There is no typo. If you have a gap it's because some other CSS is affecting the label. Look for a form plugin or in your theme. 

There is no gap and you can change the text.

![screen shot 2017-05-23 at 9 31 22 am](https://cloud.githubusercontent.com/assets/1124594/26356716/f0ba9ace-3f9a-11e7-906b-b3f5de25a065.png)

**Comment by Ver3** [comment]
Apologies, I'm not seeing these options on any of my Elementor sites. Will
now look foor common plugins and start to disable them.

Cheers!


Kind regards / Vriendelijke groet,

*Verdi Heinz*

▶ About me <https://www.verdi.nu/>
