### ISSUE TITLE
Pro: Add custom CSS tab specific for Desktop, Tablet and Mobile

### ISSUE THREAD

**Issue by luizeof** [pojome/elementor#1775]
## Description

On Elementor Custom CSS provided by Elementor Pro, there are a possibility to add tree custom CSS items .. one specific for Mobile, one for Tablet and one for Desktop?

![download 3](https://cloud.githubusercontent.com/assets/257004/26582808/ddcd1526-4518-11e7-8b6f-4662a9918fe1.png)

**Comment by enkota** [comment]
You would achieve this by using media queries in the custom CSS, but I agree, would be a nice feature to allow pre-defined media query fields.

**Comment by Basilakis** [comment]
I really believe it is better to have your own media queries on the main Custom CSS box, instead of having multiple boxes.

But - if you need to do that, you can simple extend the fields, with the following:
https://github.com/pojome/elementor/blob/master/docs/content/hooks/php-hooks.md

Which would allow you to add after Custom CSS those areas. Create a plugin that you can enable to all of the sites you are working and it is embedding that. 

Core and Pro versions should be kept simple and not have things that are not needed so much, instead be focused on creating more advanced stuff and extending with functionality that is needed to make the editor better as product.

**Comment by arielk** [comment]
Custom CSS designed for advanced users, so you can add a custom media query as you want.

Thanks for your comment!

**Comment by gsusI** [comment]
I think this now, on 2020, makes more sense than it did by 2017.

Quick example could be, the alignment of some elements is forced to be the same on desktop, tablet and mobile. However, from a design perspective this constrain doesn't make sense.
