### ISSUE TITLE
Simplify widget templates with Mustache

### ISSUE THREAD

**Issue by edirpedro** [pojome/elementor#181]
I was creating a widget and noticed that I need to repeat the HTML template for JS and PHP. Why does not use such tool like Mustache? http://mustache.github.io/

The Mustache library has a PHP and a JS version, the settings values would be passed as is and only if needed, I could change or add some value with the functions php_render() and js_render() before Mustache renders the template.

Sample code that could result for the widget, replacing render() and content_template()
```

class My_Widget extends Widget_Base {
	
	protected function render_php($settings) {
		
		// Do some PHP stuff if needed
		$settings['avatar'] = $settings['image']['url'] ? '<img src="' . $settings['image']['url'] . '">' : false;
		
		return $settings;
	}
	
	protected function render_js() {
		?>
		<%
		
		// Do some JS stuff if needed
		settings.avatar = settings.image.url ? '<img src="' + settings.image.url + '">' : false;
				
		%>
		<?php
	}
	
	protected function get_template() {
		
		return '
		<div class="my-element">
			{{avatar}}
			<h1>{{name}}</h1>
			<p>{{biography}}</p>
		</div>
		';
		
	}
	
}
```

**Comment by KingYes** [comment]
Hi @edirpedro 

We are need two templates (JS/PHP), Because the JS is faster then PHP (no need server request), but the problem with this, in some cases we need server data. For example to render custom shortcodes; Get custom image sizes as saved in WordPress data; Using custom server API; And more things..

Thanks for your idea by the way 👍
