### ISSUE TITLE
How can i bind events when value changed, for custom control input field?

### ISSUE THREAD

**Issue by wpaholic** [pojome/elementor#2036]
Hi, i'm trying to create a custom ajax control to retrieve category ids. I have a text field handled with jquery handled to look for specific category when user types, and add chosen category (id) to hidden input field, something like this:

```
<input type="text" id="ajax-cat-search" placeholder="Type to search...">
<input type="hidden" id="<?php echo $control_uid; ?>" data-setting="{{ data.name }}">
```

the problem is Elementor uses backbone and i have no idea how to bind custom events to tell Elementor editor that my hidden input field has changed. I tried these but no luck. 

```
$( 'input[type="hidden"]' ).trigger( 'change' );
```

or 
```
//elementor/assets/js/editor line 7887

$( 'input[type="hidden"]' ).trigger( 'input:change' );
```

Any help would be much appreciated.
Thanks in advanced!

**Comment by KingYes** [comment]
We working on API for that..

**Comment by premitheme** [comment]
Hi, any new on this?
Great page builder by the way.

Is there any workaround for this situation until the API is ready?
I have made a custom control. It's a clone of the text control with minor changes to open the media manager on click and send file url (video or audio) to the text field. Everything works fine, but this action doesn't trigger the needed change event to allow the editor to save. If I type in the text filed manually it saves fine.

Actually if the existing media control allow video and audio files selection (with mime type filter in the media manager), there will be no need to my custom control.

I have no backbone experience, so any guidance will be appreciated. Thanks.

**Comment by premitheme** [comment]
Hi again,
I'm not sure if I should open new issue or just update this one, anyway, I want to post some updates, bad news unfortunately...
**My problem was:** I need media control that allow video and audio selection. The provided media control is limited to images only, so I needed to create a custom control.
Since there is no clear way to trigger the needed change event to activate the editor save button on input value change when media manager sends the value to the input, I ended up doing it that way below.

**My solution:** I cloned the text control, added a button next to the text input and did the needed javascript to let it open the media manager. When you select file in the media manger instead of sending the value to the text input directly, I copy the value to clipboard, focus the text field and clear any existing value, then wait for manual paste action using keyboard shortcut. I found this way (pasting the value manually using keyboard) trigger the needed change event and make the save button active. Not a perfect solution but the best that I can came with.

**The big problem now:** After the last Elementor update pasting with keyboard shortcut no longer triggering the change event. I tried everything, triggering "change", "keypress", "keydown" or "keyup" doesn't make any difference.

Elementor is really a great page builder, I can comfortably recommend its free version over several paid solutions and I use it as the main page builder in a premium theme that will be for sale very soon. But - as a developer - that lake of a proper media control is the only downside IMO.

The existing media (image only) control is great, why not just make the minor changes to make it accept video and audio. I will be happy to offer any contribution in this matter, but my poor Bakebone experience is holding me back.

**Comment by bainternet** [comment]
API docs are ready.

https://developers.elementor.com/creating-a-new-control/

**Comment by rezarahnama** [comment]
Hi, I have same problem.
I'm trying to create custom ajax select field with select2 plugin but my js codes not work.
is there any solution for this?

**Comment by shahmanish877** [comment]
I have the same problem. I am using select2 and I can't save the selected value. So, I tried using input text field to trigger('input') when a value is selected in select2. But still can't resolve it. 
Anyone has ever built a custom control with select2?

**Comment by nimaaminz** [comment]
Same problem . . . 
And Elementor developers still working on it since 2017 . 😂😂
