### ISSUE TITLE
Change z-index value on Hover

### ISSUE THREAD

**Issue by webbteche** [pojome/elementor#2198]
Hi,

Can you add: change z-index value on hover so that elements will overlap or under lap nicely when hovering. It's good when for example: All images are placed side by side and have no gap and when you hover with a Grow animation it will stand out nicely.

Like I don't how will you do it. but I think it is that simple as this code:
```
.elementor-widget-image:hover
   {
     z-index:9000 !important;
   }
```

Can I post suggestions here? I'm sorry if does not the case. BTW Kudos for a great plugin! and sorry for bad english.

**Comment by arielk** [comment]
You can do this by adding custom code for your theme.

Why should we add this into the core?

**Comment by BigJinge** [comment]
This issue still occurs in 2020.

The key is this. If you have say three images with no gap side by side, it is common sense that if you are using a Grow Hover setting that each image would raise up and over all the other images in the section. 

Currently if you have three images across the screen image 1 grows under image 2 which grows under image 3. Only image 3 grows on the top of the pile.

This is with the Z values set to 0. 

If you change them individually, you still get the same issue.

Adding a hover option in the section to let any active image to hover over ALL other images in the section is sensible, it would work.

**Comment by LinearDynamics** [comment]
Found my way here via google search while investigating this issue.

**Comment by ToddSlaughter** [comment]
It's 2024 and this is still an issue. 

I am quite surprised that @arielk closed the issue and wrote "You can do this by adding custom code for your theme. Why should we add this into the core?" The reason why is that most people use a page builder because they don't know how to or don't want to write custom code. He should know that. He's the co-founder of Elementor.

Here's how I would add this capability to Elementor. In the **Transform** section, where we already have **Hover** properties for Rotate, Offset, Scale, Skew, Flip Horizontal, Flip Vertical, and the transition time, add a **Z-index** option. For example, on hover, my element may scale to 2x, offset a bit, and swap its z-index for 1000. When the hover is over, everything goes back to normal. A cherry on top would be to let me specify whether to do the z-index swap before or after the animation. For the effect the OP is looking for, you would want to set the z-index high _before_ scaling up, and go back to normal _after_ scaling down.

**Comment by levantail** [comment]
9 years since the original post, no improvements. By this time would even expect dynamically adding fields instead of having just pre-defines. Add the Z-index option.
