### ISSUE TITLE
[Bug] Unable to add elements above / below columns

### ISSUE THREAD

**Issue by atMaarten** [pojome/elementor#2407]
What is not working currectly: When you choose the quick-start section (with 2 colums) it is not possible to add elements above of below the colums.

When you start with this layout and want to add a title on top of the both colums later, it's not possible. You will have to start with a full width column and replace all the previous build items to this new section. This is adding a lot of extra work.

I made an GIF to show what I mean. It's not possible to rebuild the gray section, when you start with 2 colums.
![colums](https://user-images.githubusercontent.com/5883842/30521382-2687d3b2-9bbf-11e7-87c4-11d170145efb.gif)

**Comment by ramonztro** [comment]
I always get confused by that.

**Comment by bainternet** [comment]
@atMaarten 

The grey Section at the top is set to a single column and inside/nested it you have two columns.

The bottom section is set to two columns, that's why there is no place above to drop the heading widget.

So when you add the section add a single column section and inside add a column widget of 2 columns.
