### ISSUE TITLE
[Feature Request - Core]Set image instead of icon for Control_Choose

### ISSUE THREAD

**Issue by norewp** [pojome/elementor#2504]
Hello team,

Would it be possible to extend or maybe introduce Control_Choose/Control_Choose2 to use and image instead of an icon font?

Use case would a panel to say select a header type represented visually by a thumbnail placeholder rather than the icon font. Idealy the image should occupy the full width of the side panel.

TIA,
Zulf

**Comment by bainternet** [comment]
@norewp 

To achieve that you would need to extend the [Control_Choose](https://github.com/pojome/elementor/blob/master/includes/controls/choose.php) to overwrite the  [`content_template`](https://github.com/pojome/elementor/blob/master/includes/controls/choose.php#L108) method to show you images instead of icons.

Then edit [`editor.js`](https://github.com/pojome/elementor/blob/master/assets/dev/js/editor/editor.js) and add your control to the list of controls [array pointing to the choose.js](https://github.com/pojome/elementor/blob/master/assets/dev/js/editor/editor.js#L52) handler.

In theory that should be enough for it to work.
