### ISSUE TITLE
[Feature Request] Apply style to widget from existing widget

### ISSUE THREAD

**Issue by ninefootone** [pojome/elementor#2611]
It would be great if you could set a style for a widget (eg. Icon List) and then apply that style to other instances of the widget and then, when you update the master style it affects all instances. I know you can do something similar with the library but I often find myself creating a global instance which has the base styles but then wanting to change the icon/link etc. It would be nice if I could edit those elements without losing the means to manage the style globally.

**Comment by avermat** [comment]
Would love this as well. I think the easiest solution is to rework the global widgets so that you're only locking certain styles and not the entire widget. Then you could have multiple "global" icon list widgets where the styles could be managed globally (but the content could be different for each widget). 

Currently, because an entire global widget is locked, the global widgets are kind of useless (with a few exceptions like forms and social).

**Comment by ehausen** [comment]
#879

**Comment by fredsky2003** [comment]
yeah very nice.
also, i would like to know if we can build nested global widget ?
example :  
1) widget = logo
2) widget of widget = logo + menu
3) widget of widget of = logo + menu+ header

now when i change the logo (so #1) , ALL PAGES where 1) + 2) +3) are used are updated automatically!
crazy :)

fred

**Comment by themedleb** [comment]
+1

**Comment by arielk** [comment]
This feature is already released in v2.1 of Elementor, please update the plugin and you can copy & paste style between elements via right click.

Post release: https://elementor.com/introducing-copy-paste/

Thanks for your feedback!
