### ISSUE TITLE
Full width and height video doesn't work

### ISSUE THREAD

**Issue by silvioghedin** [pojome/elementor#2661]
Hello guys,I'm trying to make a full height and width page video but doesn't work: http://prntscr.com/h2k1k0

http://aprendabaixo.com.br/2017/10/23/teste-post-01/

**Comment by bainternet** [comment]
Hi @silvioghedin,

To make a video fullscreen, set the video as background and not by using the video widget.
Also you can use either youtube video, or an mp4 file but not vimeo for background videos.

**Comment by silvioghedin** [comment]
But It's video not background, I need the controlers etc.

**Comment by bainternet** [comment]
I see,

The issue here then is that the video is maintaining aspect ration in order to keep the video from being cropped or starched.

if you think about when you click the "Fullscreen" button in the control bar the video is not really full with and height, the background is set to black and you have black stripes, one above the video and one under the video.

so in your case I would try to set the background of the page to black instead of the gradient you have now to get the same "effect" .
