### ISSUE TITLE
EPro Bug - Media Carousel

### ISSUE THREAD

**Issue by norewp** [pojome/elementor#2702]
Came across this issue on FB: https://www.facebook.com/matt.tozer.10/videos/1577816155590827/ and can confirm that it appears to be a bug.

Issue 1: Switching from Slide to Fade mode breaks item count layout i.e. 3 items selected but only one displayed in Fade mode. 

Issue 2: Switching the Pause on Interaction to Yes has no effect as the animation continues when hovered.

**Comment by bainternet** [comment]
@norewp 

issue 1: Not a real issue since the "Slides Per View" should be visible only when the effect is set to "slide", we will correct that.

issue 2: Again not an issue because hover is not an interaction, if you click on next/previous slide arrows, that is an interaction and as expected the animation stops once you do that.

Thanks for reporting.

**Comment by norewp** [comment]
Thank you @bainternet and glad to hear that #1 will be taken care of.

As #2 - I'd argue that from an end user's perspective, a hove action is an interaction event for the module in a similar fashion as it is for a menu item - the interaction triggers a certain event i.e. dropdown items for the menu. Therefore one would expect the slider to pause when hovered over.

I'd classify Hover, Swipe and/or navigation Clicks to be of interaction action with the functionality of the module!

**Comment by bainternet** [comment]
:)

We use [swiper](http://idangero.us/swiper/) library for the media carousel. They defined user interaction as such, and that is why the control in Elementor is called "Pause on Interaction" and not "pause on hover".

So again we don't see this as an issue, but as you know, we are always looking to add more feature and tweaks to our widgets, and maybe "pause on Hover" will be one of them.

Again thanks for your input.

**Comment by norewp** [comment]
Cool. Let's consider this a request for "pause on Hover" as a feature request shall we? :)

**Comment by michaelpratt-swervepoint** [comment]
I agree that an interaction IS a hover. Especially when something is moving. 

Imagine using a carousel for a slider of partners, or for advertisers etc. They have the ability to have links right? So if someone hovers over the carousel, it would only make sense to pause it so they can click instead of making the end-user chase it, right? This shouldn't be a toggle separately, it should be included with the interaction button, and in my opinion, this should be default behavior that you have to specifically opt out of.
