### ISSUE TITLE
Developer API assistance please

### ISSUE THREAD

**Issue by norewp** [pojome/elementor#2819]
Hello team,

I'm in need of some assistance/pointers please - been trying to be smart but got a little stuck :D 

I've added some custom controls to the Page Settings and these work & save as expected but for the typography which only renders on the frontend only - not a biggy for now.

But my main issues are with controls added to the Global Settings and here is where I'm a little stuck - I can not get these to save although they initially render in edit mode where I get the output inline, but frontend I get nothing. Plus when I refresh the editor then my settings are no longer in place i.e. they never saved.

## Steps to reproduce

I've added a color control using the module method targeting the site title - works initially but data does not get saved let alone being output on the frontend.

## Environment

All up to date and running on PHP 7.0

TIA,
Zulf

**Comment by norewp** [comment]
Just to add to this.

Default values get printed in the global.css file but not new values are saved or retained in the controls!

**Comment by bainternet** [comment]
@norewp 

Lets have a look at the code...

**Comment by norewp** [comment]
@bainternet 

Here's a gist of the code: https://gist.github.com/norewp/ac5e7d8f80728df5b49532ceb1a27907

**Comment by bainternet** [comment]
@norewp 
I see, well a few things first:

You can target the specific section hook and avoid your internal checks from running on each section, instead of:

```PHP
add_action( 'elementor/element/before_section_start', [ $this, 'register_controls' ], 10, 3 );
```
use:
```PHP
add_action( 'elementor/element/global-settings/style/before_section_start', [ $this, 'register_controls' ], 10, 2 );
```

Then in your `register_controls()` you can remove your checks:

```PHP
	public function register_controls( $element, $args ) {

		$element->start_controls_section(
			'site_granules',
			[
				'label' => __( 'Site Settings', 'elementor-granules' ),
				'tab' => Controls_Manager::TAB_SETTINGS,
			]
		);
		$element->add_control(
			'site_granules_description',
			[
				'raw' => __( 'These are sitewide options for your theme!', 'elementor-granules' ),
				'type' => Controls_Manager::RAW_HTML,
				'content_classes' => 'elementor-descriptor',
			]
		);
		$element->end_controls_section();
		$element->start_controls_section(
			'theme_header_granules',
			[
				'label' => __( 'Header Granule Controls', 'elementor-granules' ),
				'tab' => Controls_Manager::TAB_SETTINGS,
			]
		);
                ...
    }
```
This way you code only runs once, When it is needed.

Now for your issue, The general settings tab knows only to save Elementor's native global controls. So if you have to take care of the saving yourself, and you can do that using the 
`elementor/general/settings/success_response_data` filter [triggered here](https://github.com/pojome/elementor/blob/master/core/settings/base/manager.php#L67).

And last you have the issue of the CSS generation which again currently you would need to take care of the generation yourself.

We are thinking of making a better API to add general/global settings but for now, this should get you going in the right direction.
