### ISSUE TITLE
When I hide the sidebar element, my custom widget also hide?

### ISSUE THREAD

**Issue by xttn** [pojome/elementor#2823]
Hi, please see my image to better understand the issue I want to mention
https://i.imgur.com/oyRqlnD.gif

this is my code for custom widget

```php

namespace Elementor;

if ( ! defined( 'ABSPATH' ) ) exit;

class Custom_Widget extends Widget_Base {
    
    public function get_name() {
        return 'my-custom';
    }

    public function get_title() {
        return __( 'Custom', 'text' );
    }

    public function get_icon() {
        return 'fa fa-user';
    }

    public function get_categories() {
        return array('general-elements');
    }

    protected function _register_controls() {

        $this->start_controls_section(
            'my-custom',
            array(
                'label' => __( 'My custom', 'text' ),
            )
        );

        $this->add_control(
            'number',
            array(
                'type' => Controls_Manager::NUMBER,
                'label' => __('Number of Posts', 'text'),
                'default' => 6,
                'min' => -1
            )
        );

        $this->end_controls_section();
    }

    protected function render() {
        $settings = $this->get_settings();

        $args = array(
            'post_type' => 'post',
            'posts_per_page' => $settings['number']
        );



        $defaults = array(
            'posts_per_page'   => 6,
            'post_type'        => 'post',
        );

        $attr = wp_parse_args($args, $defaults);

        $posts = get_posts($attr);
            if(count($posts)){
                    global $post;
                        foreach($posts as $post){
                            setup_postdata( $post ); ?>

                            <div class="my-custom-element <?php echo esc_attr($col); ?>">
                                <h3><a href="<?php the_permalink( ); ?>"><?php the_title(); ?></a></h3>
                                <?php the_excerpt(); ?>
                            </div>
                    <?php }
                        wp_reset_postdata();
                    } ?>
        }
}

Plugin::instance()->widgets_manager->register_widget_type( new Custom_Widget() );
```

**Comment by norewp** [comment]
I've not tested this but why are you not using the WP_Query() function to loop through the posts instead of the foreach loop? (I'm just curious) - using `global $post;` & `setup_postdata( $post );` can be resource intensive!

Also, where is the variable $col defined?

The main issue there is because you are not using the _content_template() function which would render the content of your widget in render mode. Add this `protected $_has_template_content = false;` just above the get_name() function and test again.

**Comment by xttn** [comment]
Hi @norewp, you can ignore variable $col 😄 
Can you answer me some questions?
1. Custom query `$query = new \WP_Query($args);` or `$query = new WP_Query($args);` not works for me, how does it work?
2. How to show my custom widget in preview mode if i can not get data from custom query? like this code
```php
protected function _content_template() { ?>
    <# if(settings.number){ #>
        <# what is title? #>
        <# what is excerpt: #>
    <# } #>
<?php }
```
Thank you.

**Comment by bainternet** [comment]
@norewp almost correct, `_content_template()` is optional and if its missing then the preview mode defaults to `render()` via AJAX.

@xttn 

1) if you are inside A namspace (which you are, Elementor) then `$query = new \WP_Query($args);` needs to work.

2) Again preview mode will work fine with just `render`.

But I can only guess that you have not registered your widget at the correct place (hook) and that's why it's not printing anything to the preview.

Please have a look at our [elementor-hello-world](https://github.com/pojome/elementor-hello-world)

To get a better Idea where, when and how to register your widgets.
