### ISSUE TITLE
[Improvement] Make "My Library" the 1st link in WP admin menu

### ISSUE THREAD

**Issue by drank** [pojome/elementor#2843]
Hi,

Could you make the "My Library" link to be the 1st one in the admin menu of Elementor? Currently it is the 2nd one and going into the Library requires more gestures. The Settings (which is currently the 1st item) is used much less often).

Thank you in advance!

**Comment by norewp** [comment]
That would actually make for a bad UX as the expected behavior when a user visits the Dashboard side menu is to land on a settings/option page - the only exception being Posts, Pages and CPT.

My recommendation would be to actually move the My Library which is actually a CPT out and make it a top level menu item of itself - much like how WooCommerce does with the Products CPT.

**Comment by bainternet** [comment]
@norewp 
You bring some valid points but it actually makes more sense to access "My library" for most users because in a typical site you have more users who are not an admin and they don't have access to "settings panel" anyway. So this way helps us keep the links the same for all users.

We will probably test it in the 1.9 beta phase and see the reactions and feedback.

As always, thanks for your input.

**Comment by kokers** [comment]
This additional gestures isn't an issue for me, but changing tab to "My library" when editing page and adding new section is a bit painful. Even if user is selecting some starting layout from predefined, I suspect that later on more users have their own sections saved and reuse them, so when adding new section having "My library" opened by default instead of "predefined templates" would speed up working flow.

**Comment by bainternet** [comment]
ref: #2456
