### ISSUE TITLE
[BUG] polylang - wrong editor language

### ISSUE THREAD

**Issue by kokers** [pojome/elementor#2855]
I have set WordPress language to English for site and in my user profile. 
Polylang have 3 languages: English, Polish, Deutsch.
When editing page with elementor panel elements/names/messages are in the language currently set for page (in polylang settings) instead of language set in user profile. So when I edit page set for Polish language, all elementor widgets/names are also in Polish instead of English.

It doesn't matter what language filter is currently set by polylang here http://prntscr.com/hgh19b
Elementor editor is in language that is set for page here http://prntscr.com/hgh1vq instead of WordPress settings.

This can be easily reproduced with polylang + elementor and setting different page languages.

**Comment by bainternet** [comment]
@kokers 

We are aware of this and the root cause is very simple, Elementor is a Front-End editor and it runs in the Front-End from which it takes its language.

More specifically with Polylang, we have to set the language we get from Polylang to avoid conflicts.

Sadly there we won't be changing this behavior for the time being. unless we see a large demand for it.

Thanks for reporting and feedback.

**Comment by kokers** [comment]
Is this the case with other multilanguage plugins (like wpml) or this is the case with all of them?

**Comment by bainternet** [comment]
@kokers 

Yes, as far as i know it translates the interface to the current language in both Polylang and WPML.

**Comment by Stml-Steffen** [comment]
### Will there be a solution to this problem in the future? 

At the Moment i copy the "elementor-en_GB.po" and overwrite all other the elementor plugin languagefiles with the english one, to have english language in the elementor frontend editor.
