### ISSUE TITLE
Custom Shape Divider

### ISSUE THREAD

**Issue by rachelcolleen** [pojome/elementor#2893]
Has anyone figured out a way to add your own shape divider? My co-worker has been working with the "mountains.svg" file to try to make our own, but it's not displaying correctly when I overwrite the file with our own.

**Comment by bainternet** [comment]
As far As I know, it's going to be difficult to make it work with your own svg, because we setup controls per each svg which work based on that svg structure.

If you keep the exact structure of the svg it should partially work but again not guaranteed.


currently, there is no way of adding your own svg unless, but, we will look into it in the future if we see a large demand for it.
