### ISSUE TITLE
Custom image size SVG problems

### ISSUE THREAD

**Issue by black-eye** [pojome/elementor#2929]
When using SVG image, I'm unable to resize it via custom image size. 

See the screenshot attached: 

![obrazek](https://user-images.githubusercontent.com/5634870/33846328-ab6cd418-dea6-11e7-82e6-ef72da0bdfb6.png)

- in the center, there is a SVG flag with the native size 90x60px, which I'm unable to resize to 60x40px (yes, I tried to push the Apply button)
- on the right hand side, there is the very same flag 90x60px but in PNG, flawelessly resized
- on the left hand side there is an image box with the SVG, its resizable, but I'm not sure about the units that are used 

For SVG support I'm using https://wordpress.org/plugins/svg-support/

And one more thing: it's impossible to resize ANY image above its native size. Not much usefull for the bitmaps, but could be useful for SVGs, though.

**Comment by black-eye** [comment]
And one more thing - the SVG image is actually not displayed at all (using the Elementor Image widget), until set to full or custom size.

**Comment by bainternet** [comment]
Elementor Image widget doesn't support SVG files,

When you upload an Image WordPress actually creates a resized version of an uploaded image for each image size it has defined, so it makes sense to select a size because there is an actual file/image in that size.

Not sure about the plugin you linked but I'm pretty sure WordPress will not create an svg for each size it has defined for that uploaded SVG, mainly because you can't really resize an SVG like other image types.

You can read a little about [scaling SVG](https://css-tricks.com/scale-svg/) to maybe get what you want.

thanks for the feedback.

**Comment by Skyagent42** [comment]
I have the same situation as @black-eye, it would be great to have a block in which we could add our own svg file as it is a must for speed + visual optimization! :)

**Comment by aschulz310** [comment]
5 years later... 
You just go to the 2nd tab (Style) and enter the dimensions there in px or %.
