### ISSUE TITLE
Maintenance mode icon

### ISSUE THREAD

**Issue by leon-du** [pojome/elementor#2933]
Hi, I really like your work. Just a suggestion, the maintenance mode icon bgcolor is red, it's not so matched to some themes 
![image](https://user-images.githubusercontent.com/28700378/33874803-e927a0e2-df84-11e7-8872-8d890fb3075a.png)
And the red color makes me somewhat anxious, can you please just make the icon bgcolor matching the theme color, like black for black, blue for blue? I think it won't be so hard to notice.

**Comment by bainternet** [comment]
@leon-du 

We don't change the colors of the icon or text. The colors are inherited from your selected "Admin Color Scheme", We only set the background to red to show clearly that you are on maintenance mode.

Now I do agree that specifically in the selected color scheme (which is light?) the contrast is not great and since all other schemes look good, you can simply overwrite the CSS:

```php
add_action('admin_footer',function(){
    ?>
    <style>
    #wp-admin-bar-elementor-maintenance-on > a {
        background-color: red;
    }
    </style>
    <?php
},25);
```

replace red with the color you want.
