### ISSUE TITLE
Problem with distances in Nav Menu [Elementor Pro]

### ISSUE THREAD

**Issue by lilianmurciaart** [pojome/elementor#2968]
Hi, I am writing to report a problem with the Elementor Pro navigation menu widget.
In the screenshots I give examples of what happened so you can visualize it better.
In the capture # 1 you can see how I modify the "space between" option of the navigation menu. To be able to give equal spacing from one end to the other.
![capture 1](https://user-images.githubusercontent.com/25530766/34076524-34b24f90-e2b8-11e7-97ce-5c71f8e07908.JPG)

In the capture # 2 you can see how to put the browser smaller and it happens that the whole menu is "broken", separating it into two lines of content.
![capture 2](https://user-images.githubusercontent.com/25530766/34076525-3caf706a-e2b8-11e7-9768-9ba4769dfb04.JPG)

It is necessary to note that in capture # 3 you see the tablet mode correctly as there is no problem with the cellphone mode.
![capture 3](https://user-images.githubusercontent.com/25530766/34076527-5f36f748-e2b8-11e7-8bf2-a366c53f1ac8.JPG)

My question: Is there any way to implement in the new versions of Elementor, the equidistant separation option? Thus, it will always adjust to the width of the screen without having to break. So it would be truly Responsive.

**Comment by bainternet** [comment]
@lilianmurciaart 

Thanks for reporting,

I actually see no problem, as its working just like you defined it and in order to keep the space between that, you have set it breaks the line to avoid creating a horizontal scroll bar or hiding menu items.

what you can do is set the "space between" and "font size" specifically for both "Desktop" and "tablet" viewports.

that should help.
