### ISSUE TITLE
Custom Plugin for Elementor - TinyMCE not loading properly in Editor

### ISSUE THREAD

**Issue by djekanovic** [pojome/elementor#2998]
Hi everyone,

I am working on one plugin called "Frontend Post for Elementor" which you can check here on [Wordpress](https://wordpress.org/plugins/dj-elementor-frontend/) or on [Github](https://github.com/djekanovic/Elementor-Frontend-Post-Plugin)

I am having problem with displaying it correctly in elementor editor. 

Both Render function and content template have problems. Render function displayes button's properly with TinyMCE style and size. And Content template displays buttons by default .button style. For now i just use display none so they don't appear all weird but you will se in video bellow.

What they have in common is that both times there is no additional visual buttons visible.

I would like to make this work as i have some custom styling for TinyMCE also in my widget.

Here is a [video ](https://drive.google.com/file/d/1FVLjgtH49OWMnbZ24xBRVrLWkeIk6L4C/view?usp=sharing) that summaries my words.

Thank you.

**Comment by bainternet** [comment]
@djekanovic 

Your plugin throws a PHP Notice: undefined variable my_option

also, https://github.com/djekanovic/Elementor-Frontend-Post-Plugin/blob/master/plugin.php#L40 change the handle so it won't get overwritten.

As for your question, 
To get TinyMCE to run correctly inside the preview of the edit mode, you would need to rewrite most of Elementor Elementor JavaScript. there is no easy way to do it.

I would suggest a simpler solution: in the editor, instead of having an instance of TinyMCE, insert a mockup/ markup with no JavaScript and style that.

**Comment by djekanovic** [comment]
Okay thank you.

I will try somthing like that.
