### ISSUE TITLE
How to change tab

### ISSUE THREAD

**Issue by milsorm** [pojome/elementor#3044]
Several times I read that 

```
$( 'something which returns .elementor-tab-title in desktop version' ).trigger( 'focus' );
```

will change tab.

This works only if I call it twice or call it once and click anywhere in browser. Why? In sooner version of Elementor I've used `click` instead of `focus` and that works on first call. But `click` doesn't work now.

And sometimes focus called during `document.ready` phase didn't change tab. Is there some dependency when tab can be programatically opened? What are the correct steps to open tab synchronous and always on first call?

**Comment by bainternet** [comment]
@milsorm 

We switched from `click` to `focus` for accessibility reasons, but as of 1.9, we should have an id attribute for tabs titles. which should work better.

[related commit](https://github.com/pojome/elementor/commit/0b2e9bb1e1163244588a265efd6031d6a9781a2a)
once its out you just need to trigger focus event on that id, something like:

`$(window.location.hash).trigger('focus');`
I'm closing this because it is already been merged, just need to wait for the release.

**Comment by milsorm** [comment]
But that doesn't work always. It is unimportant if I do `$(window.location.hash)` which act as `$("#some-tab-id')` or `#( 'found it my way' )`. Issue is, that `trigger( 'focus' )` open tab only sometimes, typically after second call. In Chrome.

**Comment by bainternet** [comment]
@milsorm 

Like I said 

> it is already been merged, just need to wait for the release.

if that will still won't work then please feel free to reopen this issue.
