### ISSUE TITLE
Add custom SVGs to the Page Divider to expand this content further.

### ISSUE THREAD

**Issue by gravnetic** [pojome/elementor#3058]

**Comment by bainternet** [comment]
please explain why you'd like it to be added. 
Try to add as much detail as you can, and be specific.

**Comment by gravnetic** [comment]
It seems logical that the page dividers that are offered don't or won't fit every design.  This is such a big design element users should be able to upload their own to meed the demands of a given design.

**Comment by bainternet** [comment]
@gravnetic 

Well, this is not an easy task because each one of the shape dividers we set there was also configured with a matching controls, and to upload any SVG and expect that it will work out of the box is wrong.

So currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Until then you can always create your own widget which will support your SVG.

Thanks for the feedback.

**Comment by armandn** [comment]
I second the request. It's an expert feature, of course, but it's really needed. 
It's not even that complicated, advanced developers will have no problem understanding the requirements - viewbox size, class to be used.
