### ISSUE TITLE
Integration with Grammarly

### ISSUE THREAD

**Issue by Dentalicious** [pojome/elementor#3086]
Grammarly integrates within the WP classic editor and also its Safari Extension pops up in any form field on any area where text can be inserted, even in this text box, however somehow when editing text in Elementor it doesn't pop up.
Integrations would help tremendously, kindly consider it, thx.
grammarly.com

**Comment by bainternet** [comment]
@Dentalicious 

As far as I know, Grammarly doesn't support `contenteditable` correctly because implements grammar-correcting-underlines via textarea + element on top (reasons: contenteditable is slow to render, no way to clean markup, hard to do proper selection/annotations) so it won't work anytime soon with inline editing.

But, it works just in the TinyMCE in the editor panel, just expend the panel and it should work:

![lkhrfus](https://user-images.githubusercontent.com/660572/34582261-0061af4a-f19c-11e7-8d3c-13e1e85eba42.png)

**Comment by Dentalicious** [comment]
Thx, expanding works, cheers

**Comment by rhud** [comment]
@bainternet Grammarly seems to work fine in Safari using Elementor TinyMCE fields, but not in Chrome? Is this just me?

**Comment by juliankauai** [comment]
I'm just testing out Grammarly and I use Elementor. Grammarly was really impressing me so I was going through my site correcting all the spelling and grammar mistakes, yay. But a couple days later I noticed all my videos on those pages are gone. I think Grammarly when it saves it removes html changes like embedded videos that are only seen when you switch from visual to text editing.

There is no setting in Grammarly. I'm going to have a chat with them. I don't know where the blame for this lies whether me, Grammarly or Elementor. If anyone knows please post here what's happening and if there is a solution. Thanks.

PS I'm using the latest version of WordPress, Gutenberg, Elementor and Grammarly.
