### ISSUE TITLE
Several errors due to poor connections with your home website

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#3122]
Hi, I don't know why but today I keep getting internal server errors, curl errors, and others. After upgrading to latest versions. Since your site is currently really slow (at least here, north Italy), I think it depends on that. Then, probably it would be better if there war a less important bound between your plugin and your website, since in a case like this, is going to really slow the develoment a website based on Elementor.

**Comment by bainternet** [comment]
If your site is slow it has nothing to do with the high load we had on our servers two days ago (09/01/2018).

Our servers are used only for updates and library syncs, which have no effect on your sites front end.

And we have upgraded our servers since to avoid issues like this from repeating.

Thanks
