### ISSUE TITLE
Breadcrumbs does not work properly, when used via shortcode

### ISSUE THREAD

**Issue by HelmutGoebel** [pojome/elementor#3172]
When I make Elementor section with the Breadcrumb widget and put the related shortcode in the wp editor, instead of the path it shows the name of the section.
![grafik](https://user-images.githubusercontent.com/14095280/34916838-8eb183b6-f93e-11e7-80d3-a070a29f9cb4.png)
The same, when I use the Elementor shortcode widget
When I insert the shortcode in GP Hooks > After Header (or other positions) it shows the Breadcrumbs only on the home page, not on the others.
When I inserted the section directly on a random page, it works fine. But I want to be able to insert it via hooks once.

**Comment by drank** [comment]
I can also confirm that this bug is happening in the latest version of Elementor.

Currently the Breadcrumbs widget is barely usable because it's main use is via shortcodes or hooks but it does not work with them. It only works when added to a static page but it is ineffective to add the widget to all the pages.

Dear Elementor Team, could you please add the fix to the next release? My site requires usage of breadcrumbs and I would definitely prefer to use the Elementor version instead of the bare-bone PHP code inclusion. Thank you in advance!

**Comment by bainternet** [comment]
@HelmutGoebel 

We are Working on a solution for cases like this where the Global `$post`  is used inside templates.
but for now, this will only work as a widget.

**Comment by arielk** [comment]
We fix this issue in the latest versions, please update to latest version of Elementor & E-Pro 2.0.0-beta3

Thanks for reporting.
