### ISSUE TITLE
Compatibility with the plugin Central Color Palette

### ISSUE THREAD

**Issue by black-eye** [pojome/elementor#3193]
Any chance to make your palettes compatibile with the plugin Central Color Palette (https://wordpress.org/plugins/kt-tinymce-color-grid/)?

**Comment by bainternet** [comment]
I see that a  request has already been opened in their support threads
https://wordpress.org/support/topic/integration-with-elementor/

and it should be fairly easy to do because the color pallet is stored in a single option in the options database table `get_option('elementor_scheme_color')`. 

But it feels like it should be managed on his end.

thanks for the suggestion.

**Comment by black-eye** [comment]
Well, it was me who opened the thread there, I wasn't sure on whose end the compatibility should be managed. ;)

If I'd like to change the colors in the elementor_scheme_color by myself via PHP, what would be the the right method?

Thanks
