### ISSUE TITLE
German word for "Update" is too long

### ISSUE THREAD

**Issue by Luxamman** [pojome/elementor#3204]
Since with 1.9 the way to update sites changed, also the wording changed in the German version - instead of "Update" there is the word "Aktualisieren". 
![skizze](https://user-images.githubusercontent.com/20417555/34995064-b4e4f142-fad5-11e7-8121-4d0caa71c38c.png)
The word "Aktualisieren" has the right meaning but is too long for the button design. 
I would switch back to the word "Update" because people who use Elementor will also understand the word "Update".

**Comment by dasigna** [comment]
not an elementor issue in the first row - but checked it, since i've translated this string lately :-)
youre right, but this imho is only the case when on smaller screens, lower resolutions or increased font size. not realized this on my working screens so far...

as mentioned, the term 'Aktualisieren' is the right one of choice and i dont really like using 'update' here although it would be possible as well as reasonably suitable.
maybe have some more opinions on this or eventually elementor-guys might chime in for an el-side solution with probably more space or similar???

please let me know.

**Comment by Luxamman** [comment]
In that case - thanks for contributing, still amazing how good and versatile this plugin is :)

Well, even on my 2560*1080 resolution monitor the area has a max width when opening a site for editing with that bug. The button itself seems to have a max width because the bug is there, even if I change the area width like here:
![skizze](https://user-images.githubusercontent.com/20417555/35039407-0da02ace-fb7e-11e7-814b-caae8d4aa89f.png)

And considering different screen sizes it's maybe not the best way to change the area width for all users. Unfortunately, there is no other wording for the word "update" than "Aktualisieren" - but still I think the word "Update" will be clear for most of the people and will be a quick solution. 

Thanks!

**Comment by bainternet** [comment]
Any other suggestions??? someone else maybe??

**Comment by dasigna** [comment]
Generally i'd like to stick to 'Aktualisieren' because its the definitely right term an on the other hand the same term as when editing in native wordpress page editor... so in terms of consitency it would be the word of choice.
in this case it would be up to elementor to give the button more room.

another possible solution might be the word 'Sichern' - if that earns agreement and would not lead to another confusion maybe?

what do you think?

**Comment by Luxamman** [comment]
"Sichern" or more common "Speichern" could also work, both mean "save"-  but "Sichern" could also mean "backup". 
But since Elementor is saving all the time, the meaning is maybe not the right one.

If it is possible to just give the button more space, that's fine with me!

I did not think that would be so complicated^^

**Comment by dasigna** [comment]
o.k. so i changed it to 'Speichern' for now as its basically the same Task as Elementor does automatically...

but its not the best in terms of meaning as @Luxamman mentioned too - so we might change it back eventually if elementor comes back with more room for letters.

agreed?

**Comment by bainternet** [comment]
You guys know way better then us here :)
