### ISSUE TITLE
Override section element HTML output (feature request)

### ISSUE THREAD

**Issue by hogash** [pojome/elementor#3258]
Hey guys!

I want to add some custom code into the Section element, before the `<div class="elementor-container...`.

I was thinking in one of these methods but none are supported:

- overriding Section element's HTML output;
- creating skins for Section element;
- create custom Section element;

An alternative is to create a custom widget, but it kind of loses the page builder experience to add anything inside it (other widgets, texts, buttons, etc.).

Hope you'll consider this! Thanks!

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by hybridvision** [comment]
Yes, please consider this - at the moment it seems impossible to properly customise the section element by adding new controls that influence the display.

I will post a new issue with a reference to this one, explaining my specific problem. I need to be able to add a class to the same element of the DOM tree but I can't due to the way the JS vs PHP templates work - in the JS templates I don't have access to the very top level and in the PHP templates, I seem to only be able to add render attributes to the very top level and not below.

**Comment by alarstyle** [comment]
Also need this functionality
