### ISSUE TITLE
Bug: Form redirect cannot redirect to https urls

### ISSUE THREAD

**Issue by atMaarten** [pojome/elementor#3332]
Hi,

There is a bug on the elementor redirect after sent action.
When redirecting to https://example.com it does sent them to http://example.com.

(Also it takes 5 seconds before redirecting, because of the notification. Would be nice if redirect would be instantly).

**Comment by bainternet** [comment]
@atMaarten 

We can't replicate the issue you are describing, The redirect after submit works in a very simple manner, it uses the native JavaScript `location.href` and passes directly whatever you entered in the redirect to field so make sure it is set correctly. This is also the reason it's not instantly because it happens on the client and only after the form is submitted correctly with no errors.

If you still experience this issue, please contact our support. support@elementor.com
