### ISSUE TITLE
Feature request: Form element: option so the label can be on/off for each seperate field?

### ISSUE THREAD

**Issue by knireis** [pojome/elementor#3339]
Please create an option so the label can be on/off for each seperate field? Now it is on/off for the whole form, which is not always convenient.

Deleting the content from the label field, has a big disadvantage and that is that in the email you receive there is no 'label' information specified either.
And when editing the form, there is no 'titel' available for the field to indicate which field you want to edit.

**Comment by bainternet** [comment]
@knireis 
You can leave the labels and set them to Off so in the edit you will still know which field you are editing, as for what you receive in the email you can format the email content yourself instead of the default format which depends on the labels for example, instead of:

`[all-fields]`

use:
```
Email: [field id="email"]
First Name: [field id="fname"]
Last Name: [field id="lname"]
...
```

**Comment by knireis** [comment]
Yes i know i can turn the labels off, but then they are all off which is not always convenient. 
That is why i requested a per field setting for the label.
