### ISSUE TITLE
Elementor form results going to Spam by default (Gmail)

### ISSUE THREAD

**Issue by drawcard** [pojome/elementor#3396]
Hi, I've been noticing that by default, if I create a new form and test it out, the contents of the form send out fine but get trapped by spam filters in Gmail / Google Apps. I manually have to mark Elementor form emails as "Not Spam" and set up a filter rule to stop them from heading to spam. The emails look like this:

**Subject line** 
New enquiry: Generic Form

```
How can we help?: Test 123
Your name: Tom Dick Harry
Organisation: Test Organisation
Email address: tomdickharry@gmail.com.au
Phone number: 010203020109

---

Date: February 6, 2018
Time: 5:39 am
Page URL: https://tomdickharry.com.au/contact
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
Remote IP: 123.456.789.10
Powered by: Elementor
```

Is there anything I can change to stop them from going to Spam automatically?

**Comment by bainternet** [comment]
This is a common problem with emails that are sent from a website via PHP.
Many spam filters, especially Gmail, treat such emails with suspicion. This is with good reason. Servers can be set up to auto-generate and send thousands of spam emails per hour.

Most of the times the issue is the server sending the emails getting flagged.
First, check if all WordPress emails are going into the spam folder using a 3rd party plugin like this
https://wordpress.org/plugins/check-email/

If they do then its the next step would be to either contact your host or use SMTP to send your site email. https://wordpress.org/plugins/wp-mail-smtp/

**Comment by drawcard** [comment]
Ah cool. Yeah I felt like it might be a greater issue than Elementor, but wasn't quite sure. Thanks!

**Comment by shirokoweb** [comment]
Only emails sent via Elementor form widget end in spam folder (Gmail).
System emails, or other contact plugins arrive in inbox.
I don't understand the point of adding a 3rd party plugin to make use of SMTP since it's possible to pass lot of parameters to phpmailer including DKIM to sign emails.
https://github.com/PHPMailer/PHPMailer/blob/master/test/PHPMailerTest.php
Extend the configuration of Elementor form widget with additional settings would be an issue solver.
