### ISSUE TITLE
Full size image in gallery

### ISSUE THREAD

**Issue by Elidone** [pojome/elementor#3398]
Gallery full size image
With a large number of photos of large size, gallery long loading and freezing.
Can you fix this?
my fix: 

https://github.com/pojome/elementor/blob/master/assets/js/editor.js
3056-3061

```
selection.each(function (image) {
    images.push({
    id: image.get('id'),
    url: image.get('url')
    });
});
```
------->
```
selection.each(function (image) {
    images.push({
        id: image.get('id'),
        url: image.get('sizes').medium.url // or large/thumbnail
    });
});
```

**Comment by bainternet** [comment]
@Elidone 

Can you describe the issue better?? how to replicate?

**Comment by Elidone** [comment]
1) upload 20-30 pictures 4k-8k (8-10Mb each)
2) create gallery
3) chose uploaded images
long download preview, freezing browser 

4) close page
5) edit this page again
6) chose gallery for edit

statistic:
- images: 39
- total size: 260Mb
- total time: 40s
- local

at remote server will be longer

**Comment by bainternet** [comment]
@Elidone 

The solution you are suggesting is problematic for a few reasons but mainly for:

*) If you display in the control one image and in the preview a different one then you will create a 2nd request for every image instead of just one.

*) Adding `thumb` property to the images push would mean that you save more data to that database.

This might be better for your use case (260 MB of images) but its a performance hit for the vast majority of our users.

So I would suggest you simply create your own control by extending the native one to match your use case.
