### ISSUE TITLE
Live Font Preview in the List

### ISSUE THREAD

**Issue by folivio** [pojome/elementor#3499]
**FEATURE REQUEST**
Have fonts listed in their actual font so we don't have to switch back and forth between Elementor and Google Fonts. Elegant Themes' Divi has this feature.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by krann** [comment]
Yes - I'd like this too please - or at least a URL with all the fonts listed - there's no way of knowing what they look like otherwise.

**Comment by GraemeMcG** [comment]
Yes, I desperately want this feature, too. Without it, it is like sticking a pin in the racing guide. It would be particularly good to group the fonts as serif, sans, decorative, script. With so many - and that is a HUGE positive, thank you! - there needs to be a way to distinguish them. Most (decent) design programs have the font name shown in the correct font in the list. That is all it would need. It is pretty basic to expect to see what we are applying rather than spend an hour guessing and experimenting - and kicking the cat in exasperation!!!

**Comment by PwrSrg** [comment]
+1

**Comment by folivio** [comment]
Seriously, not having font preview is like traveling back in time to the 80s. How is this not a given? I agree that there are some distressed style fonts that can tax the system when rendering the preview, but once the preview is cached it should display very quickly. A hook that pre-renders the fonts used on the site would be a nice feature to help curb the hit on lesser equipped systems, but with most of us sitting on systems that have 16GB+ of ram, TBs of drive space, and like me, use SSD drives for everything except backups.

**Comment by Arkanjil** [comment]
I'd love to see this feature implemented!

**Comment by ricmetal** [comment]
+1000

**Comment by worldccc** [comment]
Yes please add this feature!

**Comment by cswebstuff** [comment]
This would be FANTASTIC - please consider adding this feature it is VERY needed for time management.
