### ISSUE TITLE
Elementor section cache

### ISSUE THREAD

**Issue by ikovalyov** [pojome/elementor#3524]
## Feature request

Hi.
I'd like you to add option to specify if section content needs to be cached when displaying to the user. Section can have only static content and in that case the only thing needs to be done it to read HTML from cache and output to the user.
It should save lots of page load time. Also that should be good idea to add same option to the columns
Thanks.

**Comment by bainternet** [comment]
@ikovalyov this is not something we can do because each section/column could have its own CSS/styling/JS which needs to be enqueued in order for it to show and work as defined.

What you can do if you do know that the content is static and you are sure it needs not rendering you can create a custom shortcode which will act as "Cache" for you and pull that section from a template, something like:

```PHP
function custom_cached_content_shortcode( $atts ) {
	// Attributes
	$atts = shortcode_atts( [
		'template_id' => '',
		'force' => false,
		], $atts );

	$option_name = 'custom_shortcode_cache-' . $atts['template_id'];
	// Using options
	$template =  get_option( $option_name, false );
	if ( ! $template || $atts['force'] ) {
		// Not in "Cache" so we need to generate it
		$template = do_shortcode( '[elementor-template id="' . $atts['template_id']. '"' );
		// Store in "cache" for next time
		update_option( $option_name, $template );
	}
	return $template;
}
add_shortcode( 'cached_content', 'custom_cached_content_shortcode' );
```

or even better use the [Transients API](https://codex.wordpress.org/Transients_API) to have a time validation which will get you closer to something that acts like "caching":

```PHP
// Add Shortcode
function custom_transient_cached_content_shortcode( $atts ) {
	// Attributes
	$atts = shortcode_atts( [
		'template_id' => '',
		'force' => false,
		'time' => 24, // time in days
		], $atts );

	$transient_name = 'custom_shortcode_cache-' . $atts['template_id'];
	// Using options
	$template =  get_transient( $transient_name );
	if ( false === $template || $atts['force'] ) {
		// Not in "Cache" so we need to generate it
		$template = do_shortcode( '[elementor-template id="' . $atts['template_id']. '"' );
		// Store in "cache" for next time
		set_transient( $transient_name, $template, HOUR_IN_SECONDS * $atts['time'] );
	}
	return $template;
}
add_shortcode( 'cached_transient_content', 'custom_transient_cached_content_shortcode' );
```
