### ISSUE TITLE
[Bug] "Enter" key triggers Elementor mode instead of default submit action

### ISSUE THREAD

**Issue by kokers** [pojome/elementor#3556]
After editing page/post in default wordpress editor and hitting Enter, Elementor editor is loaded instead of updating a post. Not all pages/posts will be created with elementor and removing default action is very confusing. 

This happens when editing title, custom fields or any other text fields (not wysiwyg or textarea) and hitting enter. It should trigger default submit form and not elementor editor.

**Comment by black-eye** [comment]
Confirming this issue. It's happening to me quite often. 

For me, as for a webdesigner, it's just an annoying situation, since hitting the Enter is doing something I didn't expected. But I can handle the situation, I know, what's happening.

But imagine the confusion and fear of the regular editor, who suddenly triggered a function, he doesn't understand (and what more, is unable to easily turn back)! Concerning this, don't forget, there's no option to disable Elementor per user type.

**Comment by bainternet** [comment]
thanks for reporting.

**Comment by KingYes** [comment]
Thanks
