### ISSUE TITLE
Create a custom column or section.

### ISSUE THREAD

**Issue by pulla** [pojome/elementor#3561]
We need to have a column or section which we can add other widgets in the column or section.
Because we need to have our custom tags.

We have copied the column.php in original elementor plugin and changed names or titles.
But it's not showing on widget area.

How can we make them work?

Thank you for the great plugin!!

**Comment by bainternet** [comment]
Currently, You can't, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by pulla** [comment]
Thank you for your quick response. I thank you for your great plugin. we love it.

Is there any tips for our developers ( if we don't bother you a lot. if it does, you don't need to answer )


Is there any way to create a widget like column and section? 
As you may know widgets can't add other widgets. but sections, columns are possible.  is it possible to create a widget to add other widgets?

or Is there any way to add some options in columns or section? we need to add "form" tag there.

Thank you!

**Comment by stevecove** [comment]
This would be immensely helpful, being able to create a custom widget that can accept other widgets. 

At the moment we have a ton of duplication in our custom widgets, where we create a bunch of widgets that are essentially wrappers for others widgets.

Is there any public work towards this that I can contribute to?

**Comment by edemir206** [comment]
> This would be immensely helpful, being able to create a custom widget that can accept other widgets.
> 
> At the moment we have a ton of duplication in our custom widgets, where we create a bunch of widgets that are essentially wrappers for others widgets.
> 
> Is there any public work towards this that I can contribute to?

Same thing here.

**Comment by reardestani** [comment]
We also need this feature.

**Comment by zzhenryquezz** [comment]
Same here, this option will help me a lot.

**Comment by dimative** [comment]
We need this feature. Please make api for developers.

**Comment by reardestani** [comment]
@bainternet any plan to reopen this?

**Comment by mak5imov** [comment]
+1

**Comment by Desory** [comment]
+1

**Comment by webdevs-pro** [comment]
+1

**Comment by PetoFeFe** [comment]
+1

**Comment by pegues** [comment]
+1

**Comment by pegues** [comment]
The problem is that the Elementor developers built rows and inner sections directly into editor.php and other core files. Horrible idea... why did you do this? Essentially, what needs to be done is to separate rows and inner sections from the core, and then build this into the API as a feature we can then access. In other words, if they do not want to separate this then we won't be getting this feature. Fingers crossed.

**Comment by pegues** [comment]
Exploring the following: https://code.elementor.com/classes/elementor-element_column/

**Comment by yuriypolezhayevhigh** [comment]
> Exploring the following: https://code.elementor.com/classes/elementor-element_column/

any luck with that? We are also struggling

**Comment by pegues** [comment]
No luck at all. It's not possible unless you hack the core files of Elementor. And from the lack of response from the Elementor dev team, I don't think they care. It's precisely why the majority of their dev user base consists of people that have no idea how to develop websites. Elementor caters to those people, not developers.

**Comment by sf-steve** [comment]
> No luck at all. It's not possible unless you hack the core files of Elementor. And from the lack of response from the Elementor dev team, I don't think they care. It's precisely why the majority of their dev user base consists of people that have no idea how to develop websites. Elementor caters to those people, not developers.

Unfortunately, it does look like its going that way. We moved all our agency wordpress work to Elementor in 2018 because it seems like the most developer friendly layout tool (having resisted page builders for the previous 10 years), and felt comfortable with the fact that we could easily build any custom widgets we needed, and the code was well documented.
Sadly, as is often the case, it looks like the end user market is worth so much more money, that dev focused features no longer get priority.

**Comment by pegues** [comment]
Consider giving Beaver and WPBakery a look. I used to develop for WPBakery, and it is much easier to develop for once you understand how their widgets are laid out. I actually prefer dev for WPBakery because you don't have to rely on the who backbone crap, and essentially doubling your code. The footprint in Elementor is horrible.

I know how you feel. It's a shame that the core dev team really doesn't care about making the system more accessible to developers. I honestly think the reason is they made such a mess of the core in the early days of creating Elementor, they do not want to deal with the hassle of refactoring and fixing their huge mistakes. Thus, we are left out in the cold as developers for more advanced features we'd like to create.

Anyways, best of luck to you.

**Comment by sf-steve** [comment]
> Consider giving Beaver and WPBakery a look. I used to develop for WPBakery, and it is much easier to develop for once you understand how their widgets are laid out. I actually prefer dev for WPBakery because you don't have to rely on the who backbone crap, and essentially doubling your code. The footprint in Elementor is horrible.
> 
> I know how you feel. It's a shame that the core dev team really doesn't care about making the system more accessible to developers. I honestly think the reason is they made such a mess of the core in the early days of creating Elementor, they do not want to deal with the hassle of refactoring and fixing their huge mistakes. Thus, we are left out in the cold as developers for more advanced features we'd like to create.
> 
> Anyways, best of luck to you.

I am keeping an eye on Beaver, but we are unlikely to move any time soon, since we will be maintaining the numerous existing elementor sites we built for a good 3 - 5 years, so will need to keep up with Elementor anyway. We also trained our marketing people, designers and copywritters on using the Elementor front end, so thats another hurdle.

Nested widgets is the only serious issue we have - we rarely write backbone, since php rendering is fine for the editor, and any front end dynamic aspects are written in Vuejs.

Thanks for the suggestions though

**Comment by mhsdesign** [comment]
+1

a new hope? https://youtu.be/zUBG27llWKQ?t=23

btw, it does seem there is a larger demand for it - see all the closed issues because of 'no demand': #3561 #4070 #3019
this issue is more non dev orientated but should lead to fixing the inner workings of elementor: #2587

(btw. i really like how another cms, Neos Cms handles these things - one just declares the content elements and content properties in yaml and can add an option to allow childNodes (you also would have constrains and such) and so on. - that would be crazy easy if elementor could do this.)

**Comment by sf-steve** [comment]
> +1
> 
> a new hope? https://youtu.be/zUBG27llWKQ?t=23
> 
> btw, it does seem there is a larger demand for it - see all the closed issues because of 'no demand': #3561 #4070 #3019
> this issue is more non dev orientated but should lead to fixing the inner workings of elementor: #2587
> 
> (btw. i really like how another cms, Neos Cms handles these things - one just declares the content elements and content properties in yaml and can add an option to allow childNodes (you also would have constrains and such) and so on. - that would be crazy easy if elementor could do this.)

Yes, its certainly being very actively worked on, just check out the pull requests and branches on this repo - its absolutely happening, just no idea when it will make it into beta. Since it is such a fundamental change, i expect there are a LOT of bugs and edge cases to work through.

**Comment by PandaGerrie** [comment]
Almost another year past. 
Is there anyone who found any way of achieving this? Would make developing custom Widgets so much more interesting! 
Thanks!

**Comment by tinkerbaj** [comment]
I have a crazy amount of similar but different widgets with different for example inner sections. Some of them have list some have plain text. I wish I can add a container to my widget and drop what I actually need. Another really big problem for me is Repeater inside Repeater there is no way to achieve something like that.
