### ISSUE TITLE
Start (YouTube) Videos at a certain timestamp.

### ISSUE THREAD

**Issue by InDaPond** [pojome/elementor#3565]
It would be neat to start a video from a certain timestamp on the page.
This way you have more possibilities of what to show to a first visitor and you can avoid brandings. 
Imagine you have this [video](https://www.youtube.com/watch?v=vr0qNXmkUJ8&t=22) in the background with some font on top of it "This is awesome".  But the "GoPro" branding at the first 3 seconds overlaps with your font and makes it look very crappy/unprofessional.
A suggestion would be to check for extra parameters in the link (&start=x) [x is any integer] and to apply them before embedding the video.

Thank you for your time

**Comment by OldSchool80s** [comment]
I'm new to github stuff, so let's see if you even get this, since it's closed. :)

I like how you have the ability to set the start position of a video for Vimeo.
**(Known as a video bookmark)**

New: Added start/end controls for Video widget (#3565)

What I'd like to be able to do (which I can do with the ProgressAlly plugin) is use a link or button to jump to certain sections of a video (in essence setting the play head at a certain time stamp.)

This is used for allowing people to jump to certain segments they want to see. Think of a long video, say 30 minutes and you want to have 3 parts that people can jump to instead of having to watch the whole video or scrubbing. So, you set up 3 separate text links/buttons that will move the to timestamp selected for each.

**34 Minute video of Glass Blowing class:**
See glass preparation [Click Here] (say starts at 7:22 into video)
See glass shaping techniques [Click Here] (say starts at 14:01 into video)
See glass cool down techniques [Click Here] (say starts at 23:00 into video)

-----

Here it is actually how it works:
https://youtu.be/soK8sJ4XsfE?t=1m54s

* It does mention autoplay, but I know browsers killed that now. I just want the video bookmarking option.

Vimeo How To: https://help.vimeo.com/hc/en-us/articles/360000121668-Starting-playback-at-a-specific-timecode

example: https://vimeo.com/81400335#t=1m2s
example: https://vimeo.com/81400335#t=2m12s

With YouTube, as you can see when a link/button is pressed, all the video has to be is updated to the new time.

example: https://youtu.be/soK8sJ4XsfE?t=1m54s
example: https://youtu.be/soK8sJ4XsfE?t=7m31s

Again, this would help us to use longer videos and allow people to easily jump to highlighted sections.
