### ISSUE TITLE
Bug/Issue: Snap Anchor to top of each section

### ISSUE THREAD

**Issue by smile00000** [pojome/elementor#3630]
Bug/Issue: Snap Anchor the to top of each Elementor section. The anchor will not lock to the top of each section on a page and you are forced to have it above text bar or element which makes navigation to the top of each section impossible with links.

**Comment by bainternet** [comment]
@smile00000 

please provide steps to replicate, and your system info.

**Comment by smile00000** [comment]
1. Use one of the Elementor templated sections that has 2 columns

2. Once you use 2 column modules, or especially one of the preset templates from Elementor, it's nearly impossible to put an anchor at the top of that section. It will not stick. It only works by creating another blank section above it and putting an anchor in, but it's redundant and much more streamlined to put the anchor on top of the section itself.

System Info:
Mac OS High Sierra
Mac Retina 2015
Newest Version of Wordpress
Newest Version of Elementor

**Comment by bainternet** [comment]
@smile00000 

Do you have any `position: fixed` or negative margin elements? can you share a link?

**Comment by themoodmachine** [comment]
No, we don't have negative or position:fixed. 

Here's a screencast to show you using one of your templates.
https://www.useloom.com/share/084c9ca133ba43b0b577695f4d7febc9

As you can see in the video, it won't snap to the top of the section only above text...which makes them uneven and too close to the text and not what we want.

It's actually a widely known bug that support@elementor.com knows about and has been aware but apparently hasn't shared with the Developers. These are their comments at the moment. It only works SOMETIMES with a spacer widget in a section above a column...but sometimes you don't want a spacer widget. Sometimes all you want is an anchor above the columns in a section. Should be fairly simple.

"To solve this issue you can add a spacer widget at the top of the sections or you can add some padding. It's not really intuitive but this is the only solution that we have for this issue so far." - support@elementor.com 

They really need to communicate these issues to you instead of telling us to go to Github, when it makes more sense and a stronger argument to come directly from support.
>

**Comment by smile00000** [comment]
@bainternet Hello, no we don't have negative or position:fixed.

Here's a screencast to show you using one of your templates.

https://www.useloom.com/share/084c9ca133ba43b0b577695f4d7febc9

As you can see in the video, it won't snap to the top of the section only above text...which makes them uneven and too close to the text and not what we want.

It's actually a widely known bug that support@elementor.com knows about and has been aware but apparently hasn't shared with the Developers. These are their comments at the moment. It only works SOMETIMES with a spacer widget in a section above a column but it doesn't on pre-existing designs, once a column is in there you can put a space in across the entire section horizontally and sometimes you don't want a spacer widget. Sometimes all you want is an anchor above the columns in a section. Should be fairly simple.

"To solve this issue you can add a spacer widget at the top of the sections or you can add some padding. It's not really intuitive but this is the only solution that we have for this issue so far." - support@elementor.com

They really need to communicate these issues to you instead of telling us to go to Github, when it makes more sense and a stronger argument to come directly from support when they are already aware of the issue.

Thanks in advance for your help on this. :)

**Comment by bainternet** [comment]
@smile00000 

In the video you showed, the section you are trying to insert the anchor to has a `padding-top`, which is why it looks like the top of the column is not the top of the section.


This is simply how elementor works, You cant add widgets outside a section or a column.
