### ISSUE TITLE
Image Carousel slides to scroll in mobile

### ISSUE THREAD

**Issue by keilorbrown** [pojome/elementor#3697]
## Description

This is both an issue and kind of a feature request:

When adding an image carousel to a page, you can select the amount of slides to show and slides to scroll. The slides to show allows responsive options, the slides to scroll does not. In mobile, slides to scroll defaults to 1, regardless of the value in the dashboard. Put in 2, it scrolls 1 on mobile. Put in 5, it scrolls 1 on mobile.

It would be nice if the slides to scroll value was respected for mobile, or to be able to have responsive options for slides to scroll. 

Thanks!

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by keilorbrown** [comment]
You closed this because there "isn't large demand"?

It's a bug in a PAID plugin... You want to give me back my money, Raz? You allow someone to select a number of slides to scroll, then change that number regardless of user's settings. And that's normal behavior and not an issue? 

Makes sense to me... RAZ

**Comment by pingram3541** [comment]
I think this should be reopened and I think @bainternet did not realize this is definitely a logic issue with the options presented.

For example, let's say I have a carousel slider that shows 6 images desktop, 4 tablet and 3 mobile.  Currently I can set the responsive slide count but I cannot set the responsive number of images to slide.

By default it slides 1 image at a time, so in desktop 1 image scrolls out of view and disappears while another image slide into view.  No issues with other media queries when we drop to 4 or even 3.

However, if I set my slide count to 6, in desktop mode, all 6 images slide out of view and 6 new ones slide in.  When viewed on tablet and mobile, there is not responsive options to tell it only slide 4 for tablet and then 3 mobile...it will still slide 6 images!!!

This is not a small demand feature request.

![screen shot 2018-03-23 at 2 49 49 pm](https://user-images.githubusercontent.com/319284/37854780-968269d4-2ea9-11e8-935b-01029fc1cf67.png)

**Comment by viktarbel** [comment]
I would also definitely want this issue fixed. When it scrolls 3 slides on desktop you can also set to show 3 slides but you can't set 1 slide to scroll on mobiles and it still scrolls 3 per scroll. 
It should be fixed.

**Comment by keilorbrown** [comment]
Hey guys, the way I went around this was to write my own slick sliders. The slick library is included in E, so it was just learning the syntax to add settings and create my own in jQuery. Hardly a solution to this issue, but when the issue is ignored, you find your own way.

**Comment by viktarbel** [comment]
While they think this is a feature and not a bug, I created a quick script to fix it on mobiles. I just used html widget for this:

<script>
jQuery(document).ready(function($){    
	if ( $(window).width() < 767 ) {
	    $( ".elementor-element-c598e7c" ).data( "settings" ).slides_to_scroll = 1;
	}
});
</script>

where .elementor-element-c598e7c is your own unique class for carousel slider. That worked for me.

**Comment by 2amredart** [comment]
@viktarbel I can't get your script to work for slides_to_scroll = 3.
By default tablet and mobile could only scroll 1 slide at once, no matter what setting I put.
It seems that the setting is only for desktop.

**Comment by viktarbel** [comment]
@2amredart When I created a carousel slider I set slides to scroll=3 in the elementor settings so on desktop it slides 3 images per scroll. But when I checked this on mobiles then it also slides 3 images per scroll even if I see only 1 image. Pretty ugly, huh?
So when I used that script above I changed option "slides to scroll" from 3 to 1 on mobiles so it looks okay. So it should work for you too if you want to change this option for mobiles to 3 (if you set 1 for desktop for example).

**Comment by 2amredart** [comment]
@viktarbel I am using Astra child theme and Elementor plugin latest version.
Carousel 6c511a0 with slides to scroll=1.
`<div data-id="6c511a0" class="elementor-element elementor-element-6c511a0 elementor-widget elementor-widget-image-carousel" data-settings="{"slides_to_show":"7","slides_to_scroll":"1","navigation":"arrows","slides_to_show_tablet":"5","slides_to_show_mobile":"3","pause_on_hover":"yes","autoplay":"yes","autoplay_speed":5000,"infinite":"yes","speed":500,"direction":"ltr"}" data-element_type="image-carousel.default">`
Carousel 49a0f39 with slides to scroll=3.
`<div data-id="49a0f39" class="elementor-element elementor-element-49a0f39 elementor-widget elementor-widget-image-carousel" data-settings="{"slides_to_show":"7","slides_to_show_tablet":"5","slides_to_show_mobile":"3","slides_to_scroll":"3","navigation":"arrows","autoplay_speed":2500,"speed":250,"pause_on_hover":"yes","autoplay":"yes","infinite":"yes","direction":"ltr"}" data-element_type="image-carousel.default">`
Added this twice to my child theme footer.php (the last script loaded) and body of my homepage.
`<script>
jQuery(document).ready(function($){    
	    $( ".elementor-element-6c511a0" ).atr( "settings", { "slides_to_scroll": "3"});
});
</script>
	</body>
</html>`
After that on mobile it's still only scrolling 1 slide for both carousel.
Nothing seems to make it 3 slides per scroll on mobile.
I have total 7 images.
Not sure whether it's relevant but on view source " is showing as &quot;

**Comment by viktarbel** [comment]
It shouldn't be $quot; instead of " 
Try to copy script to the text editor like notepad++, replace all quotes with new quotes and then paste it to your site. You can post url here as well.

**Comment by 2amredart** [comment]
If you view via F12, it's alright.
If you view via Ctrl+U, the format is just off.
The URL is https://comparepremium.sg/

**Comment by viktarbel** [comment]
@2amredart First of all you have a jquery error on the site. I believe this is because you define jquery in the footer and one of the script you use is above the footer - on the page. You don't need 2 identical scripts.

So try to either define jquery in the header (maybe your theme allows this) and remove unnecessary script in the footer or remove script that you used in the elementor widget and leave the one in the footer.

**Comment by 2amredart** [comment]
@viktarbel Yeap, I've just removed the html widget script. I actually started with the same solution as yours except slides to scroll = 3. Nothing seems to work and finally I put the script in the footer, thinking its because the jQuery library called out at the bottom. I've even removed the window width to force it on all screen size.

**Comment by viktarbel** [comment]
@2amredart Try to use some delay on our script using setTimeout function:
https://www.w3schools.com/jsref/met_win_settimeout.asp

That's weird why it doesn't work.

p.s. in the elementor settings did you set "slides to scroll" to 1 or is it set to "default"? If it's default then try to set it to 1 and then set on mobiles to 3.

**Comment by 2amredart** [comment]
@viktarbel I've done it, is this correct?

```
<script>
	jQuery(document).ready(function($){
		var myVar;
		myVar = setTimeout(alertFunc, 3000);
	});
	function alertFunc() {
		$( ".elementor-element-6c511a0" ).data( "settings" ).slides_to_scroll = 3;
	}
</script>
	</body>
</html>
```

Did you mean "Slides to Show", if so all of them are not default.
I've changed the settings a lot of times.
If you mean "Slides to Scroll", there is no option to change between devices.
I am on Elementor free version, is that why it didn't work?

Even the modified script which is suppose to affect all screen size including desktop didn't work.
Could you send me your url that worked?
I could also compare.

It's night here, so I have sleep.

**Comment by viktarbel** [comment]
@2amredart 
No, I did mean "Slides to Scroll". I know that there is no option to change between devices but did you changed it from default to 1?

You could make it easier like this:

`<script>
	jQuery(document).ready(function($){
		setTimeout(function(){
                    $( ".elementor-element-6c511a0" ).data( "settings" ).slides_to_scroll = 3;
                }, 500);
	});	
</script>`

Timeout function is just an option that helped me sometime. Maybe it's not helpful here. But please use "if" statement for mobiles in the script like in my original post, maybe it does matter in this case. If you use browser to check how it looks on mobiles then you need to refresh the page when you made screen width like mobile screen.

And pay attention to the console log because you have a js error again.

And yes, I used premium version of Elementor but I don't think it's because of this. Try different settings for "Slides to Scroll" like change it to 3 and then check how it scrolls on desktop and mobiles then change to 1 via script, etc.

My url is https://uavcoach dot com/drone-training/

**Comment by 2amredart** [comment]
@viktarbel Yeap, I've changed it from default to 1 and other numbers. I've also changed it to your codes. I used the codes for all screen sizes because I want to narrow down what went wrong. I don't know but your codes should work no matter what screen. The issue could be somewhere else that we don't know.

I've check console this time only have this message
```
JQMIGRATE: Migrate is installed, version 1.4.1
[Violation] Forced reflow while executing JavaScript took 30ms
[Violation] Forced reflow while executing JavaScript took 39ms
```

I actually used your codes for Livemesh Addons for Elementor.
But it still did not work.
There the issue I have was the plugin limits the column per row to 5.
Actually I need 7 or more maybe in the future.
Here is the [link to their support](https://wordpress.org/support/topic/add-more-columns-per-row-for-carousel/)  where I am hope they could change this in their plugin because I actually change their plugin codes to make the columns per row more than 5.

```
<script>

	jQuery(document).ready(function($){
		setTimeout(function(){
                    $( ".elementor-element-6c511a0" ).data( "settings" ).slides_to_scroll = 3;
                }, 500);
		$( ".elementor-element-6c511a0" ).data( "settings" ).slides_to_scroll = 3;
		$( ".elementor-element-6c511a0" ).data( "settings" ).slides_to_show = 3;
		$( ".elementor-element-49a0f39" ).data( "settings" ).slides_to_scroll = 3;
		$( ".lae-carousel" ).data( "settings" ).display_columns = 7;
		$( ".lae-carousel" ).data( "settings" ).arrows = false;
		
	});	

</script>

	</body>
</html>
```
