### ISSUE TITLE
Feature Request: Language depending on user

### ISSUE THREAD

**Issue by haemeulrich** [pojome/elementor#3700]
Please do change the UX language based on the User Language not the Site language. I want to work in English also on Websites with German content.

**Comment by bainternet** [comment]
Currently, this feature is not supported, and it's not as simple as you state because it's a frontal editor and it needs to know the language and the properties of that language( ex LTR/RTL). But anyway we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

duplicate #3623
