### ISSUE TITLE
How to control settings data order

### ISSUE THREAD

**Issue by stratboy** [pojome/elementor#3715]
Hi, I have several switches:

![schermata 2018-03-09 alle 12 07 50](https://user-images.githubusercontent.com/437598/37204854-c06ac498-2392-11e8-9843-eb8a2f56e4b9.png)

My problem is that the data doesn't come in the same order of the one I instantiated the widgets:

`Object { infra_red: "", steam_injection: "tgi-option-yes", product_injection: "tgi-option-yes", tgi_icons_color: "blu", tgi_icons_type: "optionals", humidity_control: "", touch_screen: "", tutor: "", teflon_drum_door: "", drum_with_small_perforation: "", … }`

As you can see, infra_red should come after product_injection. Why aren't they correctly ordered? How to control the data order then?

**Comment by bainternet** [comment]
@stratboy 

you cannot control the order. Its an object that keeps updating based on your changes in the panel.

**Comment by stratboy** [comment]
I supposed to. Than a feature request: 

- something to use for manual ordering, for example propery-based order. Properties could be objects (or array) themselves, featuring an index prop, so I can use some handy tool like lodash to order them on the fly before rendering. The index could be auto-generated based on the add_control() calls.

- or, simply an 'index' argument to pass to add_control(), where you manual define an index option. Then, the index prop could be used to make an ordered query as above.

- or, simply output user-defined controls as an array, so you can add them on the exact order they where added by code.

It's quite a non-sense thing not to respect the order the controls where added. In my example, every switcher (and there are about 15..), shows an icon on frontend. They are product features. They simply cannot be rendered randomly. Get the point?

**Comment by bainternet** [comment]
@stratboy 

Again you ( and we ) can't control the order, its an object (JS) and not an indexed array.
Simply don't base your logic on the order of the settings because it was never meant to keep order.

**Comment by stratboy** [comment]
@bainternet I'm a developer, I know. Sometimes it seems you don't really read or try to understand what I write, don't know-- My post has turn to a feature request, and I added up to 3 ways to start thinking of it or develop.

**Comment by bainternet** [comment]
@stratboy 

I'm sorry you feel that way, but its simply not true, I read every word that is written here on GitHub issues of elementor.

As for your request, I don't see how this is something that is missing, we never needed to rely on the order of the controls for rendering.

And honestly, I don't see Elementor changing the way it saves the data anytime soon or even implementing any of the suggestion, simply because we don't see the need.

And next time, if an issue is closed, Simply replying and deciding its now a "feature request" wont do.

thanks for you suggetions.

**Comment by stratboy** [comment]
> As for your request, I don't see how this is something that is missing, we never needed to rely on the order of the controls for rendering.

Well, mine is a clear use case: then how would you solve the icons order on a widget with several switchers like mine, where every switcher show/hide an icon on frontend? Apart from coding some kind of floppy 'manual' name-based mapping?

**Comment by davelavoie** [comment]
@stratboy I came here looking for the exact same thing. It turns out you can change the order of the controls displayed, but the way to do it is still hacky. You can do it with CSS, by using a mix of `display: flex` on the parent container (where all the controls can be found), and then move the controls using the `order` property on the children (which are the controls).

Unfortunately there is no simple solution, and even with flexbox & order, it can still be tedious to achieve what you want. However, it does work!

**Comment by bainternet** [comment]
@davelavoie
He is talking about the way the data is saved and not the order of the controls are displayed in the panel.

@stratboy
You can use a repeater instead of switches and you can use the order of the items in the repeater.

**Comment by stratboy** [comment]
@davelavoie Thank you anyway :)

@bainternet Thank you but I don't think it's a good solution for my use case, I already thinked about it. The problem is that the switchers to be used for each item are several, and using a repeater would be somewhat timespending for my client. It would be really great if you implemented one of the 3 suggestions above :)
