### ISSUE TITLE
Entrance animations bug 

### ISSUE THREAD

**Issue by JoeDarko** [pojome/elementor#3746]
Hi,

im experiencing a problem with entrance animations. 

If you set "**Fade In Left**" to one element and "**Fade In Right**" to another element -  you get a scroll bar on the bottom of a browser for the duration of the animation. This is pretty popular combination of entrance animations but the scroll bar bug makes it look really bad and it's basically unusable.

I've seen this many times on other websites (Content entering form the left and right simultaneously) and the bottom scroll bar never appears. So the problem must be in Elementor. Would it be possible to tweak the animation code so this problem doesent happen?

Here is a screen:

![anim](https://user-images.githubusercontent.com/36289156/37316801-77ec2dc0-2661-11e8-8657-fbb04a6ba1cd.png)

**Comment by bainternet** [comment]
@JoeDarko 

It's not a bug, it’s expected/specced behavior.  we use animate.css for the entrance animations which defines the behavior. You can get around it by custom css:
```CSS
selector {
    max-width: 100%;
    overflow: hidden;
}
```
But it is not something we should implement because it is depended on the combination of the animations you use, and it's not possible for us to anticipate which combination you will use.

ref: https://github.com/daneden/animate.css/issues/198

**Comment by soilwork92** [comment]
@MichaelDarko You can fix this by adding the styles to the body selector: 

`body {
  max-width: 100%;
  overflow-x: hidden;
}`
