### ISSUE TITLE
New Feature Request. Preview ability for font select (example of text), or icon selector, w/mouseover magnification

### ISSUE THREAD

**Issue by Giffordcl** [pojome/elementor#3937]
I have several new feature requests but I will limit it to one at a time every few days so as not to bombard you during the 2.0 release rush :)

It would be wonderful to have the ability to see the tiny little icons larger when looking for that perfect one for your web page, a nice mouse over feature that would magnify it would do the trick I think with the ability to add an icon or batch if you can't find what you want easily from a link at the bottom of the list inside the page builder? 

On the same basic idea the ability to preview font selections, like you have in other programs like word where you see the text example of that particular selection to see if it is the one you want or similar with also a mouse over magnification.  (Ok I need glasses)  Oh and this kind of ties in with that - so so frustrating when entering text in a text field for a header or section to have to switch screens from content to style which breaks concentration and flow to select your font for that text, why can't the typography or another typography option be placed near where you are actually entering your text. 

Thank you for your consideration. 

C

**Comment by bainternet** [comment]
@Giffordcl 

The fonts preview was discussed here already so many time, its simply not something we are going to implement because its a major performance hit.

as for the icons, you can see them in the list/picker itself already and once you pick an icon you can see it in the preview as well so its kind of redundant.

but if you still feel you need to see it bigger you can use this simple lines of css which will zoom the icon on hover:

```CSS
.select2-results__option .fa:hover {
    font-size: 6em;
    transition: 1s ease-out;
}
```

![screen shot 2018-03-28 at 19 19 19](https://user-images.githubusercontent.com/660572/38042394-f096a2b6-32bc-11e8-97a9-b623b425a6e0.png)


thanks for the suggestions.
