### ISSUE TITLE
some process is reassigning my static homepage

### ISSUE THREAD

**Issue by jonathanasbell** [pojome/elementor#3981]
I am not certain if this problem involves a plugin or not, but all of a sudden some process is duplicating/editing the assigned homepage in my theme and changing the title and excerpt to that of another page or post. All of a sudden I go to the homepage and its got a new title and excerpt. Anyone else experiencing this?

**Comment by bainternet** [comment]
We didn't get any reports like that, so try the basic troubleshooting to pinpoint the trigger:
- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).

feel free to open a new issue if the problem is caused by Elementor.

**Comment by jonathanasbell** [comment]
See the following screenshot video

https://drive.google.com/folderview?id=1Y4y3a1ktS06CZVd2RcD2SyMuMQsBdJ3e
