### ISSUE TITLE
Feature Request: Forms - Conditional Logic

### ISSUE THREAD

**Issue by themklife** [pojome/elementor#4003]
Important request: Conditional Logic is a top requested feature for the forms module of Pro. All of my clients need the ability to determine notification (email) based on a form selection (pop-up or other. We respectfully request this feature be added ASAP. Thank you.

**Comment by drank** [comment]
+1

**Comment by mcpeanut** [comment]
+1

**Comment by bainternet** [comment]
You can use the provided filter hooks to achieve that, for example, set your "email to" as the select field shortcode `[field id="department"]` and use the sanitize filter to set the email based on the selection:

```PHP
add_filter( "elementor_pro/forms/sanitize/select", function( $value, $field ){
    // Check that this is the correct field
    if ( 'department' !== $field['id'] ) { return $value; }

    $emails = [
      'support' => 'support@domain.com',
      'sales' => 'sales@domain.com',
      'info' => 'info@domain.com',
    ];
    return isset( $emails[ $value ] ) ?  $emails[ $value ] : $value;
}, 10, 2 ); 

```
or even simple if all the email address are on the same domain:

```PHP
add_filter( "elementor_pro/forms/sanitize/select", function( $value, $field ){
    // Check that this is the correct field
    if ( 'department' !== $field['id'] ) { return $value; }

    return $value . '@domain.com';
}, 10, 2 ); 
```

if that doesn't answer your issue please feel free to reopen.

Thanks for the feedback.

**Comment by laratuk** [comment]
I found this feature in Piotnet Addons. It has Conditional Logic Form + Range Slider Field https://pafe.piotnet.com/#conditional-logic-form

**Comment by davebeauchemin** [comment]
Is it just me or the code below don't work? I added the code to my plugin-name.php, change department to my correct select field ID and I always get "Server error. Form not sent.". Does the filter have been updated since last year? Thank you for your help!

Email to: [field id="dealer"]

`add_filter( "elementor_pro/forms/sanitize/select", function( $value, $field ){
    // Check that this is the correct field
    if ( 'dealer' !== $field['id'] ) { return $value; }

    $emails = [
      'brossard' => 'my@email.com',
      'boucherville' => 'another@email.com',
    ];
    return isset( $emails[ $value ] ) ?  $emails[ $value ] : $value;
}, 10, 2 );`

**Comment by spac-em** [comment]
Pionet has lifetime for $60  . quickly grab it ,.https://pafe.piotnet.com/

**Comment by narinder9** [comment]
Hi Everyone 👋,

Like many of you, I was also **waiting for Conditional Logic support** in Elementor Forms. Since this feature is still not available, we decided to **build a solution** ourselves!

We have created a **free plugin** : [Conditional Fields for Elementor Form](https://wordpress.org/plugins/conditional-fields-for-elementor-form/)

With this plugin, you can **show or hide form field**s based on values entered in other fields using simple "if condition" logic.

> For example: If option A is selected, show Field XYZ. If not, keep it hidden.

👉 [Check out the live demo](https://coolplugins.net/product/conditional-fields-for-elementor-form/?utm_source=elementor_repo&utm_medium=issue_comment&utm_campaign=demo&utm_content=2638#demos) 


Give it a try and let us know your feedback — I’ll keep improving it based on your suggestions.
