### ISSUE TITLE
Accordion - setting for all closed at start

### ISSUE THREAD

**Issue by davidmcc3** [pojome/elementor#4015]
I've started this issue again as the previous one (#2481) has been closed - the issue has not been fixed, even though bainternet said on 13th Nov 2017, that it had been fixed in 1.8

I've just upgrdaed a site to 2.0.3 ... and the Accordian still loads with the first item open ... and there's no setting I can find to change this behaviour.

So ... original post ...>>

When Accordion is first displayed at page load, the first element is always open - would like a setting so all can be closed when page loads.

arielk commented (and closed the issue) "For this option please use Toggle widget instead of Accordion"

Unfortunately, Toggle doesn't work the same as Accordion ... elements have to be closed manually. In Accordion, there is only ever one open at a time - which is the behavior I want - so Toggle isn't a substitute.

Where there is a longish list (e.g. and FAQ), it's better for the visitor to see all the list headings before chosing ... it doesn't make sense to have the first item open, as it probably isn't appropriate to the visitor.

**Comment by Ammikas** [comment]
I faced the same issue and was also waiting for the fix. Meanwhile, I used [Code Snippets](https://wordpress.org/plugins/code-snippets/) Add the following code to a Code Snippet and set the snippet to ‘Run everywhere’. 

NOTE: Make sure you click the “Save Changes and Activate” button!

function elementor_accordion_title() { ?>
	<script>
		jQuery(document).ready(function() {
			jQuery( '.elementor-accordion .elementor-tab-title' ).removeClass( 'elementor-active' );
			jQuery( '.elementor-accordion .elementor-tab-content' ).css( 'display', 'none' );
		});
	</script>
<?php }
add_action( 'wp_footer', 'elementor_accordion_title', 99 );

**Comment by bainternet** [comment]
@davidmcc3 

You are asking for accordion but you don't want it to behave like an accordion...

An Accordion *Always* has one pane open, thats just how it works. Now if you want it closed by default, then its not an accordion, and that's why we have a toggle widget. ( which was fixed in v1.8.x, the linked issue).

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by aymeric-wisepass** [comment]
I support this feature request. Very important when dealing with FAQ pages where toggle is not a good option either.
Also, @bainternet please reference this "An Accordion Always has one pane open, thats just how it works." because that is totally untrue and your "dude just trust me" ain't gonna work here.
https://www.w3schools.com/howto/howto_js_accordion.asp -> starts closed.
https://codepen.io/raubaca/pen/PZzpVe  -> starts closed.
http://freefrontend.com/css-accordions/ -> most start closed, some don't
Thus an Accordion does **not** _Always_ have one pane open.

**Comment by AymarM** [comment]
I also support this feature request.

**Comment by donwattz1459** [comment]
I also support this feature request.

**Comment by dougrintoul** [comment]
@Ammikas your code seems incomplete. At least it gives a syntax error when used with Code Snippets. Should there be more after the final </script>?

**Comment by Ammikas** [comment]
Hmm @dougrintoul
Somehow it shows only half of my message, When I click edit, I will see the full message. Check the pic
![screenshot_10](https://user-images.githubusercontent.com/38095191/38659358-e09fb02a-3e31-11e8-8285-9cdf27ec6d70.jpg)

Here is the code again:

function elementor_accordion_title() { ?>
	<script>
		jQuery(document).ready(function() {
			jQuery( '.elementor-accordion .elementor-tab-title' ).removeClass( 'elementor-active' );
			jQuery( '.elementor-accordion .elementor-tab-content' ).css( 'display', 'none' );
		});
	</script>
<?php }
add_action( 'wp_footer', 'elementor_accordion_title', 99 );

**Comment by black-eye** [comment]
+1 This option should be definitely enabled. 
I actually don't get the point, why to have 2 widgets (accordion & toggle) with almost same functionality, with the only one main difference, which is opening behaviour. 

And one more reason - it's really frustrating when you complete your task (e.g. FAQ) and then you (or more likely, your client) realize that you need the functionality of the other widget and you have to start all over again.

**Comment by 60wattmax** [comment]
Another option that was mentioned in one of the many other threads on this topic and worked for me ...

Plugins > New Plugin > Search: Granular Controls for Elementor > Install/Activate
Admin Menu > Elementor > Granular Controls > General Controls Tab > Accordion's Closed? > YES!
Save Changes! ... works like a charm! 

Thank you to the other contributor that mentioned this plugin :)

**Comment by davidmcc3** [comment]
Still no proper resolution to this, it seems.
Can't understand why the Elementor Team have been so reluctant to fix this.

**Comment by thinkpura** [comment]
This is such a serious issue- I'm shocked it hasn't been addressed.  I tried just hand-coding a workaround but every time there is a new update, I have to do it over again.

I've tried all of the suggestions here and in other threads and no luck.  I'm using Pro version, and considering changing to another editor because of these glitches.

**Comment by thinkpura** [comment]
Reinstalled granular controls for elementor and toggled "accordion's closed" option.  Voila!  

I still think it's a bit unnecessary to have to install a separate plugin to do this.

**Comment by davidmcc3** [comment]
What I find most worrying (for the future) is that this is being ignored. It's a blot on the Elementor copybook.

**Comment by zefflubrano** [comment]
+1 for this!

**Comment by bainternet** [comment]
I merged this issue with  #2756, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by bentalgad** [comment]
+1

**Comment by bentalgad** [comment]
+1

**Comment by bentalgad** [comment]
Btw - Same thing with the "Toggle Widget"

**Comment by Haloan** [comment]
I think a compromise solution between either side would be to simply have an option to select what is the default behavior of the accordion - open or closed. That's what SiteOrigin has on theirs. 
Actually SiteOrigin has the option for each panel so you can choose the default state for all of them separately if you have more than one. 
IMO having two different widgets which seem to be about the same to solve this issue is not the answer. Just have one widget with the option. Or have both but just put in the option! Thanks in advance!

**Comment by lord-srujan** [comment]
Here is the final fix to this problem

A workaround I’ve seen is to leave the first item blank (or put anything in it, doesn’t matter what) and then use this CSS to hide it:

`/* Hides the first accordion item */
.elementor-accordion .elementor-accordion-item:first-child {
display: none;
}
`

This must fix the issue.

**Comment by Franky-Four-Fingers** [comment]
> 
> 
> @davidmcc3
> 
> You are asking for accordion but you don't want it to behave like an accordion...
> 
> An Accordion _Always_ has one pane open, thats just how it works. Now if you want it closed by default, then its not an accordion, and that's why we have a toggle widget. ( which was fixed in v1.8.x, the linked issue).
> 
> Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.
> 
> Thanks for the feedback.

Really now. So tell me, when you start playing the accordion, is it open or closed?

**Comment by Franky-Four-Fingers** [comment]
> 
> 
> Here is the final fix to this problem
> 
> A workaround I’ve seen is to leave the first item blank (or put anything in it, doesn’t matter what) and then use this CSS to hide it:
> 
> `/* Hides the first accordion item */ .elementor-accordion .elementor-accordion-item:first-child { display: none; } `
> 
> This must fix the issue.

Yeah nice, did you test it? Top border is gone now.

**Comment by FrankLauda** [comment]
+ 1 for the option to be all closed on pageload

**Comment by jasonb4u** [comment]
its 21st May 2021 and still no option to have closed or open on page load, come on Elementor !

**Comment by BrandBox22** [comment]
+1
