### ISSUE TITLE
Custom element or Widget inside Widget

### ISSUE THREAD

**Issue by justpie** [pojome/elementor#4070]
Is it possible to create a custom element ( not widget )? I've tried and got the system to load it using register_element_type but I'm  not sure how to add it to the page without modifying the core editor files ( which i wont do ). 

Ideally i'm trying to create something like the accordion widget ( something that uses a repeater ) and still allow columns and sections to be created in each area.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by mylimoproject** [comment]
I second that request and would find it very useful/time saving. I've been tweaking here and there learning my way around and wished I could do that on the tabs widget (icon list, carousel, price tables, posts, etc..). 
It shouldn't be that difficult or time consuming since other 3rd party widgets have found the way to show up as an widget inside widget option (see [tabswidget] feedback img).

http://wordpress.airportspickup.com/
http://wordpress.airportspickup.com/miami-carservice-airport-transfers-limorentals/

![miami-tab](https://user-images.githubusercontent.com/29313121/38660406-1c4c5e2a-3dfb-11e8-9563-fdc31a9b5ce0.JPG)

![tabswidget](https://user-images.githubusercontent.com/29313121/38660166-492ab046-3dfa-11e8-9a3b-3ca0e7fdc107.JPG)

 Also, I will be requesting the following "page settings" requests.
1) background overlay
2) body background-color  (I am able to get around this one with custom css, but not everyone has the skills to figure out what to do and I believe your goal is to be #1 and non-geek approved -)

**Comment by alarstyle** [comment]
I also need this feature

**Comment by jaycburton** [comment]
+1

**Comment by alarstyle** [comment]
+1

**Comment by surajkhanal** [comment]
+1

**Comment by alarstyle** [comment]
@bainternet Are you going to implement this feature in nearest future?

**Comment by Nicoduweb** [comment]
We need it !
At least for Tabs and Accordion Widget, and Box too please.

**Comment by nathanael540** [comment]
Any progress?

**Comment by dusanbre** [comment]
+1

**Comment by pegues** [comment]
I might need to develop this for a project. More than likely, what could be done to create this behavior is make a duplicate of the "Inner Section" widget and customize that as your outer wrapper. You would then still have the ability to drop other widgets inside it.

**Comment by pegues** [comment]
Looks like the inner section widget is baked into editor.php and a number of other files. Sad. If I have time I'll still try to remake.

**Comment by pegues** [comment]
I created the following issue, but no response:
https://github.com/elementor/elementor/issues/13126

I added a plugin with the added element. But the element won't load like a custom widget can be loaded.

**Comment by SheezaMonsta** [comment]
Has this feature been added?

**Comment by nimaaminz** [comment]
really need this feature

**Comment by pixelbart** [comment]
+1
