### ISSUE TITLE
Work with the Paid Memberships Pro plugin

### ISSUE THREAD

**Issue by JBerendes** [pojome/elementor#4072]
Before closing because it relates to another plugin, I was asked to post here because of my Twitter post - [Elementor and Paid Memberships Pro - broken](https://twitter.com/JacobBerendes/status/983373622059454464)

# To reproduce: 
1. Install elementor
2. Install Paid Memberships Pro
3. Create a subscription level in Paid Memberships Pro
4. Create a page with content built in elementor
5. set that page content only be visible to that subscription level

# Expected:
Non-member should see something like, "This content is only available to members"

# Actual:
User sees Elementor content and as and Admin attempting to edit the page with Elementor almost always comes up as unavailable.

**Comment by bainternet** [comment]
@kimcoleman 

Thanks for stoping in, let us know how we can help. feel free to contact us, support@elementor.com

**Comment by JBerendes** [comment]
@kimcoleman do you have any examples that work with the Code Snippet plugin? If not where and when do you expect the recipe to be included and resolve, include in functions.php header.php? Basically everything I've tried has failed to get these two plugins to work in the way I would expect.

**Comment by JBerendes** [comment]
To boil down the plugins i'm using: OceanWP for the theme, Elementor and Elementor Pro for page building and content, Paid Memberships Pro for subscriptions and gated content(Elementor created content)

I'd like to use the code snippet content to drop in what you call "recipes" but editing an existing file functions.php header.php and also an option or dropping in an additional file and including it would also be an option.

I'm feeling pretty burnt by trying to put Elementor and Paid Memberships Pro together in my site.

**Comment by littlerockdesign** [comment]
@JBerendes Did you find a resolution to the issues you've been having with Elementor and Paid Memberships Pro working together? I am having a similar issue... I can't edit any of the Pmpro pages with Elementor

**Comment by oldrob57** [comment]
I can't get these two to work together either! Really a shame. If you do anything to a page you want to protect using elementor, it is no longer protected

**Comment by physiostasis** [comment]
I am also using OceanWP theme, Elementor for page building and PMPro for membership. On the PMPro pages only I keep getting the error message about the_content() function not being called and to check the template. The exact message reads as follows: 

"Sorry, the content area was not found in your page. You must call 'the_content' function in the current template, in order for Elementor to work on this page."

My page: http://physiostasis.us-east-1.elasticbeanstalk.com/

Any advice? Thanks!

**Comment by physiostasis** [comment]
@jberendes three months later... did you wait that long? Looks like I have the same issue and yours wasn't resolved...

https://www.paidmembershipspro.com/forums/topic/the_content-error-incompatibility-with-pmpro-on-oceanwp-and-elementor/#post-157259

If anyone finds this link, save your money and check out LearnPress and LearnDash, they have those issues resolved. $147/yr and you're stuck before you begin.

**Comment by kimcoleman** [comment]
I am not sure I am clearly understanding the issue. I want to first clarify that you cannot edit the content within the required shortcodes on the Membership pages. When using the Elementor Editor, these shortcodes will in most cases just need to use the Shortcode widget of Elementor and place the appropriate shortcode within. It will not render in the preview pane. It will render on the front end of the site when you view the page. In short, these shortcodes are not available for custom editing in Elementor or any other WordPress editing environment at this time. 

By taking the steps outlined in this recipe (being sure to set a pmpro_default_level custom field on the Membership Checkout page only), I am able to fully edit each of the pages created and associated with Paid Memberships Pro areas of the site. I am using:
- Paid Memberships Pro
- Elementor
- OceanWP as my theme
- The customization code in a plugin for PMPro Customizations as outlined in these two links: 
-- https://gist.github.com/kimcoleman/19265deeb657228b4922eb6bccee38f9#file-elementor_compatibility_for_pmpro-php
-- https://www.paidmembershipspro.com/filter-members-only-content-later-for-page-builders-and/

I have not seen the error reported by @physiostasis regarding the_content filter. Can you please write a detailed list of how to recreate this error?

**Comment by physiostasis** [comment]
Hi Kim,

I have posted my information on this forum: https://www.paidmembershipspro.com/forums/topic/the_content-error-incompatibility-with-pmpro-on-oceanwp-and-elementor/

I am working with Andrew Lima: https://www.paidmembershipspro.com/forums/users/arctek/

Can you get in contact with him? I gave him Admin access through the  info@paidmembershipspro.com email. I also sent the following to him through private message:

 try what you can with this Admin access and please advise. I found this YouTube video about editing the theme template: https://www.youtube.com/watch?v=RbyiwwPOfJA&t=165s
However, the problem is not the theme because I tried GeneratePress and still same problem. Kim Coleman (co-developer PMPro) here (https://github.com/pojome/elementor/issues/4072#issuecomment-406588270) says she used my same setup with no problem.

The only issue is with four pages as mentioned above: Account, Cancel, Checkout, and Confirmation
It is not theme, because I tried another theme. It doesn’t happen on other pages. Only those four PMPro pages.

I noticed if I don’t assign the pages under the Membership Page Settings to their page, then go back and edit with Elementor that it works. For example, I go back to Page Settings and under the drop down menu I change the page assignment to “Choose One” then scroll down and click “Save Settings” Then I go to the page and edit with Elementor and it works. When I go back and assign the page to Account, then it doesn’t let me edit with Elementor and gives me the the_content error. However, all pages still display fine on user end of things and work, including Membership Checkout.

There appears to be a problem with the coding behind the shortcode for those four pages mentioned above that don’t call the_content(). Again, due to my limited programming background that is all I could figure out.

Kim Coleman mentioned to put the shortcode in an Elementor widget and I was always doing that since the beginning. You will see on login.

Please advise. Thanks.

**Comment by kimcoleman** [comment]
We have discovered that with Elementor, in addition to adding the mentioned code recipes and custom field specifically to the Membership Checkout page, you must also have a Membership Level for your Administrator account. This is due to the fact that the Elementor plugin / editor is trying to offer you a “preview” of the page, while our membership plugin is trying to restrict your access to these members-only pages. The preview is caught (somewhat) in confusion. Having a membership on your Admin account (even you create a hidden, private level that only your Admin account has) resolves this.

**Comment by clecastilho** [comment]
Hi Kim, how can i do that?
Can you show us a step by step?

**Comment by clecastilho** [comment]
Thank you very much @physiostasis , it worked perfectly, but I had to make some changes in sections 1 and 2 of your tutorial.

I could not install the "pmpro-customizations" plugin after it was changed, so I installed it first without any changes and it worked. Then I changed it using the Edit option in the Plugins menu and I inserted ALL OF @kimcoleman 's code "elementor_compatibility_for_pmpro-php", not only to line 24, because although it works in some browsers, I understand that it is necessary to close the functions, to avoid future errors. So I followed exactly what was described in section 3 and worked correctly as expected. We also did not have to make any changes to the checkout page, maybe @kimcoleman could explain us better about the need for this change as she reported above.

About your concern on doing this tutorial, it was really cool of you, because not everyone does it that way and really, people need to find a step by step that instructs them correctly about what needs to be done, without it needing to stay searching on multiple sites, and could have found the solution and solved their problem more efficiently and quickly.

It really looked great. Thank you again!

**Comment by TerenceMilbourn** [comment]
> @clecastilho here is what I did...
> [deleted]
> (e) Go to this link and copy ONLY lines 2*-24 
> [deleted]

I am guessing that changes subsequently made to this gist mean those numbers are not now correct.  For the benefit of novice code divers that come after this post, that line should read...

> (e) Go to this link and copy ONLY lines 2*-27

Hope that helps.

**Comment by TerenceMilbourn** [comment]
> We have discovered that with Elementor, in addition to adding the mentioned code recipes and custom field specifically to the Membership Checkout page, you must also have a Membership Level for your Administrator account. 

How is it possible that when setting up pmpro that the admin user is NOT granted a membership level?  Or, let me put that another way, wouldn't it be a good idea, with so many of us using Elementor, that this is the default position; that pmpro does this out of the box?
