### ISSUE TITLE
[feature request] Custom login widget - disable standard WP login page

### ISSUE THREAD

**Issue by rich73625** [pojome/elementor#4091]
Goal: Taking the login Widget one step further, so that it's not just for linking to from the front end of the website (i.e. with a link to "Login")
When creating a login page (and a new URL for that page) it would be good to be able to use that login page as the default login page for the client (and admin) and **disable** the WP login page.

Yes, I could use a plugin to change the wp-login address to something ridiculous so that no-one could ever guess it which would effectively disable it for people guessing, **and** force everyone to use the custom URL Elementor login page but it would be nice not to have to use another plugin.
That way we can create a lovely login page with Elementor (Pro) on it's own custom URL (good security) and easily disable/remove the WP login page at the same time.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by Cyberdemon87** [comment]
+1 that would be awesome. Exactly what I was thinking.

**Comment by dribgib** [comment]
This is needed - what's the point of a login widget if it's not the default login portal? Seems like the minority of cases can use this as is.

**Comment by dribgib** [comment]
btw - a crude method to at least get the login widget working is create a page with your login widget and use this in functions:

```
add_action ( 'template_redirect', 'redirect_login' );
function redirect_login(){
    if ( is_user_logged_in() && is_page('PAGEID') ) {
        wp_redirect('/REDIRECTURL') ;
        exit();
    }
}
```
Replace PAGEID & REDIRECTURL as needed.  Then just use your menu to link to your login page you created, it should show for logged out and redirect to account page for logged in.

**Comment by EnjeruTantei** [comment]
This feature would be amazing. I just experienced a full-on denial-of-service attack from multiple IPs on my website this morning, and it was down for hours. I finally got ahold of someone at IT that was able to reset it for me. As I result, I attempted to hide/disable _wp-login.php_ but in doing so, I broke my main login widget since Elementor relies on _wp-login.php_. I obviously cannot leave it that way, or keep it the way that it was because that would be broken or vulnerable. Please implement this feature soon.
