### ISSUE TITLE
WPML & Elementor Pro UX

### ISSUE THREAD

**Issue by MAthez** [pojome/elementor#4117]
Using Elementor with WPML is great, but really complicate to navigate between translations, front and back office, because both Elementor and WPML miss the links to do so.

For example when I edit a page from Elementor Editor in English, if I want to go the the French translation, I need to jump to WP Dashboard, then search the page, then edit its translation. Doing so with several pages, you end up with dozens tabs open, and a real useless fatigue.

I wish I coul easily, from the Elementor editor :
- jump to the page view (in front end)
- jump to WP editor of the same page (back end)
- jump to edit the translation of the same page (back end)

Also from WPML editor, I wish I could edit the original in Elementor again.

**Comment by bainternet** [comment]
Well,

 * jump to the page view (in front end) - You can its called preview.
 * jump to WP editor of the same page (back end) - You can its called back to dashboard.

only  
>jump to edit the translation of the same page (back end)

Its something we can't do because Elementor doesn't add the languaes and is not really awere of them. Its hould be donr form the translation plugin's side.

thanks for the suggestion.
