### ISSUE TITLE
Using _content_template() for skin

### ISSUE THREAD

**Issue by sushmak02** [pojome/elementor#4171]
## Description
I am implementing skins in my widget. I want to add _content_template() for it. How can I do this?

**Comment by dudaster** [comment]
Here is a example of how to make a skin https://wordpress.org/plugins/ele-custom-skin/

**Comment by sushmak02** [comment]
Thank you for the reference @dudaster .

But I am looking for how can I render element output in the editor to generate the live preview, using a Backbone JavaScript template i.e the `_content_template()` function implementation.

Is it even possible to do that?

**Comment by sandeshjangam** [comment]
_content_template() function not working in skins. @bainternet

**Comment by KingYes** [comment]
Yeha.
For now, skins not working with JS templates.

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by gvgvgvijayan** [comment]
Expecting this functionality, want interactive content in the editor screen for custom skins. Explored all code in depth no hooks for both in PHP and JS found.

Even tried something like this in custom skin constructor

```
      public function __construct( Widget_Base $parent ) {
		parent::__construct( $parent );
		add_filter(
			'elementor/widget/print_template',
			array( $this, 'skin_print_template' ),
			10,
			2
		);
	}

	public function skin_print_template( $content, $widget ) {

		if( 'buttons-kit' === $widget->get_name() ) {
			?>
			<#
			console.log(settings.button);
			#>
			<?php
		}

		return $content;
	}
```

But this is not working instead that it rendering as HTML see here:
https://github.com/elementor/elementor/blob/069e890bc2ee5d0d679a6ac2f3ab8a4fbabf6b9b/includes/base/controls-stack.php#L1681

At least if Elementor provided a parameter to control the script type instead of hardcode it with `text/html` will be helpful for the developers to do interactive skin logic using JS in the editor screen
