### ISSUE TITLE
Nested Columns

### ISSUE THREAD

**Issue by bkonia** [pojome/elementor#4176]
I recently switched from Thrive Architect to Elementor. I've discovered Elementor has many advantages over TA, but also has one HUGE shortcoming. With Elementor, you can nest a column within a column, but only one level deep. TA supports infinite column nesting, which makes it much easier to create complex page layouts.

I understand you can partially work around this limitation by creating a template from a Columns widget and inserting that template into another Columns widget, but this solution is neither practical nor scalable. Therefore, I'm wondering if support for infinite columns nesting is on the roadmap and when we could expect it?

**Comment by pulla** [comment]
+1

**Comment by black-eye** [comment]
+1

**Comment by tristanleboss** [comment]
+1

**Comment by bainternet** [comment]
I merged this issue with  #2587, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by cceglia** [comment]
+1

**Comment by nicholaszein** [comment]
Hello, everyone!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was introduced with Elementor **v3.6**, and is now a stable experiment since Elementor **v3.8!** 🥳 

✔️ Feel free to check it out and update your plugin to the new version!

Stay tuned for the next versions that will introduce Nested Accordions as well. 

🗨️ Please continue the conversation in issue #2587.

Cheers 🥂
