### ISSUE TITLE
Memcache - Elementor Pro

### ISSUE THREAD

**Issue by Dentalicious** [pojome/elementor#4179]
Hi,

Post upgrading my hosting plan from shared hosting to 'dreampress', with the host 'DreamHost',  I have been having issues for a few months now, wherein, post 'elementor pro' plugin updates (not elementor, but elementor pro), the site would look wonky as the cache was not getting cleared, to resolve this, I had to repeatedly raise tickets and seek help from the support team at Dreamhost to manually clear the cache.

This is how the site looks post updating the plugin 
https://imgur.com/dvLyHSw

This is what they say about elementor pro.
1)
...The issues here are being caused by the elementor
plugin. It creates special CSS files and these files were missing from
the uploads elementor directory. You can regenerate these files at
https://www.dentalicious.com.au/wp-admin/admin.php?page=elementor-tools.
Make sure after doing this that you also purge the varnish cache by
clicking the "empty cache" link in the admin tool bar. Everything should
be loading normally now. The main problem is that this plugin does it's
own thing with separate CSS files....

However, issues were not resolved even by doing this, on digging deeper, they wrote this,

2)....
It was actually Memcached caching that was causing it to act wonky, not
Varnish. Unfortunately, there isn't a plugin that can be used to clear
Memcached. It needs to be done manually using the command line. If you
are familiar with the command line you can connect via SSH and run `wp
cache flush` and that should take care of it.......

Just flagging issues faced by me and the issue here is that 'elementor pro' plugin updates are causing memcache caching issues and if anything that can be done from your side that would assist and make life simpler without having to go through the whole command line process cycle, then kindly have a look at it.

Thanks.

**Comment by pdclark** [comment]
Hi — Paul here at Dreamhost technical support.

As Dentalicious mentioned, we are running Memcache object cache + Varnish here on DreamPress.
The post-upgrade layout issue Dentalicious encountered with Elementor appeared to resolve when we flushed object cache. (CLI: `wp cache flush`)

A possible resolution for all users might be found by calling the `wp_cache_flush()` (function, not CLI) on the `upgrader_process_complete` hook, or a similar post-install / post-upgrade check & cache refresh. (The WP CLI command is slightly different than the `wp_` function, but it should have an effect.)

These docs may be relevant:
https://developer.wordpress.org/reference/hooks/upgrader_process_complete/
https://codex.wordpress.org/Plugin_API/Action_Reference/upgrader_process_complete

If there's anything we can do to assist further in debug, please let us know:
The Dreamhost ticket number for this issue #8177713 — anyone on the team can look for further details for testing over LiveChat or email.

Hope that helps!

Have a great day.

Paul

**Comment by bainternet** [comment]
@Dentalicious 

We have added a new action hook `elementor/css-file/clear_cache` which runs when we clear the css cache so you can hook into it and clear your varnish/memcache cache as needed, Ex:

```PHP
add_action( 'elementor/css-file/clear_cache', function(){
     wp_cache_flush();
});
```

**Comment by Dentalicious** [comment]
@bainternet  I gather from the response that i have to copy that code provided and paste it into my 'Astra' child theme 'functions' file (Image link - https://imgur.com/OuNoJth), and post update 2.0.8, the issue would get resolved automatically.
Kindly confirm, alternatively, If my understanding is mistaken, please elaborate your response.

@pdclark from Dreamhost had provided the code for ssh and it worked pretty well, 

This is what is the end result, from the terminal page.
….
[dp-545a030940]$ ssh user@dentalicious.com.au "cd dentalicious.com.au && wp cache flush && wp varnish purge"
user@dentalicious.com.au's password: 
Success: The cache was flushed.
Success: The Varnish cache was purged.
[dp-545a030940]$ 
…

Thanks.

**Comment by bainternet** [comment]
@Dentalicious 

The CLI flash command basically calls `wp_cache_flush();`
https://github.com/wp-cli/cache-command/blob/master/src/Cache_Command.php#L157

as for why it didn't work from a Child theme, I have no idea.

**Comment by seanosh** [comment]
The solution presented here is incomplete and should be incorporated into `elementor` directly. 

WordPress core itself uses `wp_cache_*` functions for adding/getting/deleting things like posts, postmeta, users, options, etc. An external cache store can be supported by adding a `WP_CONTENT_DIR . '/object-cache.php'` file with the required `wp_cache_*` functions. See `wp-includes/load.php`'s `wp_start_object_cache()` function for details. Some examples of external object cache store include [Memcache](https://wordpress.org/plugins/memcached/) or [Redis](https://wordpress.org/plugins/redis-cache/). 

Using WordPress core functions like `{get,update,delete}_post_meta` inherently use the `wp_cache_*` functions which are provided by the use of an external cache store via `object-cache.php`. 

One issue is within `clear_cache` function:

```
	public function clear_cache() {
		// Delete post meta.
		global $wpdb;

		$wpdb->delete(
			$wpdb->postmeta, [
				'meta_key' => Post_CSS::META_KEY,
			]
		);

		$wpdb->delete(
			$wpdb->options, [
				'option_name' => Global_CSS::META_KEY,
			]
		);

		delete_option( Frontend::META_KEY );

		// Delete files.
		$path = Base::get_base_uploads_dir() . Base::DEFAULT_FILES_DIR . '*';

		foreach ( glob( $path ) as $file_path ) {
			unlink( $file_path );
		}
```

Deleting from `wp_postmeta` where `meta_key = '_elementor_css'` (assuming defaults) doesn't then trigger the same `wp_cache_delete()` call(s) that WP core's `delete_post_meta` function does. 

At this point the data in the site's DB is different from what is in the site's external object cache. Continuing on from there, all of the generated files from Elementor are then deleted. Requests arrive to the site, the meta values are pulled from that external object cache, which the logic within Elementor uses to enqueue styles for a CSS file that no longer exists.

I believe this is at the core of what @pdclark and @Dentalicious were asking about/requesting. While Elementor plugin doesn't itself make direct use of `wp_cache_` functions, it does rely on or wrap WP core functions that do. By extension, Elementor should take care to invalidate that cache when it makes sense instead of requiring theme authors or site maintainers to add or execute `wp_cache_flush()` via WP CLI or the `elementor/core/files/clear_cache` hook. A lot of folks using the plugin might not be familiar with what this code is or what a hook is or where to add it.

**Comment by bainternet** [comment]
@seanosh 

Thanks for reporting, next time please open a new issue so we won't miss it.

We replaced the "direct" database calls (`$wpdb->...`) with the native `delete_post_meta_by_key` and `delete_option`.

should be out in next patch version.

**Comment by wpkc** [comment]
If you are like me and came here wondering why `add_action( 'elementor/css-file/clear_cache', function(){));` never gets called, here is the correct action name...

`add_action( 'elementor/core/files/clear_cache', function(){
   // Do stuff here!
} );`
