### ISSUE TITLE
New feature: Sprites Widget for Elementor Builder.

### ISSUE THREAD

**Issue by olairmarcos** [pojome/elementor#4183]
I want to suggest a new feature for Elementor Builder.

We need an element (widget) that the possibility of working with sprites. Sprites have already become a requirement to get good rank on pagespeed.

A widget that we can load an image in sprite form (an image composed of several smaller grouped images) and through fields we can enter the values for the height and width and the coordinates of the background so that the desired image appears.

This will greatly facilitate the use of sprite (smaller grouped images) with Elementor Builder, it will be a good tool for Elementor Builder.

Thank you for your attention, I await your feedback.

**Comment by redlagoon** [comment]
Sprites can be loaded just as easily.

Just simply "cut" then with your CSS.

I'd highly recommend using `svg` instead of sprites. People need to realize that 0.002ms won't affect your SEO and let's face it - most people in the WP business (customers that use themes) don't have a large enough business for them to matter.

In fact, this doesn't matter. At all.

So, use SVG for clean display / incredibly small file-size.

SEO is 90% how much you can pay for both Google and individuals to feature you, 5% content that actually matters, 4% luck and 1% speed of your site alongside [insert-completely-irrelevant-term-marketers-think-matters-to-sell-here].

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by garciacrew** [comment]
This would be a great feature.

**Comment by MarcelHeiniger** [comment]
+1 Yes it would be a great feature

**Comment by Dudaevskiy** [comment]
+1
