### ISSUE TITLE
Important suggestions

### ISSUE THREAD

**Issue by yeu** [pojome/elementor#4189]
Hello,

I state that I have already contacted the Elementor team to propose these improvements.

I'm a web developer and I tested all page builders "wp integrated" for a long time.

Your page builder is among the most complete and flexible, but it has some important limitations and can be absolutely the best if only you can make the following implementations:

1. Currently Divi has the best graphical interface, it's the fastest about insertion of the elements, no drag and drop, just a click and click. It's very fast, very useful, it's great!

2. Wp editor text: never neglect the power of being integrated into WordPress! It's very important to allow to use exactly the same original editor, because a lot of plugins add buttons and functionality into wp text editor. In other page builders I can open wp text editor with buttons of plugins.

3. Add a quick animation settings for each element. You can check this in King Composer, it's fantastic, it also have a preview effect! Please, take a look!

4. I think it's very important to allow inserting a row into a row. WPBakery builder allows to insert an inner row (with its columns) in a row and this is important for the layout structure.

I hope you'll consider my suggestions, they're only 4 steps. 

So... Good work! :)

**Comment by redlagoon** [comment]
1. Elementor is the same in terms of speed and Developers have the ability to allow controls to be "Popover". So, the same.

2. No, it's not. You have the WYSIWYG editor, so, same.

3. You can animate each element and you can also define your own animations.

4. You can do that. It's pretty basic for every builder.

Put aside the marketing bullshit (because, let's face it, every theme is the same, every builder is almost the same) and you only have 3 competing builders for 2018: Elementor / Divi / VC.

Elementor's extremely fast, open-source.

VC is damn slow.

Divi is closed, but you can expand on it from what I saw.

Due to me not being as knowledgeable in terms of what Divi can do:

It's all the same. Use whatever you want.

**Comment by bainternet** [comment]
Thanks for the suggestions
