### ISSUE TITLE
Feature Request: Dynamic content for Price Table widget

### ISSUE THREAD

**Issue by mgpub** [pojome/elementor#4242]
## Description
Really need the option to use dynamic content within the Price Table widget. I am using WooCommerce with the ACF plugin to add custom fields to products.

My products have variations so I have a lot of info that I would like to include in the Price Table widget - either directly from the Product Variation (like price) or from custom fields (like my custom Add to Cart links and Features).

Ideally, I want to be able to dynamically set the Pricing, the Features, and the Footer button link URL.

This would really take my WooCommerce store to the next level ;)

**Comment by bentalgad** [comment]
It's funny that you have for dynamic content in every field separately instead of just having the option to add dynamic fields any where just like in beaver builder which lets you add it even inside text and even multiple dynamic content's in one field. a lot of posts on how to do fancy effects but basic features are still missing from the beginning of this plugin.

**Comment by bradallenfisher** [comment]
anyway the price table could get dynamic "features" as well as the heading and title?
