### ISSUE TITLE
Related posts

### ISSUE THREAD

**Issue by themedleb** [pojome/elementor#4349]
Now since Elementor became a theme builder so we need related posts made by Elementor to build our theme with it so everything will be consistent.

We know there are several plugins to do that, but not like the features and styles that Elementor Pro offers, the site will look inconsistent and unprofessional when posts from archive pages and other pages will look very different from related posts in terms of style and features (like custom fields ...).

**Comment by DrMohamedGamal** [comment]
Yes Completely agree +1

**Comment by black-eye** [comment]
+1

**Comment by klarakalko** [comment]
+1.

**Comment by Hanleymade** [comment]
Good idea + 1

**Comment by popsantiago** [comment]
Cool +1

**Comment by Ver3** [comment]
+1

**Comment by JoeDarko** [comment]
+1

**Comment by ZedProg** [comment]
+1

**Comment by bainternet** [comment]
Should be easy to implement with Elementor Pro 2.1 custom query filters:

https://developers.elementor.com/custom-query-filter/#Related_Posts_by_Tags_in_Posts_Widget

**Comment by yoavshai** [comment]
@bainternet hi, didn't really understand why this feature request is closed. Maybe I'm missing something, but I don't think there is a way to chose dynamc tags/categories via the them builder

**Comment by kdawg1406** [comment]
@yoavshai please see the issue I opened here [https://github.com/elementor/elementor/issues/7790](https://github.com/elementor/elementor/issues/7790).

I provided a video so that the developers can understand our requirements for rendering related data in our front ends. 

The video also explains in detail my current solution and the workaround for the lack of support for Pods related data.
