### ISSUE TITLE
Use the User Language instead of Site Language

### ISSUE THREAD

**Issue by theDevelopersRO** [pojome/elementor#4529]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
For the Romanian language, I noticed that some of the words/strings are bigger than the English version and they are bigger than the button or the place which they are in. 

**Describe the solution you'd like**
Elementor should use the same language as the user language which was defined in Settings

**Describe alternatives you've considered**
Another way to deactivate specific language or test Elementor in any language and fix this problem.

**Additional context**
-

**Comment by bainternet** [comment]
Currently, this feature is not supported, and it's not as simple as you state because it's a frontal editor and it needs to know the language and the properties of that language( ex LTR/RTL).

If you would like to alter the translations, then please feel free to contribute:
https://docs.elementor.com/article/42-translate
https://www.facebook.com/groups/elementortranslators/

Thanks for the feedback.

duplicate #3623, #3700
