### ISSUE TITLE
Custom webhook handler does not continue with other actions

### ISSUE THREAD

**Issue by joeczucha** [pojome/elementor#4534]
I'm trying to connect a form to Pardot. I've follows advice in a  [similar thread](https://github.com/pojome/elementor/issues/3847) and created a custom webhook handler. 

    <?php

    function submit_form_to_pardot($record, $handler) 
    {
      $form_name = $record->get_form_settings('form_name');

      if ('Demo' !== $form_name ) {
        return;
      }

      $raw_fields = $record->get('fields');

      $fields = [];
      
      foreach ( $raw_fields as $id => $field ) {
        $fields[ $id ] = $field['value'];
      }
      
      $endpoint = 'https://go.pardot.com/l/000000/2017-06-22/xxxxxx';

      $response = wp_remote_post($endpoint, array(
        'body' => $fields
      ));
    }

    add_action('elementor_pro/forms/new_record', 'submit_form_to_pardot');

This working fine, my record is created in Pardot and the server returns a 200 code. However, the form just displays a red X (no text)

![image](https://user-images.githubusercontent.com/2218980/40438264-8cd30fca-5eaf-11e8-87b5-3c44065efb18.png)

and doesn't continue with the next action, which is to redirect to the thank you page. 

In my browser, the XHR request shows `{"success":false,"data":{"message":"","errors":[],"data":[]}}` so I'm assuming that Elementor is interpreting the success: false as a failure and exiting before the next action can be called.

Is this is a bug or do I need to do something to tell Elementor that the AJAX call was successful?

Thanks :)

**Comment by bainternet** [comment]
Seems fine. But we can't tell for sure without debugging,

Please contact our support at support @elementor.com for guidance in resolving this issue.

**Comment by joeczucha** [comment]
For future visitors, it was because I was specifying the redirect URL as `/thank-you/` rather than `http://www.xxx.com/thank-you`.

**Comment by icoso99** [comment]
I apologize, However, I  am VERY new to this and using Elementor.  I am assuming that this code is to be added to the webhook.php file, right or no?  IF no, then where is this php code to be added?

Also I found this page for Webhooks on Forms? https://docs.elementor.com/article/281-form-faq   Which explains that "To control the field names, give your form fields a custom ID and use the following snippet. Be sure to update the form name and your webhook URL."  Which we have done.  I added the exact code from that page to the webhook.php file as follows:


add_action( 'elementor_pro/forms/new_record', function( $record, $handler ) {

//make sure its our form
	$form_name = $record->get_form_settings( 'form_name' );
	if ( 'loanform' !== $form_name ) {
		return;
	}
	
	$raw_fields = $record->get( 'fields' );
	$fields = [];
	foreach ( $raw_fields as $id => $field ) {
		$fields[ $id ] = $field['value'];
	}

	wp_remote_post( 'HTTP://myurl.org/wp/loan-calc-form', [
		'body' => $fields,
	]);
});

Then in my Elementor pro  form for the webhook URL I put: HTTP://myurl.org/wp/loan-calc-form
This loan-calcform is the same page that contains this form.   I'm trying to send the data to the page itself.  so the calculator that I built using PHP will populate the form.  You can find an example of what I m try to accomplish here: http://icoso.com/loancalc/calcphp.php.  This is a BASIC webpage.  this is not an elementor page.  But on this page my <form> tag looks like:
<form METHOD="POST" ACTION="<?php echo $PHP_SELF ?>" name="loanform" id="loanform">
and my calculate button is a simple submit button:
<input type="submit" value="Calculate" id="calcLn" name="calcLn">
My Php Code test for if 'calcLn' then does the calculation with the submitted code and runs a javascript that populates the readonly fields at the bottom of this page.  

On the Elementor pro page I've created the form, however using the code inspector the FORM tag does not appear to have any type of ACTION tag, how do we add this to a form?  I figured I'd use the Webhook and send the date to the form itself that way, ie: HTTP://myurl.org/wp/loan-calc-form,  I dont appear to get anything submitted to the form I created in Elementor Pro.   I'm using PHP Everywhere to pull in my background PHP via a Shortcode that is put into a HTML field that is loaded above my FORM.  I know this is running, because I added a series of PHP echo's to display info on the page to see how far I got.  I've put two type of button on my calc form,  an HTML button that uses <input type="submit" value="Calculate" id="calcLn" name="calcLn"> and the Elementor Submit button.  I've tested with both buttons to submit the data. at the bottom of the form page the words "The form was sent sucessfully" gets added to the page. 

I also found this:  https://developers.elementor.com/forms-api/
On this forms API it talks about this: 
Form Submission Action
elementor_pro/forms/form_submitted
After the forms module is loaded and it’s a POST request with the form action. This is the place to add a form handlers.

And it gives code examples.  Where does this code go? Where do I add or edit this code?

Basically, I'm trying to create an Elementor Pro form on my Wordpress site, that acts like my basic calculator at http://icoso.com/loancalc/

Any suggestions would be greatly appreciated.

**Comment by johnnyfish** [comment]
@joeczucha can you explain please? 
dealing with the same issue imo

**Comment by joeczucha** [comment]
@johnnyfish Thats pretty much it, sir. As well as the Pardot and email actions set on the form, I’d also set up a redirect to the thank you page. However, I’d set a relative URL rather than a full one, hence the red X.

Should be a simple enough fix, if it is indeed the same issue...

**Comment by johnnyfish** [comment]
Thanks for the quick response, I am guessing that is not the same exact issue.. 
But I am also getting the red X 
using the same form + webhook to pass the data of the form to my server.. 
will open a case I guess to try to find what is it in my side

**Comment by collejack** [comment]
Hi @johnnyfish 
Were you able to get an answer about the red X for sending the webhook? I have the same problem with the Elementor form.
