### ISSUE TITLE
Dynamic Content: Support Multiple Featured Images

### ISSUE THREAD

**Issue by jessmason** [pojome/elementor#4604]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
I want to create page templates with multiple images, dynamically sourced from the page itself. 

**Describe the solution you'd like**
I use a plugin to allow me to add multiple featured images, and I'd like to be able to select featured image 1, 2, or 3 (etc) for a template dynamically.

**Describe alternatives you've considered**
I don't know of any.

**Additional context**

**Comment by bainternet** [comment]
@jessmason 

how do you see that working? what is the plugin we are talking about?

**Comment by jessmason** [comment]
I'm using this plugin: https://cl.ly/s1eM

And I simply see "Featured Image 2", "Featured Image 3", etc; listed under the current "Featured Image" choice in the dynamic menu: https://cl.ly/s1jE

**Comment by bainternet** [comment]
@jessmason 

thanks for clarifying
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.,

**Comment by wywebsite** [comment]
**This is an amazing idea !!!**, I'm looking for the exactly the same feature, I tried the "Dynamic Featured Image" plugin, actually I insert a shorcode in the front pages, but this solve some of my needs, I'm looking the way to make a portfolio index, for display a few featured images for each project, like mini sliders, because the project involve 2 or more important and inseparable pictures, right know I'm displaying separate images in the index, but this is not the right way to show the project, because at side of this pictures you'll see another totally different projects. and all stay mixed in a confusing way. I'm not an expert in php, but I know that this can be done. I'll still looking for a solution or someone who knows to create a plugin to add this feature to elementor.

**Comment by joebak** [comment]
i am looking for this featured as well! please add this for us... thanks!

**Comment by BasilDimopoulos** [comment]
+1

**Comment by senator94** [comment]
I have a client that would like multiple featured images rotating or a featured mini video that is triggered when hovered. Similar to PornHub.

**Comment by luukee** [comment]
+1

**Comment by robsoncarvalho** [comment]
+1 please... I'm just looking for a solution to the same problem, and just realized this is from 2018 :'(
