### ISSUE TITLE
Cannot select Canvas template when editing Section Template

### ISSUE THREAD

**Issue by diggeddy** [pojome/elementor#4669]
The General Settings > Page Layout options are missing when editing a Section Template. Cannot change Layout from Default template to Canvas. Preferably Section Templates should default to the Canvas template.

**Comment by bainternet** [comment]
@diggeddy 

Its not there by design, not missing.

Simply because a section is not a page/post and canot hold a template.

there are a few workaround like [registering a theme location](https://developers.elementor.com/theme-locations-api/) and seting the location to open the section edit area.

thanks for the feedback.

**Comment by diggeddy** [comment]
Unless i am mistaken, it used to be possible to select Canvas for the purpose of editing Section templates. It makes a poor UX for designing full width section templates.

**Comment by pingram3541** [comment]
@bainternet Raz is misinterpreting the request.  It has nothing to do with how the "section" template is rendered on the front end and storing a "template type" to be used and has everything to do with the template that is used when editing an Elementor said library item.  Some items allow this control like Elementor templates saved as whole pages vs sections.

I missed this one when checking to see if an issue was already open - see https://github.com/pojome/elementor/issues/4819

My only work around is to import the section template into a page using canvas, modify it, delete the original template and save a new one.  If this template is used dynamically elsewhere it could still entail a lot of effort to go back and update these areas with the new template.

**Comment by fippy** [comment]
If it helps anyone, I have a workaround using the following Code Snippet which creates a conditional

```
function is_section_template() {
  if ( get_post_meta( get_the_ID(), '_elementor_template_type', true ) == 'section' ) {
    return true;
  } else {
    return false;
  }
}
```
 which I then use in Simple Custom CSS and JS PRO to hide the unnecessary elements via css:

```
.elementor-location-header,
.elementor-location-footer,
.page-header,
.otgs-development-site-front-end { 
	display: none; 
}
```

by applying the css only when the Conditional Tag is_section_template() returns true.

Would still love to see this properley implemented by Elementor, because there are tons of use cases where one would want to edit a section template WITHOUT the default page template!
