### ISSUE TITLE
Domains for local development require license activation

### ISSUE THREAD

**Issue by srcek** [pojome/elementor#4675]
It's just a minor annoyance that Elementor Pro requires license activation for domains intended for local development. I use Laragon which defaults to .test domain. So my local testing sites look like example1.test, example2.test, example3.test etc... Every time I create a local site I have to activate my license. That's unnecessary since that domain can't be used as top level domain, only for development.
More info here: https://en.wikipedia.org/wiki/.test

It's not an issue for me since I have unlimited license but I thought this could be useful to bring to your attention. Also, I like to have a clear overview of active sites on which I used my license on and entries with .test domain make the list (my.elementor.com) a bit crowded.

**Comment by bainternet** [comment]
@srcek 

From now on, we don't count `.test` domains.

thanks.

**Comment by boutzamat** [comment]
I'm running on Pantheon.io who is providing 3 enviroments (dev, test and live).
I have a pro license. Is there any way that i can not spend 3 installations on 1 site with multiple enviroments?
This was not a problem back when a license ment unlimited installations. But i don't want to use 3 licenses per customer.

Sorry for commenting on a closed thread. Just didn't think it was worth opening a new one for, since the topic is pretty much the same.

**Comment by marwann** [comment]
I have a similar problem, using WAMP for local development. Elementor does not consider it as localhost because WAMP asks to create Virtual Hosts for each local project.
