### ISSUE TITLE
Forcing open item to close when clicking on other toggle item - Elementor toggle widget

### ISSUE THREAD

**Issue by darrinnc** [pojome/elementor#4706]
Trying to get the Elementor toggle widget to behave like the accordion widget where the previous open item will close when opening another toggle item.

With the toggle widget, any open toggles remain open when clicking on different toggle item.  A tick box to enable/disable this would be great for this widget.

**Comment by bainternet** [comment]
@darrinnc 

why not use accordion?

**Comment by JohnMulderFrance** [comment]
Because the accordion always has the first item opened. That is not always what you want.
There is a plugin that disables the accordion from doing that. (https://wordpress.org/plugins/granular-controls-for-elementor/) But it would be easier and more straightforward if this could be set within Elementor itself, not needing a plugin to do that.

**Comment by bainternet** [comment]
I merged this issue with  #2756, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by Matthieu11** [comment]
Hello, did any answers for that problem was said ? 
I looked to the issue linked but  didn't find any solution.
thx
