### ISSUE TITLE
Why is design broken after changes until I clear cache?

### ISSUE THREAD

**Issue by get8bit** [pojome/elementor#4755]
So, this has been bugging me for a while. 

Let's say I have a nice design. I go in and add one new section. When I check the live site, everything has reverted back to light blue default text and light green buttons. Formatting and layout are totally out of whack. Now, if I clear my cache, everything looks fine. 

However, what about repeat visitors? They are seeing the broken site as well unless they clear their cache too. Why would a visitor have to clear their cache every time they visit a site? They don't know I made changes. All they see is a broken design. See image of what I mean here: https://imgur.com/a/WNw6ToA

This is probably the only thing I don't like about Elementor. Well, that and the page refreshes in place instead of the top like other sites, but that is a separate issue.

**Comment by bainternet** [comment]
@get8bit 

This behavior is due to your caching mechanism, Elementor can't and is not responsible of clearing your cache and what happens is that the CSS file is deleted once you change something but you cache is blocking it from recreating the new CSS file.


You can, however, hook into the save action and clear your cache then which will force a recreating of the CSS.

thanks
