### ISSUE TITLE
Call to Action widget = Dynamic Content.

### ISSUE THREAD

**Issue by eachlife** [pojome/elementor#4767]
## Prerequisites

- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
This would add an incredible way to display posts, much similar to plugins like The Grid or Essential Grid. It would get users attracted to view the post in a very dynamic way! 

**Describe the solution you'd like**
Dynamic content like other widgets that already have this. 

**Describe alternatives you've considered**
None. I imagine it would be a simple implementation, to add the dynamic meta to the content elements in the Call to Action widget. THANK YOU.

**Additional context**

**Comment by black-eye** [comment]
+1

**Comment by srcek** [comment]
+1

**Comment by NTuneMusic** [comment]
+1

**Comment by wmassjct** [comment]
+1 would also like to see this for accordion, toggle, etc

**Comment by eachlife** [comment]
@wmassjct Yes! It makes sense to have in every content widget. Imagine all the possibilities.

**Comment by wmassjct** [comment]
I have asked about this before and never gotten a response.  Maybe you posting it here will be more productive.  One of the paid plugins has an option for call to action style posts but I forget which one.  I seem to remember there was a reason other than price that I didn't pay for it.  As a work around I've been using AE Pro Post Block templates.  I created a template that is just a formatted AE Post Content widget and then I insert the shortcode into the content of the accordion.  It's a few extra steps but has been working so far.  When you're making the template make sure to preview it using a post or else the widget will be empty.

**Comment by Jaska** [comment]
+1

Call to Action is a great widget but man how boring it is to copy paste content, links and images by hand from posts which already has them.

Recent example here: https://tanssittamo.fi/palvelut/tanssipalvelut/
If only I just could have pointed the page to the widget and it would dynamically link to the posts content.

**Comment by john298612** [comment]
+1

**Comment by stephan1996** [comment]
## Prerequisites


- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )


**What problem is your feature request going to solve? Please describe.**
I am using the CTA to display my posts in an overview, using a loop. 
The problem is, I can not mark certain posts with a ribbon. 

**Describe the solution you'd like**
To solve this it would be nice to see the availability to add dynamic content into the ribbon.
No content = no ribbon
Content = show ribbon on the CTA

**Describe alternatives you've considered**
No alternatives known. Would like to stick to the main widgets from elementor pro.

**Additional context**
![CTA Feature request](https://user-images.githubusercontent.com/20606281/73567499-c6bf4c00-4466-11ea-982c-a50e974156bd.png)
