### ISSUE TITLE
Bug - Editing Elementor Library item cannot choose page template

### ISSUE THREAD

**Issue by pingram3541** [pojome/elementor#4819]
## Prerequisites

- [ x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x ] The issue still exists against the latest stable version of Elementor.

## Description

When editing an `elementor library item` it opens using the theme's default "post" template which is often not full width, has a sidebar and includes the header, footer and other post meta not desired to be seen in the editor.  The space to work within in the Twenty Seventeen theme is less than 600px!

![screen shot 2018-06-20 at 10 54 05 am](https://user-images.githubusercontent.com/319284/41675786-7d170e54-7478-11e8-9ec1-237f63b1e56a.png)

It makes editing very difficult without taking additional measures.  It would be preferable to be able to set the post type `elementor_library` to use a specific template, for example `Elementor Canvas` or `Elementor Full Width` but there is no where to do this.  It's as if the `elementor_library` post type itself has been excluded from the Display Conditions altogether.

Additionally the ability to define Display Conditions by post_type is also missing, you can only filter by Post Name, Category, Tag or In Format which is too restricitive.  Very frustrating indeed.

![screen shot 2018-06-20 at 10 54 55 am](https://user-images.githubusercontent.com/319284/41675887-ccaf4ddc-7478-11e8-9903-32d48bff6291.png)

Even when creating a new Single template with only a single empty full-width section and the `wp_content widget` AND setting that template to use `Elementor Canvas` and then applying the Display Conditions to All Posts with the setting ALL still doesn't apply it to `elementor_library` items, even when choosing the preview option `POST - ALL` it refreshes and uses the theme's post template anyway.

Library items that are not `Single` and `Archive` Elementor template types should never be loaded in the editor using the theme's post templates and should always be a full 100% canvas area to work with.

![screen shot 2018-06-20 at 10 54 31 am](https://user-images.githubusercontent.com/319284/41675967-082c344c-7479-11e8-8561-9222de9105d8.png)

## Steps to reproduce

1) Fresh wp install w/ twenty seventeen theme any only Elementor + Elementor Pro
2) Create a new template, notice less than a 600px area to edit it
3) Try to change page template type, it's no where to be found

## Isolating the problem

- [ x ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [ x ] This bug happens with a default WordPress theme active.
- [ x ] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
Applies to all systems
```
</details>

**Comment by bainternet** [comment]
@pingram3541 

This is not a bug but a feature by design.

If the theme you are using has registered locations then you could select the location as a place to open the editor. If not then the only default single template is where can open the editor.

Without it, you are basically saying something like: "I want to set a template for a template"...

here is the documentation for registering a location: https://developers.elementor.com/theme-locations-api/registering-locations/


As for why you can not set `elementor_library` in the conditions is because of the way they work which is one level above/before the conditions.

thanks for the feedback.

**Comment by pingram3541** [comment]
@bainternet Raz, sorry but I disagree wholeheartedly. This is very poor design control when one can only define what template pages and posts use but not library elements.  It defeats the whole purpose of having a full canvas to work with when editing a library item and this should be **theme agnostic**.

Other library items like "page" templates allow this, I just want to be able to do this for "section" templates too...having nothing to do with how they are rendered when actually used, but only how they are rendered when editing them.

> If not then the only default single template is where can open the editor.

This statement is true, but also the entirety of the problem because one cannot (within Elementor) define the `elementor_library` post type to use a specific template like `Elementor Canvas`, `Elementor Full-Width` or `Elementor Page/Post dynamic template using Display Conditions`.

> Without it, you are basically saying something like: "I want to set a template for a template"...

Yes indeed I am and this already works with other post types, just not `elementor_library` and the class is protected so it is impossible for us to fix without hacking code!!!.  I want to be able to define that all `elementor_library` post types USE the `Elementor Canvas` template so I have a full work space to work within.  How can I do this without hacking the theme or the Elementor plugin?

The correction to what I'm basically saying is "I want to set a template for a post type of `elementor_library`, specifically for when I'm editing a library item" - that is all.

I really feel I should make a big stink about this one.  Gonna bring it up elsewhere and get some feedback, if anything instead of closing this out as "NOT A BUG", how about suggesting it as a FEATURE instead?

**Comment by brucetm** [comment]
@pingram3541 is right, and this should not be closed.  If I save a section as a template, then go back to edit it, it should be rendered on a blank canvas, not in the content area of a themed page, which is in many cases not the intended context for the template, and so not easily readable or edited.  

Simplest example: a theme with white content area and dark header and footer, saving a template for use in header and footer will have white text, and will be invisible when rendered in the content area of a page.  I don't think this is "by design."

**Comment by fippy** [comment]
@pingram3541 is definitely correct. This is terrible design. When you are editing a section template, there are so many uses cases where you do not want to see the default header and footer. Anywhere this should be something we the customer of Elementor Pro can control. 

Also highlighted here: https://github.com/elementor/elementor/issues/18896

**Comment by fippy** [comment]
If it helps anyone, I have a workaround using the following Code Snippet which creates a conditional

```
function is_section_template() {
  if ( get_post_meta( get_the_ID(), '_elementor_template_type', true ) == 'section' ) {
    return true;
  } else {
    return false;
  }
}
```
 which I then use in Simple Custom CSS and JS PRO to hide the unnecessary elements via css:

```
.elementor-location-header,
.elementor-location-footer,
.page-header,
.otgs-development-site-front-end { 
	display: none; 
}
```

by applying the css only when the Conditional Tag is_section_template() returns true.

Would still love to see this properley implemented by Elementor, because there are tons of use cases where one would want to edit a section template WITHOUT the default page template!

**Comment by pingram3541** [comment]
I gave it a good go today, an illusive one at that seeing if I could go AROUND the problem.

First, I enabled the Landing Pages post type in Elementor Settings.

Next I opened an Elementor Section Template in the Theme Editor, where it initially loads with the undesired theme header & footer.

I then chose under Preview Settings to Preview Dynamic Content as a Landing Page expecting it to render with the Canvas template but nope, just refreshed with the header and footer again, no difference.

For the time being, your work around gets the job done, thank you @fippy .
