### ISSUE TITLE
Feature Request: Add New Section > Add Layout > "Grid Layout"

### ISSUE THREAD

**Issue by kubik101** [pojome/elementor#4928]
I am new to Elementor and found a need to make a grid for certain layouts, similar to Foundations Block Grid.
Something that can not be achieved with columns.

Within Grid you could have the following settings:
- Number of Columns (Definable for Desktop, Tablet and Mobile)
- Equal height
- CSS Class
- CSS ID
- Ability to duplicate cells with already entered content so that you can easily duplicate complex cell content layouts
- Ability to save it for re use globally or otherwise

Then you could populate each grid cell with your desired content.

**Comment by bainternet** [comment]
@kubik101 
Thanks for reporting,
Please follow guidelines for opening a new feature request, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Description and examples.

As for your requests,
* CSS Class - you can in the column advanced tab.
* CSS ID - you can in the column advanced tab.
* Ability to duplicate cells with already entered content so that you can easily duplicate complex cell content layouts - since v2.1 you can simply copy & paste columns content.
* Ability to save it for re use globally or otherwise - possible with global widgets in Elementor Pro.

so for these:

- Number of Columns (Definable for Desktop, Tablet and Mobile)
- Equal height

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.
