### ISSUE TITLE
How can I stop submit with Elementor Forms API?

### ISSUE THREAD

**Issue by odedta** [pojome/elementor#5006]
Is there a jQuery way to stop the submit of a form?

Is there a way to use the new_record action with validation action so that if the form doesn't validate, then new_record action wouldn't fire?
What is the best way to approach this?

Thanks

**Comment by bainternet** [comment]
@odedta 

You can return an error in the ajax handler and it will stop the form submission ex:

```PHP
add_action( 'elementor_pro/forms/validation', function ( $record, $ajax_handler ) {
	// Do you validation
	// set an error to the ajax handler to stop the form submission
	$ajax_handler->add_error( 'field_id', 'error message' );
}, 10, 2 );
```

you can also set the hook to a specific field type only, ex:

```PHP
add_action( 'elementor_pro/forms/validation/select', function ( $field, $record, $ajax_handler ) {
	// Do you validation
	// set an error to the ajax handler to stop the form submission
	$ajax_handler->add_error( $field['id'], 'error message' );
}, 10, 3 );
```

**Comment by eyal670** [comment]
Hi
I was looking just that, and it's working but only with 
`$ajax_handler->add_error( 'field_id', 'error message' );`

when trying to use 
`$ajax_handler->add_error_message('general error msg' );`
for showing the massage as general massage and related specifically to one field
it shows the error message instead of the success message  but not stopping the submit action and the actions after submit
I also tried to add 
`$ajax_handler->is_success = false;`
but still, the submit actions took place

a workaround for me was to add both and just hide the field specific msg
```
$ajax_handler->add_error( 'field_id', '<div class="dummy-error" style="display:none">error message</div>' );
$ajax_handler->add_error_message('general error msg' );
$ajax_handler->is_success = false;
```
but I see no resone why the two bottom lines will not stop the form from submiting
any idea how to achieve it without the first line and the need to hide it with css?

**Comment by odedta** [comment]
Which hook are you using?

You could use `validation` hook in order to validate fields, if that doesn't work the form will not submit.

**Comment by eyal670** [comment]
hi,
I'm using the hook "elementor_pro/forms/validation"
as I said, it's work for 
`$ajax_handler->add_error( 'field_id', 'error message' );`
but keep submiting when using only
`$ajax_handler->add_error_message('general error msg' );`
or
```
$ajax_handler->add_error_message('general error msg' );
$ajax_handler->is_success = false;
```

**Comment by eyal670** [comment]
I'm not sure if I need to open a new issue or not,
it is related to this issue but with a twist

**Comment by odedta** [comment]
It's a good question, let's tag @bainternet and hope for a reply.

**Comment by bainternet** [comment]
Please open a new issue and paste your code in it.
