### ISSUE TITLE
Frequent changes in names of actions and classes

### ISSUE THREAD

**Issue by VadymPogorelov** [pojome/elementor#5096]
Hello guys, 
It's become a tradition already, that with each new update, names of actions are changing (for example, instead of 'elementor/frontend/**element**/before_render', 'elementor/frontend/**section**/before_render' is used). So are the css-classes of many items in the editor (for example, '.elementor-panel-category-title' instead of '.panel-elements-category-title' is used). 

This is a huge inconvenience for the developers who use your API and make improvements or additions to Elementor, since after such updates some parts of their code just stop working! And instead of proceeding with their new projects, they have to constantly release updates for the previously created themes. That would be awesome if you guys cared not only about the beauty of your own code, but also about those who work with it, and kept backwards compatibility when making changes! 

We really like your product, however the issues we've described above are really getting in the way, and we become more and more demotivated using it.

**Comment by atashinbar** [comment]
Yes, I have same problem. You said these actions "elementor/frontend/section/before_render" and "elementor/frontend/section/after_render" work in "Editor" and "Frontend" mode. But they work just in frontend.
Please check it again.

**Comment by VadymPogorelov** [comment]
It's just an example )) And there are many such examples! And I did not write that this action is used in the Editor. I wrote that in the Editor often change the names of css-classes.

**Comment by atashinbar** [comment]
:)) Aha. Ok thank you for your description.

**Comment by bainternet** [comment]
@VadymPogorelov 

Thanks for the feedback.

We try not to change the names of classes in the widgets markup and same goes for actions in our API.

Specifically speaking about the `elementor/frontend/element/before_render` | `elementor/frontend/section/before_render` this was a correction of a long time bug that `element` was a string instead of a variable `{$element}` like it should have been.

As for methods in our API we never just "Change/remove" anything without at least a 4 major versions phase of soft depreciation with notices.

As for classes of elements in the panel which are **not a part of the API** in any way, we will change some of them from time to time as we are always updating the panel.

All of our development cycles are publicly aviable here on Github which you are more than welcome to follow.

Now, after that been said, we may miss a change every once in a while (we are humans) , So please feel free to call us up on it.

thanks.
