### ISSUE TITLE
Google Maps

### ISSUE THREAD

**Issue by liberodark** [pojome/elementor#5119]
Hi,

Have google maps code not work on elementor !
And add html code in this put my iframe from google : 

`<iframe src="https://www.google.com/maps/d/embed?mid=1z-4xcKNdrYQhxuj10zW9bA5KqC2EymhN" width="640" height="480"></iframe>`

Is not possible to save my work have this error : 
Erreur serveur (403 Forbidden)

https://i.imgur.com/Qa28CS7.png

Have elementor pro and is updated

**Comment by bainternet** [comment]
@liberodark 

Thanks for reporting,
Please follow guidelines for opening a new issue report, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

As for the issue here, 403 is a server response that means you were blocked from saving, either by a firewall, server configuration ( apache modsecurity ) or a 3rd party plugin for having an Iframe in your content.
 if its none of the above, Please contact our support at support @elementor.com for guidance in resolving this issue.

**Comment by liberodark** [comment]
Have send email...

**Comment by Wyndoos** [comment]
Has anyone found a solution?

**Comment by Wyndoos** [comment]
Have any one found a solution to adding maps code on elementor?

Looking to add in frame code from snazzy maps, * tried more that one widget "SiteOrigin Google Maps" and the "HTML" widget, both resulting in a 403 server error upon updating? 

<iframe src="https://snazzymaps.com/embed/401376" width="100%" height="600px" style="border:none;"></iframe>
