### ISSUE TITLE
Elementor not reading database changes

### ISSUE THREAD

**Issue by expphoto** [pojome/elementor#5179]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest stable version of Elementor.

## Description

I had a bunch of pages created with incorrect URLs since source codes were moved over to the posts. I would need to change the urls from the relative to absolute. IE: /SiteAssets to https://www.example.com/SiteAssets.

This only effects a specific section of the site.

I've already changed ALL database entries, cleared caches, and Elementor still isn't picking up the changes. There are around 2k of them, so manually changing isn't feasible. 

To note, I reached out to Support, and they pointed me to Dev on this.

## Steps to reproduce

Enter in an incorrect hyperlink in a text box
Change the entry in the DB
Elementor still doesn't update the link

## Isolating the problem

- [X] This bug happens with only Elementor plugin active (and Elementor Pro).
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
					
== Server Environment ==
	Operating System: Linux
	Software: Apache/2.4.29 (Unix) mod_hive/6.6 OpenSSL/1.0.1e-fips mod_fastcgi/2.4.6
	MySQL version: 5.6.36
	PHP Version: 5.6.36
	PHP Max Input Vars: 1000
	PHP Max Post Size: 32M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.7
	Site URL: 
	Home URL: 
	WP Multisite: No
	Max Upload Size: 24 MB
	Memory limit: 40M
	Permalink Structure: /%category%/%postname%/
	Language: en-US
	Timezone: 0
	Debug Mode: Inactive

== Theme ==
	Name: Astra
	Version: 1.3.3
	Author: Brainstorm Force
	Child Theme: No

== User ==
	Role: administrator
	WP Profile lang: en_US
	User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

== Active Plugins ==
	Active Directory Integration for Intranet sites
		Version: 2.8.2
		Author: miniorange

	Broken Link Checker
		Version: 1.11.5
		Author: Janis Elsts, Vladimir Prelovac

	Elementor
		Version: 2.1.4
		Author: Elementor.com

	Freshchat
		Version: 2.2.1
		Author: Freshchat

	Hustle
		Version: 6.0.3
		Author: WPMU DEV

	Jetpack by WordPress.com
		Version: 6.3.2
		Author: Automattic

	ManageWP - Worker
		Version: 4.5.0
		Author: ManageWP

	Media Deduper
		Version: 1.4.2
		Author: Cornershop Creative

	reSmush.it Image Optimizer
		Version: 0.1.15
		Author: reSmush.it

	Restrict User Access
		Version: 1.0.1
		Author: Joachim Jensen

	Search & Replace
		Version: 3.1.2
		Author: Inpsyde GmbH

	Shortcodes Ultimate
		Version: 5.0.4
		Author: Vladimir Anokhin

	Simple 301 Redirects
		Version: 1.07
		Author: Scott Nellé

	Simple Custom CSS and JS
		Version: 3.18
		Author: SilkyPress.com

	Smush
		Version: 2.7.9.1
		Author: WPMU DEV

	Stripe Payments
		Version: 1.9.2
		Author: Tips and Tricks HQ, wptipsntricks

	Theme My Login
		Version: 7.0.9
		Author: Theme My Login

	UpdraftPlus - Backup/Restore
		Version: 1.14.12
		Author: UpdraftPlus.Com, DavidAnderson

	Velvet Blues Update URLs
		Version: 3.2.8
		Author: VelvetBlues.com

	Webcraftic Clearfy – WordPress optimization plugin
		Version: 1.2.1
		Author: Webcraftic <wordpress.webraftic@gmail.com>

	When Last Login
		Version: 1.1
		Author: Yoohoo Plugins

	Wicked Folders
		Version: 2.9.1
		Author: Wicked Plugins

	WordPress Importer
		Version: 0.6.4
		Author: wordpressdotorg

	WP File Manager
		Version: 2.8
		Author: mndpsingh287

	WP Mailgun SMTP
		Version: 1.0.5
		Author: InkThemes

	WP Post Page Clone
		Version: 1.0
		Author: Gaurang Sondagar

	WP Security Audit Log
		Version: 3.2.2.1
		Author: WP White Security

== Must-Use Plugins ==
	ManageWP - Worker Loader
		Version: 
		Author: ManageWP

== Debug ==
	Errors: 
		TypeError: Cannot read property 'errors' of undefined
			at https://example.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.1.1 - 2:138433
			2018-07-06 20:19 +00:00
			x 28 times

		TypeError: Cannot read property 'on' of null
			at https://example.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.16 - 2:82365
			2018-06-18 21:12 +00:00

		TypeError: Cannot read property 'style' of undefined
			at https://example.com/wp-admin/js/editor.min.js?ver=4.9.6 - 1:694
			2018-06-18 21:12 +00:00

		TypeError: Cannot read property 'on' of null
			at https://example.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.16 - 2:82365
			2018-06-18 21:10 +00:00

		TypeError: Cannot read property 'style' of undefined
			at https://example.com/wp-admin/js/editor.min.js?ver=4.9.6 - 1:694
			2018-06-18 21:10 +00:00

		TypeError: Cannot read property 'on' of null
			at https://example.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.16 - 2:82365
			2018-06-18 21:00 +00:00

		TypeError: Cannot read property 'style' of undefined
			at https://example.com/wp-admin/js/editor.min.js?ver=4.9.6 - 1:694
			2018-06-18 21:00 +00:00

		TypeError: Cannot read property 'on' of null
			at https://example.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.16 - 2:82365
			2018-06-18 21:00 +00:00

		TypeError: Cannot read property 'style' of undefined
			at https://example.com/wp-admin/js/editor.min.js?ver=4.9.6 - 1:694
			2018-06-18 21:00 +00:00

		TypeError: Cannot read property 'on' of null
			at https://example.com/wp-content/plugins/elementor/assets/js/editor.min.js?ver=2.0.16 - 2:82365
			2018-06-18 20:59 +00:00
</details>

**Comment by bainternet** [comment]
@expphoto 

Elementor stores its data in the database, so if it was changed in the database it should change in Elementor. 

Now, currently, Elementor works with full URLs and not relative so I'm not sure how you got the relative URL's there in the first place.

Now if it was full URL's I would tell you to use the change URL toll but I understand it is not. 

The only way I can think of for you is to use our "Replace-URL" tool query to run the replacement.

### BEFORE YOU DO THIS MAKE SURE YOU HAVE A BACKUP AND THAT YOU ACTUALLY KNOW WHAT YOU ARE DOING 

```PHP
global $wpdb;
$from = 'SEARCH';
$to = 'REPLACEMENT';
$rows_affected = $wpdb->query( "
	UPDATE {$wpdb->postmeta} " .
	"SET `meta_value` = REPLACE(`meta_value`, '" . str_replace( '/', '\\\/', $from ) . "', '" . str_replace( '/', '\\\/', $to ) . "') " .
	"WHERE `meta_key` = '_elementor_data' AND `meta_value` LIKE '[%' ;" 
);
```

This is not tested and you should do this on your own risk.

good luck.

**Comment by expphoto** [comment]
@bainternet Some of the links were copied and pasted when we migrated over from another site. See screenshot for relative link. The database has already been exported, find and replaced, and imported. The replace url tool doesn't work since I can't have it replace:

old: href=:/
new: href="https://

![image](https://user-images.githubusercontent.com/761323/43215722-ccf7cb72-8ff1-11e8-9cd5-6fa4fafbf241.png)

![image](https://user-images.githubusercontent.com/761323/43215913-4da999da-8ff2-11e8-98cf-1fd89114f37a.png)

**Comment by Margriet2380** [comment]
Hi 
I have the same problems with Elementor. When i used Better search and replace to replace any hyperlinks, Elementor don't renew them. When I desactivate Elementor, than the changes are visable.

**Comment by geekynoob** [comment]
I too am having the same issue.  I am trying to change a field in an iframe that exists on around 400 pages.  When looking the database the values are changed.  When using the Elementor GUI the values are still the old values.  It almost seems like something is being cached somewhere, but I do not have any caching currently enabled.

**Comment by Margriet2380** [comment]
You can used the url replace tool in Elementor to replace the url. Thats what elementor is writing

**Comment by geekynoob** [comment]
Did you see any of the previous correspondence?

If you did you would know that really doesn't answer the issue at all and
is a terrible non-descript answer.  I don't need to change a url, I need to
change a specific value on over 300 webpages.

If I am making a change directly to the database why is elementor not
getting its values from the database?  Where are the values coming from if
not directly from the database?

Your help in figuring this out would be greatly appreciated.

**Comment by Margriet2380** [comment]
Yes the same i mean to. Do it in elementor in the tools change url. It works perfect. It change for me directly 70 url's.

**Comment by Margriet2380** [comment]
But why you answer at my message, I have the same prob;em. I give the answer on my problem, that was the question!!

**Comment by geekynoob** [comment]
I don't want to change a url.

I want to mass update page content on over 300 pages.  Just for fun I tried
inputting the content I wanted to change on the page and the tool told me
"The 'from' and 'to' URL's must be valid URL's.

What I want to change on over 300 pages is

style="height:1800px;width:99%;border:none;"

to

style="height:1960px;width:99%;border:none;"

I made the change directly in the database but elementor is still getting
the old values from somewhere.

All this to say is your response still does not solve the issue at hand.

**Comment by geekynoob** [comment]
@Margriet2380 - I confused threads.  I thought you were from elementor support and I was very confused.  

Your suggestion in this case doesn't work as I am not trying to replace urls but instead mass update content on pages.  

Thanks for the input regardless!  :)

**Comment by burnyay** [comment]
Hi there,

Is there still no solution to this? I am using Better Search Replace to update content as well and while the database query seems to be completed the content isn't changed on the Elementor page.

**Comment by geekynoob** [comment]
There is still no solution directly from Elementor.  Funny enough when I opened a ticket I was told that I could not get support because I was using a 3rd party.  So I removed the 3rd party and made the change directly to the database myself, only to have the same issue.  Then their recommended solution was to use a 3rd party (https://wordpress.org/plugins/real-time-find-and-replace/).

The 3rd party solution works but is a hack. 

I pushed for support, they asked for a staging site which I provided.  It has been about 2 weeks I have followed up at least once and there has been 0 response from them.  Not exactly good customer support.

**Comment by juanmaguerrero** [comment]
I have the same problem, does anyone know where does elementor stores the data from the content that is created from the frontend view? In the database (where?) in files? (where?) Thanks so much!!

**Comment by webspreso** [comment]
Hola Juan,
It seems that Elementor stores a copy of the content in the table $pref_post_meta using the meta_key _elementor_data
Then, it applies a filter to the_content for showing the content on the frontend.

**Comment by roireshef** [comment]
Elementor guys, excuse me, but this is a paid product. How come it takes you more than a year to reply to users with the hacks you do on the background that make a simple (but important) wordpress functionality like search-and-replace to not work? Does it make sense people will reverse engineer a paid product instead of getting support?

And why in hell would you not use the original *posts* table? Why would you copy posts content to a side table on the DB and serve pages based on it? That's a real spaghetti.

**Comment by bainternet** [comment]
@roireshef 

Few corrections:

> Elementor guys, excuse me, but this is a paid product.

* Elementor is a *free open source* product and if you paid for it then you got ripped off.

> it takes you more than a year to reply

* The original OP got replied in less than a few hours so I'm not sure what you mean by that.

> Why didn't you reply in the first place that Elementor stores its data in a **different table** than the original Wordpress DB setup?

* Maybe I should have explicitly added that if it's not implied by my original reply. 

> Does it make sense people will reverse engineer a paid product instead of getting support?

* This Github repo is not a support channel/forum.

* Any Elementor Pro paid customer is entitled to support and there should be no reverse engineering involved.

> And why in hell would you not use the original *posts* table? Why would you copy posts content to a side table on the DB and serve pages based on it?

* Elementor stored the data outside the posts table for many reasons but mainly to allow you to disable elementor at any time you wish and not have nasty shortcodes or HTML comments like other page builders do.

>  This practically makes every DB manipulation tool unusable, other than your own tools...

* We know and that is why we developed these tools.

And last closed old issue threads are not regularly monitored so if you have an acceptable issue which is:
   * A bug report.
   * A Feature request.
   * A development-related question.

Then please feel free to open a new Github issue.


Thank you.

**Comment by roireshef** [comment]
@bainternet Hi Raz, thanks for correcting me. Let me add some of mine:

> Elementor is a free open source product and if you paid for it then you got ripped off.

- I have the Pro version of Elementor, and I do feel I got ripped off. This was my wife's choice, based on a word of mouth among bloggers. After researching a little bit more in the aftermath, I now understand the word of mouth is not a result of a superb product, but rather more an aggressive marketing strategy based on affiliates. I'm now looking into other tools in search for rescue.

> The original OP got replied in less than a few hours so I'm not sure what you mean by that.

- The original post was indeed replied quickly. Kudos for that. But it didn't provide a robust solution. The suggestion was a mere hack that was sealed by "do this on your own risk". The feature request was left open for the most of us, clients. At least it feels like that from my client's perspective.


> Maybe I should have explicitly added that if it's not implied by my original reply.

- Not only this is not implied by your original reply, your wording was misleading. Let me quote the part I was furious about: "Elementor stores its data in the database, so if it was changed in the database it should change in Elementor". This is going to lead any naive reader into thinking you store the data in the same place every other editor does. Who would have thought you make your own duplicates?? Do you even know how much time I spent turning on and off caching layers and debugging this nonsense, before I found [this comment](https://github.com/elementor/elementor/issues/5179#issuecomment-538321534) ?? 

> Any Elementor Pro paid customer is entitled to support and there should be no reverse engineering involved.

- Thanks for that. In reality, your support team couldn't even tell my wife hot to mark links as "no-follow". Leave all the blows and whistles aside. This is the most basic feature probably should have been existed. There was no "yeh we'll push a hotfix for that" response, but in fact "this is not supported, period."

> Elementor stored the data outside the posts table for many reasons but mainly to allow you to disable elementor at any time you wish and not have nasty shortcodes or HTML comments like other page builders do.

- Oh boy... read [that one](https://almostinevitable.com/opinion-re-moving-away-from-divi/), I couldn't have explained it better. Let me tell you on top of that, any solution that comes to not being able to search-replace with regex deserves being thrown out of the window. How are supposed to be able to maintain a +100-page website - with replacing manually, page by page?

> We know and that is why we developed these tools.

- Thanks for creating your own stack of tools, Raz, but if it aims to overcome the fact that your solution isn't modularly fitting in the WordPress ecosystem, it just ain't enough. As an engineer, I know you can do better. You had 2 choices: make your solution comply to wordpress standards and let your clients enjoy the power of open-source (use any other plugin together with Elementor), or break the API and make your clients helpless - the moment the need any functionality your team hasn't developed yet. I just understand the choice you've made - do you suggest your team develops features faster than the open-source community...?

Let me conclude with some other perspective. After watching [this benchmark](https://www.youtube.com/watch?v=RmIrqJ9Wd0U) and going through the tables in [this page](https://oxygenbuilder.com/why/visual-builders-compared/), I have no doubt, regardless of all the blows and whistles, you guys are lagging behind. A website that is super-pretty but can't get traffic due to being scored low by google, because it have so much boilerplate, is a waste of its developers time. In other words, if you have a great product but you can't sell it, you will be left with no money.

**Comment by dmpinder** [comment]
Just jumping in here, because this is still an issue for people trying to do find and replace directly within the DB, for example using WP-CLI.

Doing the usual command will not work:

```
wp search-replace 'wp-content/' 'app/' --all-tables     # Won't work
```

This is because Elementor escapes special characters in the `_elementor_data` post meta field which we want to edit.

Therefore change your WP-CLI command to include the backslash:

```
wp search-replace 'wp-content\/' 'app\/' --all-tables
```

Hope this is useful for someone!

**Comment by bjornlll** [comment]
I can't believe @dmpinder's comment hasn't received more upvotes. Life saver! Spent half a day trying to figure this out.

If any of you are trying to replace URLs, or other strings, across both Elementor and the 'normal' wordpress pages and posts, this solves it.

As @dmpinder says, Elementor stores its HTML tree in a field `_elementor_data` in `wp_postmeta`. The data is stored as string values in a JSON object.

Attaching an example, below, for regex search and replacing URLs across Elementor and the rest of WordPress

## Example: Add trailing slashes to URLs
```
// For WordPress pages and posts excl. Elementor
wp search-replace '"(https://www\.yourwebsite\.com/[A-Za-z0-9/-]*[A-Za-z0-9])"' '"\1/"' wp_post* --regex --dry-run --log

// For Elementor (notice the escaped `/` and `"`)
wp search-replace '\\"(https:\\/\\/www\.yourwebsite\.com\\/[A-z0-9\\/-]*[A-Za-z0-9])\\"' '\"\1\/\"' wp_post* --regex --dry-run --log
```
