### ISSUE TITLE
Incompatibility products "WooCommerce "

### ISSUE THREAD

**Issue by GENERAIL** [pojome/elementor#5182]
Hello 
I have a problem with product incompatibility when running "elementor" 
These products are not compatible:

1-WooCommerce Google Product Feed 
2-WooCommerce Order Status Manager 
3-WooCommerce Print Invoices/Packing Lists 
4-WooCommerce Product Bundles 
5-WooCommerce Smart Coupons

I hope you make the products compatible with all the extras this is important to me

#What are the problems when activating the product 
Problem When I activate the product I can not edit pages using a product "elementor" 
Since my site supports 70% of pages "elementor"

Thank you waiting for you

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new issue report, so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

From your report, it's not clear what the issue is and also one issue per GitHub Issue.

thanks again
