### ISSUE TITLE
Responsive display settings have 1px gap in breakpoints

### ISSUE THREAD

**Issue by localpcguy** [pojome/elementor#5221]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

When using the Advanced > Responsive section to toggle Hide on Mobile, Hide on Tablet or Hide on Desktop there is a chance the element doesn't get hidden properly. This can cause an issue where two similar elements show, for example, if used to show/hide similar elements for Mobile vs. Tablet with different images or styling.

This happens when the browser width falls in between the max-width for the mobile or tablet media query but below the min-width for the next one up, tablet or desktop respectively. For example, a browser width of 767.2px would not be hidden on mobile if the "Hide on Mobile" is checked.

## Steps to reproduce

Make 2 elements, toggle the switch to hide one on mobile, and the other to hide on tablet. Adjust the browser width so it is 767.5 (in between 767 and 768). Note you can see both elements. 

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

## Environment

<details>
<summary>System Info</summary>
```
					
== Server Environment ==
	Operating System: Linux
	Software: Apache
	MySQL version: 5.6.40
	PHP Version: 5.6.36
	PHP Max Input Vars: 1000
	PHP Max Post Size: 100M
	GD Installed: Yes
	ZIP Installed: Yes
	Write Permissions: All right
	Elementor Library: Connected

== WordPress Environment ==
	Version: 4.9.6
	WP Multisite: No
```
</details>

**Comment by localpcguy** [comment]
The fix would be to ensure the frontend styles all use max-width for the toggle styles media queries, rather than a mixture of min-width and max-width.

**Comment by bainternet** [comment]
@localpcguy 	

Devices usually have a fixed width to a pixel (768 px) and not a fraction of a pixel (767.ABC px).

So for real devices (mobile/tablet) you have no real issue here. Other than that you can set the max width of the break points yourself if you want.


thanks.

**Comment by localpcguy** [comment]
I disagree that this is not an issue. Whether it is reproducible on a device or not is not the issue. It is a simple fix to the responsive styling to ensure that there is not a 1px gap when things are hidden or shown. Please reconsider closing this issue.

**Comment by Manusan42** [comment]
@bainternet 
This is a common issue with Windows 10 display scaling (which is default) and Chrome or Firefox. As the scaled pixel value gets fractional it falls between 767 and 768px. So if you horizontally scale your browser to 767px you get no responsive column width (elementor columns) and this results in completely destroyed layout o f the whole page.

A simple and recommended solution is to use only min-width @media rules and mobile first approach.

Defining `@media (min-width: 768px) and (max-width:1024px) {` and `@media (max-width: 767px) {` as you do in Elementor styles, is simply wrong as it does not cover values between 767 and 768.

So please consider making the change either to a fractional cover like `max-width: 767.999` or better only min-width statements.

Thanks

**Comment by Salubritas** [comment]
This definitely happens in the wild due to display scaling AND also browser zoom. I came across it organically in responsive testing. Happens in FF, Chrome and Edge on the desktop just the same. Might also happen on mobile devices due to high PPI screens.

The fix/workaround to add a decimal to max-width queries is exactly how it is done in Bootstrap. You can see information on that here (search the page for "fractional"): https://getbootstrap.com/docs/4.0/layout/overview/

I really think this should be reopened and fixed.

**Comment by jeoff03** [comment]
I understand that this "fractional values" has little chance to appear on a real device.
Doesn't mean that there is no real case scenario that will cost us time and money.

Let's take the example of an agency delivering websites :
You're delivering the website to your customer.
Showcasing the work you did on desktop view.
Awesome !

Then you switch your browser in responsive view and your site appears broken in some instances.
So now you just look like a dumb amateur.

Do you think the customer is going to care about that "fractional values" explanation ?
No, he wants his website fixed.
And you don't want to have to convince him that "it's all right" and that you "did your job properly and it's not your fault".

I'll keep testing and evaluating Elementor with my current PRO personal licence as it looks really promising.
But until this is fixed, it would be insane to move all our production to Elementor PRO.

**Comment by Salubritas** [comment]
It certainly cost me time and money due to many bugs being reported at media query max-width break points. Testers and developers wasted a good amount of time.

It would be nice if the browser responsive design tools showed the decimals too rather than just truncating - it makes this problem a lot harder to diagnose then the browser claims a width of 767px but it's actually 767.4px! But I digress.

**Comment by Nyconing** [comment]
Can someone open this issue again? This is now happens on Chrome and Firefox. In 2020 real device, pixels are fractional.

**Comment by mosada881** [comment]
Upvoting to re-open. This is going to keep my OCD client who discovered it up at 3 am 3 times a week till it is fixed. Please code a fix and let this poor lady get a good night's sleep, it has been known about for 2.5 years now. ;-0

**Comment by mosada881** [comment]
Please do what you can to adress this in a future release.

**Comment by JeroenvanderPoll** [comment]
I have exactly the same issue. First happened in July 2020, then it was fixed and now it's back again.
The issue appears in (at least) Chrome, Edge and Firefox.

**Comment by JeroenvanderPoll** [comment]
I did some additional research and it appears to be a Windows related problem.
I cannot replicate it on MacOS.

https://www.gitmemory.com/issue/elementor/elementor/5221/494906090

**Comment by localpcguy** [comment]
I was definitely able to replicate it on Mac computers. It may not replicate on a retina display?

**Comment by JeroenvanderPoll** [comment]
At least not on my 5K iMac or on a linux computer of a colleague.

**Comment by localpcguy** [comment]
It is simple math. Whether you can replicate it or not is not really material. The fact is, there is a gap due to poor coding strategy of the media query choices (mixing of min/max widths). There are best practices around how to code media queries. I'm not losing sleep over this issue, but I do think it should be addressed and it does make me less likely to suggest Elementor to customers/clients of mine if it isn't, because as was mentioned in another comment, it can make the developer look like an amateur when it does break (and it does).

**Comment by JeroenvanderPoll** [comment]
I got a response from Elementor. No fix soon

_Regarding the issue here, I want to share with you that we are aware
of this issue regarding the 1px gap in breakpoints, most times when
using the responsive visibility feature to hide/show elements on the
mobile/tablet/desktop view.

As fixing these glitches requires core code changes, it will take some
time to ensure that fixing this particular glitch does not affect
other areas of Elementor. Regrettably, I won't be able to provide you
with an ETA for a resolution of this issue, but once the fix is
released we will update it on our changelog page: Changelog of
Elementor_

**Comment by localpcguy** [comment]
That's great to hear that they are at least looking into the issue! Thanks for sharing @JeroenvanderPoll

**Comment by hapiscalin** [comment]
On windows, I am having the same issue when my windows screen scale is at 125%

**Comment by mdelangeccc** [comment]
Similar to @hapiscalin , I have the same issue when my Windows screen scale is at 175%.

**Comment by Rik44444** [comment]
I also disagree this is not an issue and that this topic should be reopened. With us, this issue occurs when the width is at 767px, and we have a windows screen scaling setup at 125 or 150%. At 100% it does not happen. 
125 and 150% are extremely common screen scaling settings for laptops, which apparently results in the fractional width, so i disagree with the author above who states that that never happens in practise. 

Also, importantly, 767 px is the width to which my laptop 'snaps' windows when i put them to one side, so this error actually happens very frequently.

**Comment by black-eye** [comment]
+1

**Comment by xtiand3v** [comment]
+1

**Comment by localpcguy** [comment]
Still firmly believe this is a very reproducible issue in the wild and should be fixed. The author is incorrect that browsers do not end up in sub-pixel rendering situations, as is seen by many of the posters on this bug alone. It is best practice in development to work "mobile-first" (or even "desktop-first", but pick one) and if the CSS were written that way, it would not be an issue. This happens due to a mix of min-width and max-width settings.

**Comment by Selah1337** [comment]
Running into this issue with every single one of my sites built using Elementor. Sites built using WPBakery don't have this issue. On my Windows laptop with the screen scale set to 125%, my sites are broken in some places at 767px. Doesn't happen on my Mac or when I change the screen scale to 100% on my Windows. Now I gotta go through and manually fix all these broken places on my sites..

**Comment by Nyconing** [comment]
Above comments explained why this issue should to re-open. 
Especially it is reproducible inside a minute on every elementor website.

**Comment by cyn3rgy** [comment]
April 2022, I've just hit this issue too. Frustrating.

**Comment by mosada881** [comment]
It went away for a while but yes, it's back again sadly.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by arye-eidelman** [comment]
This actually a common resolution.
On windows 10 (most common desktop) at 1080p (most common resolution) at 1.25 display scale when you snap 2 windows side by side you get 768 pixels (1920/1.25/2).

In Chrome and Edge there is an extra .8 pixels missing in split screen **creating a resolution of 767.20 pixels**. (you can see fraction of the desktop background around and between the windows.)

You can reduce the commonality of this issue by simply adjusting your mobile breakpoint by a few pixels.

**Comment by localpcguy** [comment]
That's a greet point @arye-eidelman , however, I don't agree with your proposed resolution. They should just fix the CSS so there isn't a gap, it's a pretty simple fix to completely remove this issue. No need to adjust the mobile breakpoint (which I would argue could be a breaking change to site using this), which also just shifts the problem to a different point, and doesn't eliminate it.

**Comment by arye-eidelman** [comment]
I wasn't clear. As a temporary ~fix~ improvement, those using elementor can adjust the breakpoint in their own site. Maybe check your analytics or find published statistics on most common page widths to avoid.

**Comment by Nyconing** [comment]
They dont want to fix it because it requires css overhaul, thats why this issue still closed. A bit disappointed to fight this issue by ugly workaround but I can understand that css overhaul will break another millions css... and also break thousands of websites...

**Comment by Dixfractions** [comment]
Issue still here on January 5th 2023. What a shame that other editors don't have the issue. I consider moving to Oxygen.

**Comment by dougm1966** [comment]
Wow....I really can't believe this is a 5yr old problem and it took 18 email communications and 5 video screencasts of the errors to be told the following...

-----

Hi, I'm Araceli with Tier 2 Technical Support. I've taken over your ticket and my colleague, Latif, is currently offline.Thank you for taking the time create the videos to help us understand what you're experiencing on your end. 

After some digging on my end, I found the issue is due to a 1px gap in breakpoints, resulting in a broken layout at 767px.

Our developers are aware of this issue, but do not plan on issuing a fix any time soon due to the complexity of the code involved in the fix, as these changes can potentially do more damage than what they will resolve.

From my understanding, the 767px width is not used by tablet or mobile devices, so this issue is only reproducible by manually changing the window size.

One of our users suggested a temporary workaround in our following Github page, which you may be interested in reading (see the comments by arye-eidelman): https://github.com/elementor/elementor/issues/5221​. 

You can also add your comments on this page, as well, as they are reviewed by our developers.We sincerely apologize for any inconvenience this may cause. As always, if you have any other questions or concerns regarding this ticket, please let us know. 

Otherwise, if you have any other issues or questions unrelated to this ticket, please feel free to open a new support ticket.

Kind Regards,
​Araceli

**Comment by snandos** [comment]
We have multiple websites where display issues occur because of this. 
Its a shame that this issue still exists after so many years.
And Windows 10 / 11 with DPI > 100% is not something rare because of modern HDPI displays.
Just because it does not happen on physical tablets or mobile devices does not mean it is no issue.

We are also paying customers. Please fix this.

**Comment by MTaye** [comment]
I just modified some code to add the ".98" to max-width for responsive stuff, like in bootstrap.

Fix for Elementor 3.20.1:

elementor/core/responsive/files/frontend.php
On line 82 change
return $value . 'px';
to
return $value . ($is_max_point ? '.98' : '') . 'px';

elementor/includes/stylesheet.php
On line 409 change
$style_format[] = '(' . $end_point . '-width:' . $value . 'px)';
to
$style_format[] = '(' . $end_point . '-width:' . $value . ($end_point === 'max' ? '.98' : '') . 'px)';

Elementor > Tools > Regenerate Files & Data so that css is recompiled and the 1px gap is gone.

If anyone more knowledgeable than me can suggest how to create a override so that updating Elementor doesn't negate the changes, I'm all ears.

**Comment by abhianub** [comment]
+1

**Comment by davelavoie** [comment]
I've got the same issue. Weirdly, adjusting the mobile break point to 766px seems to have fixed the issue. 
![image](https://github.com/elementor/elementor/assets/3408028/73f1c2db-f137-45e3-9b4d-0b73f08ce4bc)

**Comment by Selah1337** [comment]
> I've got the same issue. Weirdly, adjusting the mobile break point to 766px seems to have fixed the issue. ![image](https://github.com/elementor/elementor/assets/3408028/73f1c2db-f137-45e3-9b4d-0b73f08ce4bc)

Unfortunately this solution doesn't fix the issue at its core. It just makes the layout break at a different breakpoint (i.e, between 765px and 767px as opposed to between 766px and 768px). It'll appear fixed because most people probably encountered this issue by using their browser in split screen on Windows. When the display scale on Windows devices (as far as i've seen since I haven't encountered it on Mac), is set to anything but 100% (i.e 125%, 150%, 175%), breakpoints become decimals (like 767.20px) and Elementor doesn't account for this, which is why the layout breaks. The only workaround i've found for this so far is writing a bunch of custom CSS to account for those gaps in the breakpoints.

**Comment by dougm1966** [comment]
This is something that will probably never be fixed. It's a problem at the core of Elementor and if I understand correctly, they have to rewrite the entire code base.

**Comment by MTaye** [comment]
> This is something that will probably never be fixed. It's a problem at the core of Elementor and if I understand correctly, they have to rewrite the entire code base.

Earlier in this thread I gave a [code update that fixes the issue](https://github.com/elementor/elementor/issues/5221#issuecomment-2008619752) and now I'm wondering if anyone has even tried it. It's basically the same solution that they used in Bootstrap to fix this issue, so why wouldn't it work for Elementor, you know? And it does work on my projects. If you try it, the only problem is that new Elementor updates overwrite the code changes, so you need to keep fixing it with every update.

So if any Elementor dev is listening, feel free to update the code with the fix.

**Comment by parthdream** [comment]
This is still a bug and should be reopened.
