### ISSUE TITLE
How can I enqueue a script (JavaScript file) in the Elementor Editor (Live Preview)

### ISSUE THREAD

**Issue by mdjwel** [pojome/elementor#5265]
I want to enqueue some script files in the Elementor editor preview. Is there available any hook to enqueue there my scripts?

Thanks in advanced

**Comment by bainternet** [comment]
https://developers.elementor.com/add-custom-functionality/#Registering_Custom_Styles
https://developers.elementor.com/add-custom-functionality/#Registering_Custom_Scripts

**Comment by joeczucha** [comment]
This works when you click on the "Preview Changes" button but doesn't appear to work on the live preview itself, perhaps because the widget is embedded via an iFrame? Is there any way around this? Thanks

**Comment by Spartanace1024** [comment]
Agreed I am really curious how you might go about adding javascript the editor portion as well.

**Comment by dbjpanda** [comment]
@bainternet Can you please give an example how we can enqueue a script for editor preview ?

**Comment by dbjpanda** [comment]
Okay never mind, I found an example [here](https://github.com/elementor/elementor-hello-world/blob/master/assets/js/hello-world.js) . Just change `		elementorFrontend.hooks.addAction( 'frontend/element_ready/hello-world.default', WidgetHelloWorldHandler );` to `		elementorFrontend.hooks.addAction( 'frontend/element_ready/YOUR_WIDGET_NAME.default', WidgetHelloWorldHandler );` . Widget name can be found from [here](https://github.com/elementor/elementor-hello-world/blob/09839c53401534e6a33d597be0e0de633c14c8da/widgets/hello-world.php#L28)

**Comment by ravismakwana** [comment]
Hello @dbjpanda,
How can I write other js code?

**Comment by MA7MOUDAL3RABY** [comment]
use HTML widget and add your script into script tag
example :
<script>
// your Code 
</script>

**Comment by gvgvgvijayan** [comment]
In Elementor you can find hooks related to preview iframe in the following file:
https://github.com/elementor/elementor/blob/v3.0.14/includes/preview.php (here I linked V3.0.14 instead of master repo)

For a quick look at the hooks present in the `preview.php` file:

- `elementor/preview/enqueue_styles`

https://github.com/elementor/elementor/blob/8701f250282bf8c9ee606de81dd68315953a9dc4/includes/preview.php#L274

- `elementor/preview/enqueue_scripts`

https://github.com/elementor/elementor/blob/8701f250282bf8c9ee606de81dd68315953a9dc4/includes/preview.php#L309
