### ISSUE TITLE
Border responsive

### ISSUE THREAD

**Issue by corke** [pojome/elementor#5284]
Hello all,

**What problem is your feature request going to solve? Please describe.**
I can't use border in responsive, hide or show or just modify border for the differents devices.

**Describe the solution you'd like**
Just integrate border responsive like for the others option responsive (margin / padding / font etc..)

Thanks

**Comment by KoshaK0** [comment]
Hi, I think if Developers will Separate CSS Files for different View Modes, then ALL options will be available for diferent views, not just some of them. Ha?

**Comment by corke** [comment]
I don't know how they do, but all I can say it's they have integrate well the responsive for 3 device mode for some features, like font options or margin /padding, but you don't have for the borders and I think for some others css functions too where you don't have this responsive features.

**Comment by Ricarditu** [comment]
Good idea!

Also, there could be the option for different color for each border side. I got this situation more than once and it would be very useful.

Thanks!

**Comment by AppGrind** [comment]
I agree with @corke feature request.

I am currently stuck with a borderless menu on big screens because on medium and small screens with a border it just doesn't look nice. I have an icon list above the menu which reads (Navigation) with a maps-o icon and a background color of 787878 which the menu items are separated with a color of ddddd, as per client design.

I think this feature should be added. Shouldn't be too hard, right?
