### ISSUE TITLE
Feature Request: Allow filtering of structural markup

### ISSUE THREAD

**Issue by iamcanadian1973** [pojome/elementor#535]
I realize I'm getting picky here. But it would be awesome if you could filter the markup. Be able to:

-Add/remove structural markup in sections
-Change element classes/id's/data attributes (especially in the grid).

I'm a big fan of Foundation, I know others love Bootstrap. This has been a long desired feature of mine for any page builder.

More filters throughout would be awesome.

**Comment by joshmarom** [comment]
We added some hooks that allow you to filter widgets output, for example:
https://github.com/pojome/elementor/blob/develop/docs/content/hooks/php-hooks.md#elementorwidgetrender_content

Unfortunatly when it comes to the grid and the basic structural markup, I'm afraid this isn't quite possible to allow that, since it will compromise the integrity of the builder. Any change done on that level can have drastic unexpected effects.
