### ISSUE TITLE
Feature Request: Allow Show/Hide/Removal of elements in panel by post type

### ISSUE THREAD

**Issue by iamcanadian1973** [pojome/elementor#536]
As an example: not every website is going to need a Google map, progress bar, image carousel, counter etc....

I'd prefer if my clients didn't see any of those options altogether.

I'd also prefer they didn't see any of the default WordPress widgets. Or at least where I have control of which ones they would see.

**Comment by zu** [comment]
+1

**Comment by zu** [comment]
it's easy to remove elementor widgets by deleting them from the array `$build_widgets_filename` in `widgets-manager.php`

I know this is surely not a solid and good way, but it seems to work.

Any hints on how to better select-de-select / register-de-register widgets would be appreciated and of course I'd love to have an option to have a control to choose which of all widgets (elementor, wordpress and custom) to have available in the panel.

**Comment by InternetSemplice** [comment]
+1
This is also the need I have!
AND I think it is the same need of designers who develop a website for clients whom need to add themselves the posts to their business blog: the need for a customization role based of the available Modules to show.
This is indeed also the way other Visual D&D Builders plugins are offering.
Elementor is great, bus the risk to give the client an interface to mess up with is too risky. They will call me every day, or more… ;-).
BTW, on the time being the solution will be available, what about the way @zu suggested in #536?
Thanks a lot anyway!
Andy

**Comment by carasmo** [comment]
It would be idea if the `elementor/widgets/black_list` filter, which works fine for removing anything but elementor widgets would work:
```

function prefix_blacklist_widgets( ){

	$black_list = [
		'Elementor\Widget_Image_Gallery', // nope
		'Simple_Social_Icons_Widget' // yep
	];

	return $black_list;

}
add_filter( 'elementor/widgets/black_list' , 'prefix_blacklist_widgets' );

```

**It would be idea to remove based on the situation with a filter or a way to turn on or off in Settings.**

**Comment by arielk** [comment]
I merged this issue with another issue #1314 in the same subject so we could deal with it more efficiently. So please let's continue the conversation there.

Thanks for your feedback!

**Comment by Choufourax** [comment]
+1 for the ability to disable unwanted widgets

**Comment by pulla** [comment]
Hello, 

I am sorry if I am asking this issue which is already solved.

**I am still looking for disable (or hiding ) some widgets by template and custom post type.**
I just want to show necessary widgets on the pages or template pages. 

@carasmo black list seems not working yet.  

Is there any update about it? 

Thanks

**Comment by spacemano** [comment]
Hello,

Try this code

```
add_action('elementor/widgets/widgets_registered', 'custom_unregister_elementor_widgets');

function custom_unregister_elementor_widgets($obj){
	$obj->unregister_widget_type('image'); // This hides the Image widget for example
}
```

You can see the list of all widgets in elementor/includes/managers/widgets.php in the $build_widgets_filename array.

**Comment by gianghl1983** [comment]
> 
> 
> Hello,
> 
> Try this code
> 
> ```
> add_action('elementor/widgets/widgets_registered', 'custom_unregister_elementor_widgets');
> 
> function custom_unregister_elementor_widgets($obj){
> 	$obj->unregister_widget_type('image'); // This hides the Image widget for example
> }
> ```
> 
> You can see the list of all widgets in elementor/includes/managers/widgets.php in the $build_widgets_filename array.
> 
> You can add all the necessary checks for post type and template into the function if you want I guess.

Do we have any benifit of removing widgets (Speed increase) ?

**Comment by arielk** [comment]
@gianghl1983 No, the scripts are loaded according to the widgets that you used on the page.

**Comment by thomasmalley** [comment]
> Hello,
> 
> Try this code
> 
> ```
> add_action('elementor/widgets/widgets_registered', 'custom_unregister_elementor_widgets');
> 
> function custom_unregister_elementor_widgets($obj){
> 	$obj->unregister_widget_type('image'); // This hides the Image widget for example
> }
> ```
> You can see the list of all widgets in elementor/includes/managers/widgets.php in the $build_widgets_filename array.
> 
> You can add all the necessary checks for post type and template into the function if you want I guess.

This however is **not** the ideal way if I'm not mistaken because it can break parts of the website. For Example:  I created a page using the **Shortcode** widget at one point for a client. I don't want the client to see the Widget in the Elementor Editor's Sidebar because it is to confusing for him; Only the most basic Stuff like Image, Headline etc. ... If I disable the Shortcode Widget using the Code you mentioned all Content which was created using the Shortcode Widget won't be visible any more for Visitors (FrontEnd). 

The OP said:

> I'd prefer if my clients didn't see any of those options altogether.

So we are talking about different Views: What the Client logged into the Backend using Elementor Editor sees (the List of available Widgets) and what the User sees (Front End). 

Editing the Backend view (List of available Widgets for certain Role in the Editor) should **not** influence the FrontEnd view (Content created using hidden Widgets) at all!

**Comment by pako69** [comment]
Hi

Yes it would be very useful to be able to remove widgets from the Elementor builder panel by roles!

How ever I tried with the given PHP code below:

```
add_action('elementor/widgets/widgets_registered', 'custom_unregister_elementor_widgets');
function custom_unregister_elementor_widgets($obj){
	$obj->unregister_widget_type('image'); // This hides the Image widget for example
}
```

Yes It works but as mentioned it remove the widget from everywhere (both front and back sides).

BUT if you install and use this free WordPress plugin: https://wordpress.org/plugins/code-snippets/ you can add a snippets that only run in the WordPress Administration area, that way if you remove the image widget, this widget will continue to be displaud in front end but not in the Elementor builder area.

Unfortunately this will also remove it for you who are administrator. How ever it's pretty easy to look at the user role befor running this.

---
**I have a question:** where I can find the names used for the PRO widgets? because 'elementor/includes/managers/widgets.php' seems to list only thre free widgets...

Thanks
