### ISSUE TITLE
Post Excerpt element and html tag

### ISSUE THREAD

**Issue by ianstudio** [pojome/elementor#5491]
Hi,
the Post Excerpt does not "obey" html tags, for instance I often add break elements <br> in my excerpts which are then picked up by my grid plugins (The Grid etc, have not et paid much attention as to what Elementor tool may pick them up s well.. or not, I hope they all do post grids and such...) 

BUT when I make an Elementor template and add a Post Excerpt in it the <br> becomes inlined as text :/ How sad is that..

Thanks

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

as for the issue, Elementor Post excerpt widget (assuming that is wat you are using) does strip HTML tag.

Will be fixed in next version.

**Comment by ianstudio** [comment]
Good, thanks.

**Comment by arielk** [comment]
This is now available in Elementor Pro v2.1.6 

Thanks for your feedback!

**Comment by mbleverage** [comment]
I am on elementor 2.5.1, Elementor Pro 2.4.6, Wordpress 5.1 and the html tags are still getting stripped.  Any ideas.
