### ISSUE TITLE
Add "woocommerce_before_single_product_summary" to Single Product Page Template

### ISSUE THREAD

**Issue by 1sourceweb** [pojome/elementor#5574]
## Prerequisites

- [X] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [X] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Hi guys, I am loving the new Woo   Commerce Widgets and templates. I am wondering how I can add a Specific   WooCommerce Hook to the Single Product Page Template. 

**Describe the solution you'd like**
You currently have   included:      
woocommerce_product_thumbnails   
woocommerce_before_add_to_cart_form   
woocommerce_before_add_to_cart_button   
woocommerce_after_add_to_cart_button   
woocommerce_single_variation   
woocommerce_after_add_to_cart_form   
woocommerce_variable_add_to_cart   
woocommerce_product_tabs     

 The two I need are: 
"woocommerce_before_main_content"
"woocommerce_before_single_product_summary"
![elemento_single_products_page_missing_woo_hooks](https://user-images.githubusercontent.com/38915589/44723140-0751b380-aa84-11e8-84b3-7a453eac03d0.png)
![woo_defualt_single_product_page_hooks](https://user-images.githubusercontent.com/38915589/44723141-0751b380-aa84-11e8-9ed1-4f51fc64e7d8.png)

   (REALLY need thins one as it is the one used by this product designer I am using)

Can these hooks be added?

--

**Describe alternatives you've considered**

**Additional context**

**Comment by bainternet** [comment]
@1sourceweb 

We tried adding all default WooCommerce hooks but we found that we either break most 3rd part themes and plugins or we break the editor. So we decided not to include all default hooks on all pages.

A solution I can suggest is to create a simple shortcode function which will act as a placeholder for hooks, eg: 
```php
add_shortcode( 'do_hook', function( $atts = array(), $content = null, $tag = ''){
	if ( isset( $atts['hook'] ) ) {
		do_action( $hook );
	}
	return;
});
```

and once you have this shortcode registred on your site you can use it in elementor shortcode widget which you can place anywhere you want, ex:

`[do_hook hook="woocommerce_before_main_content"]`

Hope this helps.

**Comment by BaloghGabor** [comment]
@bainternet 
Hello Raz,

I have the same problem and I tried to find out how to make the shortcode work, but unfortunately, could not make it. I have contacted everyone Elementor Pro (the page builder used), OceanWP (theme active) and Fancy Product Designer (the third-party plugin) too, but none of them actually helped. They are pointing to each other who should solve it. I have 0 knowledge of programming. All I know is that the third-party plugin works after Elementor Pro is deactivated. 

Tried to rewrite the content-single-product.php file in cpanel (public_html/wp-content/themes/oceanwp/woocommerce) as the third-party plugin's debug option says that the missing hooks are caused by the theme. Followed the plugin's guide. I have copied the lines from here. Not sure If I could have copied anything inappropriately. 
https://support.fancyproductdesigner.com/support/solutions/articles/5000582912-using-the-debug-mode-to-inspect-any-missing-hooks-in-woocommerce-product-pages 

If you have time, could you please help and guide me to fix it? 

I have attached a picture from the third party plugin's debug message.

Thank you in advance for your reply! 

![missing hook - fpd debug](https://user-images.githubusercontent.com/45736709/49699473-13e0be80-fbd2-11e8-8bd4-c53c22e81377.jpg)

**Comment by BaloghGabor** [comment]
@1sourceweb
Hello Hutch,

Did you manage to solve the missing hook issue? If yes, could you please share the code that you have implemented and the php file where it should be copied? Should it be in the Elementor's or theme's folder?

Thank you in advance!

**Comment by nigel-wells** [comment]
I have found this solution to work for what I needed which was to make use of `woocommerce_before_main_content` and `woocommerce_after_main_content` hooks.
```
add_action( 'elementor/widget/render_content', function( $content, $widget ) {
   if ( 'woocommerce-archive-products' === $widget->get_name() ) {
        // Run the hooks without outputting the code that `do_action` will want to do
        ob_start();
        do_action('woocommerce_before_main_content');
        $beforeMainContent = ob_get_contents();
        ob_clean();
        do_action('woocommerce_after_main_content');
        $afterMainContent = ob_get_contents();
        ob_end_clean();
        // Attach the output from the two hooks before and after the content generated by Elementor
   	$content = $beforeMainContent . $content . $afterMainContent;
   }

   return $content;
}, 10, 2 );
```
This hooks in to elementor and triggers both hooks when relevant to the `woocommerce-archive-products` widget.

**Comment by BaloghGabor** [comment]
@nigel-wells 
Hello Nigel, 
Sorry for the late reply it was a busy period.

Thank you so much for your help! :)
Wish you a great and successful year!

**Comment by brevalo1** [comment]
> I have found this solution to work for what I needed which was to make use of `woocommerce_before_main_content` and `woocommerce_after_main_content` hooks on the product archive pages.
> 
> ```
> add_action( 'elementor/widget/render_content', function( $content, $widget ) {
>    if ( 'woocommerce-archive-products' === $widget->get_name() ) {
>         // Run the hooks without outputting the code that `do_action` will want to do
>         ob_start();
>         do_action('woocommerce_before_main_content');
>         $beforeMainContent = ob_get_contents();
>         ob_clean();
>         do_action('woocommerce_after_main_content');
>         $afterMainContent = ob_get_contents();
>         ob_end_clean();
>         // Attach the output from the two hooks before and after the content generated by Elementor
>    	$content = $beforeMainContent . $content . $afterMainContent;
>    }
> 
>    return $content;
> }, 10, 2 );
> ```
> 
> This hooks in to Elementor and triggers both hooks when relevant to the `woocommerce-archive-products` widget.

Hello, your solution is perfect!
Now I would like to make **woocommerce_before_single_product_summary** appear. So, I change your code this way. But didn't help.
How can I solve it?


 `add_action( 'elementor/widget/render_content', function( $content, $widget ) {
   if ( 'woocommerce-archive-products' === $widget->get_name() ) {
        // Run the hooks without outputting the code that `do_action` will want to do
        ob_start();
        do_action('woocommerce_before_single_product_summary');
        $beforeSingleproductsummary = ob_get_contents();
        ob_end_clean();
        // Attach the output from the two hooks before and after the content generated by Elementor
   	$content = $beforeSingleproductsummary . $content;
   }

   return $content;
}, 10, 2 `);``

Thank you very much in advance.

**Comment by brevalo1** [comment]
Hello, 

I changed the solution code for "woocommerce_before_single_product_summary": 
```
add_action(` 'elementor/widget/render_content', function( $content, $widget ) {
   if ( 'woocommerce-archive-products' === $widget->get_name() ) {
        // Run the hooks without outputting the code that `do_action` will want to do
        ob_start();
        do_action('woocommerce_before_single_product_summary');
        $beforeSingleproductsummary = ob_get_contents();
        ob_end_clean();
        // Attach the output from the two hooks before and after the content generated by Elementor
   	$content = $beforeSingleproductsummary . $content;
   }

   return $content;
}, 10, 2 );

```

But didn't help....
Maybe I made a mistake?


Thank you for your effort.

**Comment by brevalo123** [comment]
Os there any solution for woocommerce_before_single_product_summary

**Comment by emre-edu-tech** [comment]
Hi there! Do we have a solution for filters like for the actions that are provided above? Because for example 'the_title' filter does not work on Single Product Template. Or maybe it was out of my skills' reach but I really can not get it working.
Thanks!

**Comment by ninetyninew** [comment]
We would like to know the same as above, is there anyway Elementor can use these missing WooCommerce core filters/actions without this workaround of a shortcode? Either way it would be good if Elementor had information related to this and potential workarounds in the documentation somewhere so we could link users struggling with this to help them fix the issues due to Elementor not using the standard actions/hooks.

**Comment by WebmonitorBondis** [comment]
Hi Everyone,

I have a solution that will hopefully help people still stuck with this problem. I am making the assumption that you are developing your own plugin. If not, check with the developers of the plugin before modifying code that is not yours (just in case they have already implemented their own fix, etc).

I was able to get the hooks: "woocommerce_after_single_product_summary" working. My solution is based on code previously added in the comments, but changed to be more flexible. Because certain widgets like: "product-short-description" might be awkwardly placed for what you are trying to do.

First of all, the code: `( 'woocommerce-product-short-description' === $widget->get_name() )` will check the name of a widget type that is found in Elementor. So this will not work: `( 'woocommerce_before_single_product_summary' === $widget->get_name() )` because this is not the name of a widget in Elementor. You need to be a bit more creative.

You can try looking at different Elementor Widgets and their names, but my solution was to use the html widget. In WordPress go to: Templates -> Theme Builder -> Single Product -> [The template that you need] -> Edit. This was where I needed to make changes in order to get the corrects hooks working.

In the editor, search for a html widget and drag it in to the place where you want the content to end up. Put a unique string inside the widget, for example: "elementor_fix_unique_replacement_string". Save the template.

Next add this line of code to your plugin (in this example, I am only using: "woocommerce_after_single_product_summary"):
```
function wc_custom_extensions_fix_elementor($Content, $Widget) {
	$WidgetName = $Widget->get_name();
	
	//Check the name/type of the widget
	//And check if the content of the widgets matches your unique string
	if ($WidgetName === 'html' && $Content === 'elementor_fix_unique_replacement_string') {
		//First we empty the output to make sure the string does not show up on the front end page
		$Content = '';
	
		//Run the hook without outputting the code that `do_action` will want to do
		ob_start();
		do_action('woocommerce_after_single_product_summary');
		$Output = ob_get_contents();		
		ob_end_clean();

		//Attach the output from the hook after the content generated by Elementor
		$Content = $Output;
	}
	return $Content;	
}
```

You can maybe remove some lines of code, depending on your situation. For example, the: `$Content = '';` might be unnecessary. But I wanted to make sure it will work for most people. Also add the correct add_action to your plugin.
`add_action( 'elementor/widget/render_content', 'custom_fix_elementor_wc_hooks', 10, 2 );`

And of course make sure that your plugin uses: "woocommerce_after_single_product_summary"
`add_action( 'woocommerce_after_single_product_summary', 'your_own_function_name' );`

This way you can get the contents of most WooCommerce hooks and place it where ever, without having to rely on standard Elementor widgets that might be in the wrong place. But, there may still be a problem, that I will cover down here.

If you are using WooCommerce hooks, you might end up with content from the hooks that is already added to the page through normal Elementor widgets (for example, related articles). So what do you do if you only want the content from your own plugin? You can create/use your own hook.
```
function wc_custom_extensions_fix_elementor($Content, $Widget) {
	$WidgetName = $Widget->get_name();
	
	//Check the name/type of the widget
	//And check if the content of the widgets matches your unique string
	if ($WidgetName === 'html' && $Content === 'elementor_fix_unique_replacement_string') {
		//First we empty the output to make sure the string does not show up on the front end page
		$Content = '';
	
		//Run the hook without outputting the code that `do_action` will want to do
		ob_start();
		do_action('woocommerce_custom_hook_fix_elementor');
		$Output = ob_get_contents();
		ob_end_clean();

		//Attach the output from the hook after the content generated by Elementor
		$Content = $Output;
	}
	return $Content;	
}
```

Also add the correct add_action to your plugin.
`add_action( 'elementor/widget/render_content', 'custom_fix_elementor_wc_hooks', 10, 2 );`

And of course make sure that your plugin usses: "woocommerce_custom_hook_fix_elementor"
`add_action( 'woocommerce_custom_hook_fix_elementor', 'your_own_function_name' );`

This way you can get the contents of only your plugin and place it where ever, without getting to much content that is already on the page somewhere else.

**Comment by jlstysis** [comment]
Thank you WebmonitorBondis for your post! It's a great help!
A few questions, if I may.
The line add_action( 'elementor/widget/render_content', 'custom_fix_elementor_wc_hooks', 10, 2 ); lists a function name that's not defied in your code above. Is that by design or a mistake?
When I substitute "custom_fix_elementor_wc_hooks" with "wc_custom_extensions_fix_elementor" everything works, but when I use this code for the "woocommerce_before_single_product_summary" hook in order to display product image, the resting image is smaller than it should be and I'm unable to resize it. Any idea why?

**Comment by jlstysis** [comment]
Found a fix via CSS!

/*fix image width*/
.woocommerce-product-gallery.woocommerce-product-gallery--with-images.woocommerce-product-gallery--columns-4.images {
width: 100% !important;
}

**Comment by joannavgp** [comment]
> Hi Everyone,
> 
> I have a solution that will hopefully help people still stuck with this problem. I am making the assumption that you are developing your own plugin. If not, check with the developers of the plugin before modifying code that is not yours (just in case they have already implemented their own fix, etc).
> 
> I was able to get the hooks: "woocommerce_after_single_product_summary" working. My solution is based on code previously added in the comments, but changed to be more flexible. Because certain widgets like: "product-short-description" might be awkwardly placed for what you are trying to do.
> 
> First of all, the code: `( 'woocommerce-product-short-description' === $widget->get_name() )` will check the name of a widget type that is found in Elementor. So this will not work: `( 'woocommerce_before_single_product_summary' === $widget->get_name() )` because this is not the name of a widget in Elementor. You need to be a bit more creative.
> 
> You can try looking at different Elementor Widgets and their names, but my solution was to use the html widget. In WordPress go to: Templates -> Theme Builder -> Single Product -> [The template that you need] -> Edit. This was where I needed to make changes in order to get the corrects hooks working.
> 
> In the editor, search for a html widget and drag it in to the place where you want the content to end up. Put a unique string inside the widget, for example: "elementor_fix_unique_replacement_string". Save the template.
> 
> Next add this line of code to your plugin (in this example, I am only using: "woocommerce_after_single_product_summary"):
> 
> ```
> function wc_custom_extensions_fix_elementor($Content, $Widget) {
> 	$WidgetName = $Widget->get_name();
> 	
> 	//Check the name/type of the widget
> 	//And check if the content of the widgets matches your unique string
> 	if ($WidgetName === 'html' && $Content === 'elementor_fix_unique_replacement_string') {
> 		//First we empty the output to make sure the string does not show up on the front end page
> 		$Content = '';
> 	
> 		//Run the hook without outputting the code that `do_action` will want to do
> 		ob_start();
> 		do_action('woocommerce_after_single_product_summary');
> 		$Output = ob_get_contents();		
> 		ob_end_clean();
> 
> 		//Attach the output from the hook after the content generated by Elementor
> 		$Content = $Output;
> 	}
> 	return $Content;	
> }
> ```
> 
> You can maybe remove some lines of code, depending on your situation. For example, the: `$Content = '';` might be unnecessary. But I wanted to make sure it will work for most people. Also add the correct add_action to your plugin. `add_action( 'elementor/widget/render_content', 'custom_fix_elementor_wc_hooks', 10, 2 );`
> 
> And of course make sure that your plugin uses: "woocommerce_after_single_product_summary" `add_action( 'woocommerce_after_single_product_summary', 'your_own_function_name' );`
> 
> This way you can get the contents of most WooCommerce hooks and place it where ever, without having to rely on standard Elementor widgets that might be in the wrong place. But, there may still be a problem, that I will cover down here.
> 
> If you are using WooCommerce hooks, you might end up with content from the hooks that is already added to the page through normal Elementor widgets (for example, related articles). So what do you do if you only want the content from your own plugin? You can create/use your own hook.
> 
> ```
> function wc_custom_extensions_fix_elementor($Content, $Widget) {
> 	$WidgetName = $Widget->get_name();
> 	
> 	//Check the name/type of the widget
> 	//And check if the content of the widgets matches your unique string
> 	if ($WidgetName === 'html' && $Content === 'elementor_fix_unique_replacement_string') {
> 		//First we empty the output to make sure the string does not show up on the front end page
> 		$Content = '';
> 	
> 		//Run the hook without outputting the code that `do_action` will want to do
> 		ob_start();
> 		do_action('woocommerce_custom_hook_fix_elementor');
> 		$Output = ob_get_contents();
> 		ob_end_clean();
> 
> 		//Attach the output from the hook after the content generated by Elementor
> 		$Content = $Output;
> 	}
> 	return $Content;	
> }
> ```
> 
> Also add the correct add_action to your plugin. `add_action( 'elementor/widget/render_content', 'custom_fix_elementor_wc_hooks', 10, 2 );`
> 
> And of course make sure that your plugin uses: "woocommerce_custom_hook_fix_elementor" `add_action( 'woocommerce_custom_hook_fix_elementor', 'your_own_function_name' );`
> 
> This way you can get the contents of only your plugin and place it where ever, without getting to much content that is already on the page somewhere else.
________________________________________________________________________________________________________________
Hi! I have found your comment which explains how to make woocommerce hooks work with elementor. I understand the idea, but honestly, my acknowledgment of the area has its limitations. I'm going to explain to you my need, and maybe you could clarify what I have to do in my case. I'm working on a staging site before overwriting the current one. What I am trying to do is to add a contact form for those 'out-of-stock' products, so people can request the product for re-stock.  Currently, I have this snippet, and as I said, it works perfectly well in my current theme, but the one that I am expecting to launch is not because of Elementor.

`/* Show contact form instead of "Out Of Stock" message */

add_action('woocommerce_single_product_summary', 'out_of_stock_show_form', 50);
function out_of_stock_show_form() {
    global $product;
    if(!$product->is_in_stock( )) {
        echo  '<b>Notify me when the item is back in stock.</b>';
        echo  do_shortcode('[contact-form-7 id="8744" title="Waiting list"]'); // Replace with your own contact form shortcode
       }
}
/* This will show your contact form when the variation is out of stock */

add_filter( 'woocommerce_available_variation', 'variation_out_of_stock_show_form', 10, 3 );
function variation_out_of_stock_show_form( $data, $product, $variation ) {
    if( ! $data['is_in_stock'] )
    {
        $data['availability_html'] = '<div class="your-form">';
        $data['availability_html'] .= '<b>Notify me when the item is back in stock.</b>';
        $data['availability_html'] .= do_shortcode('[contact-form-7 id="8744" title="Waiting list"]'); // Replace with your own contact form shortcode
        $data['availability_html'] .= '</div>';
    }
	return $data;
}`

Since the new theme works with Elementor, that snipped doesn't work. It barely appears for variation products only.
I read many time your suggested code but I have no idea how to apply it to my case.

Could you help me, please?

**Comment by Julezeee** [comment]
Hey,

the shortcode seems not to work for me, but creating my own hook with that html-widget works, kind of...

On that page you can see that this curved arrow is added twice (it should only once, right above the product image): 
[Example](https://mediamagica.de/?product=kommt-ein-vogel-geflogen-liederbuch-mit-41-klassischen-kinderliedern)

 I just added the code from above to my site and then I put the html-widget to the single product page in Elementor THEME BUILDER...
