### ISSUE TITLE
Wrap text around another widget

### ISSUE THREAD

**Issue by pb52** [pojome/elementor#5619]
I love building pages with Elementor.  Posts are a different matter though.

Like many bloggers my posts are a mixture of text with images / video media.

In The TinyMCE editor I can insert media and align it so the text wraps around it,  In Elementor if I try to drag a media widget into the text it gets places above or below.  I watched a video explaining how to do this but it is too complex for a novice like me.

I tried using two inner sections, one for the video and another for the text, but the text column doesn't wrap.  So I am reduced to creating a separate full width section to create the wrap effect, but positioning it relative to the previous text is an issue.

Please can we have the ability to place another Elementor widget into a text widget, with wrap around?

**Comment by bainternet** [comment]
@pb52 

Currently, this feature is not supported or even possible, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by erfan-ilyas** [comment]
I was also looking for this but for the images.

For example, I want to place an image widget on the left and then post content widget wrapped around it.

Seems like it's not even possible with custom CSS?

I have tried doing it with CSS if you guys can help me with the CSS that will be great. (Elementor Pro user here)

Otherwise, I have to create my own shortcode.
