### ISSUE TITLE
Page template as condition (pro)

### ISSUE THREAD

**Issue by amindiary** [pojome/elementor#5792]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

Isn't a way to set single page template to pages with X page template?
I need this to enable disable sidebar for **pages with Page full width** and **page has sidebar**

![image](https://user-images.githubusercontent.com/2544046/45947746-10d82800-bffe-11e8-8d92-7e8d75299adb.png)

**Comment by pixelsock** [comment]
@amindiary you can add page templates to custom taxonomies. That's what I did in order to get around this. I build out a custom taxonomy called Page Layouts and assigned templates to that. Highly used, highly rated plugin [custom post type UI](https://wordpress.org/plugins/custom-post-type-ui/) if you're interested.

**Comment by amindiary** [comment]
@pixelsock yeah I was thinking of using tags. but custom tax is better idea, thanks.

**Comment by bainternet** [comment]
@amindiary 

Glad you found a workaround.
