### ISSUE TITLE
Widget hooks are not working in Elementor.

### ISSUE THREAD

**Issue by h71** [pojome/elementor#5844]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Many users are using `in_widget_form` and `widget_update_callback ` hooks to add custom fields to widgets.
Seems that Elementor doesn't calls these hooks at all. There is no visible custom markup in widget form while using widgets from Elementor and it shows only default widget fields.

Also there is some plugins that are using these hooks to extend widgets functionality. (e.g. Advanced Custom Fields) and these hooks are necessary for them.

## Steps to reproduce
Use the following code to add something in widgets. It works in Appearance-> Widgets, But not in Elementor-> WordPress Widgets.
```
add_action('in_widget_form', 'issue_in_widget_form' );

function issue_in_widget_form( $instance ){
    echo 'This should be visible in Elementor too.';
    return $instance;
}
```

## Isolating the problem

- [x] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by bainternet** [comment]
@h71 

Thanks for reporting.

**Comment by MartinStehle** [comment]
Hi, I offer a plugin which adds some options to any widget via the hooks `in_widget_form`. Elementor uses this hook, too. The extra options are displayed in the editor. But saving their settings failes since the hook `widget_update_callback` is not integrated in Elementor.

Is it possible to ad the missing hook in Elementor? Are the hooks also integrated into Elementor Pro?
