### ISSUE TITLE
Forms Webhook + Google Sheet integration via App Script 

### ISSUE THREAD

**Issue by chalgerro** [pojome/elementor#5894]
Hi everyone, 

I would like to investigate wheather it's possible to save form reaponses directly to Google Sheets using App Script.
Google sheets are widely popular and free. I know there's a working solution to use Zappier to save form responses to Sheets, but it's limited to 100 tasks per month on free account and that's not enough for my purpose, (I use it for a charity organisation, which unfo won't pay for Zappier).

Anyways, could you please enlighten me how to integrate Elementor Forms and Google Sheets, I would muuuch appreciate it :)

Thank you in advance.

**Comment by chalgerro** [comment]
OK, after digging for some time I created a fairly easy integration between Elementor form and Google sheets using App Script. 

1. Open a new sheet in Google drive
2. Open tools > script editor. You will see script editor.
3. Over there remove everything and paste
```
function doGet(e) {}
function doPost(e) {
var o = e.parameter;
SpreadsheetApp.getActiveSheet().appendRow([ o.YOURLABEL1, o.YOURLABEL2, o.YOURLABEL3, e ]);
}
```
4. Save the project under any name
5. From the Publish menu, select Deploy as web app…
6. Choose to execute the app as yourself, and allow "Anyone, even anonymous" to execute the script. If this option is not available it means that your Google account is dependable on Google Apps administrator - if so use regular @gmail account and start from scratch) 
7. Copy the link seen in this window
8. Only then click Deploy. You may be asked to review permissions now.
(IMPORTANT: If you make any changes to the code above ALWAYS repeat point 5 and 6 and in the window shown ALWAYS choose "Project version" -> New (!!!)
8. Go to Elementor
9. Create a form, skip customising for now. In the form panel go to Action after submit choose "Webhook"
10. A new panel will be shown below (Webhook). Paste the copied URL which suppose to look something like this: https://script.google.com/macros/s/XXXXXXXXX/exec
if it ends with "dev" just change it do "exec".
11. Format your form to your liking and MOST importantly name your form fields using Label field available for Each of the fields. As you look at the form field panel you see "Type" and Label below, change the label to: YOURLABEL1, and do the same with remaining fields changing labels to YOURLABEL2, YOURLABEL3 etc. You may use any label just remoember to adjust the code above accordingly.
12. Save and preview your Elementor form
13. Enter any details to your form and send.
14. Answers supposed to be automatically saved to the google sheet
15. The "e" in the code above is onle for testing purpose so you would know how you data looks like when it reaches google forms, you may remove it if not needed along with the comma before the e.

Please let me know if this worked for you, it does a great job for me. Really easy stuff!

Best of luck anyone!

**Comment by bainternet** [comment]
@chalgerro 

I have an even simpler script that can handle many forms and Field names automatically, meaning it will create a new sheet for each form and set the headers automatically based on the form fields and even send an email to notify you about it.

In order to enable this script, follow these steps:
 * From your Google Sheet, from the Tools menu select Script Editor…
 * Paste the script from [this gist](https://gist.github.com/bainternet/4b539b00a4bd7490ac3809d7ff86bd14) into the script code editor and hit Save.
 * From the Publish menu, select Deploy as web app…
 * Choose to execute the app as yourself, and allow Anyone, even anonymous to execute the script. (Note, depending on your Google Apps instance, this option may not be available. You will need to contact your Google Apps administrator, or else use a Gmail account.) Now click Deploy. You may be asked to review permissions now.
 * The URL that you get will be the webhook that you can use in your elementor form, You can test this webhook in your browser first by pasting it. It will say "Yepp this is the webhook URL, request received".
 * Last all you have to do is setup and Elementor Pro Form with a form name and Webhook action pointing to the URL from above.

**Comment by laratuk** [comment]
Connect Elementor Form to Google Sheet with Piotnet Addons. Tutorials https://pafe.piotnet.com/connect-form-to-google-sheets/

**Comment by bebotette** [comment]
@bainternet sorry I know this post hasn't been updated for a while. But I tried every step in your instructions but I don't seem to get anything in my Gsheet. I tried the URL in my browser and yes I got the "Yepp this is the webhook URL, request received". But nothing happens when I submit form. Please help

**Comment by FairhopeCreative** [comment]
@bainternet - the script is no longer working. Just ran through your steps and the webhook didn't pass info to Google Sheets. The webhook shows a positive message, I receive an email from Elementor to my email, but I don't have a database generated as you suggest.

Changed my email in the script editor and have the proper settings. 

One thing I noticed under project properties in the google script editor is that it suggests 2 scopes be enabled:
- https://www.googleapis.com/auth/script.send_mail
- https://www.googleapis.com/auth/spreadsheets

I see a sheets API to enable, but the only API I see involving email is Gmail and Cloud Messaging.

Could that be a reason that @bebotette and I are unable to pass along data to our respective spreadsheets? We don't have the proper API's enabled?

**Comment by bainternet** [comment]
@FairhopeCreative @bebotette 

just tested again, Everything was just fine!

**Comment by spsrijan** [comment]
> 
> 
> @chalgerro
> 
> I have an even simpler script that can handle many forms and Field names automatically, meaning it will create a new sheet for each form and set the headers automatically based on the form fields and even send an email to notify you about it.
> 
> In order to enable this script, follow these steps:
> 
>     * From your Google Sheet, from the Tools menu select Script Editor…
> 
>     * Paste the script from [this gist](https://gist.github.com/bainternet/4b539b00a4bd7490ac3809d7ff86bd14) into the script code editor and hit Save.
> 
>     * From the Publish menu, select Deploy as web app…
> 
>     * Choose to execute the app as yourself, and allow Anyone, even anonymous to execute the script. (Note, depending on your Google Apps instance, this option may not be available. You will need to contact your Google Apps administrator, or else use a Gmail account.) Now click Deploy. You may be asked to review permissions now.
> 
>     * The URL that you get will be the webhook that you can use in your elementor form, You can test this webhook in your browser first by pasting it. It will say "Yepp this is the webhook URL, request received".
> 
>     * Last all you have to do is setup and Elementor Pro Form with a form name and Webhook action pointing to the URL from above.

I followed your process and got an error-
"Webhook Error
This Message is not visible for site visitors."
How to resolve this?

**Comment by spsrijan** [comment]
> 
> 
> @chalgerro
> 
> I have an even simpler script that can handle many forms and Field names automatically, meaning it will create a new sheet for each form and set the headers automatically based on the form fields and even send an email to notify you about it.
> 
> In order to enable this script, follow these steps:
> 
>     * From your Google Sheet, from the Tools menu select Script Editor…
> 
>     * Paste the script from [this gist](https://gist.github.com/bainternet/4b539b00a4bd7490ac3809d7ff86bd14) into the script code editor and hit Save.
> 
>     * From the Publish menu, select Deploy as web app…
> 
>     * Choose to execute the app as yourself, and allow Anyone, even anonymous to execute the script. (Note, depending on your Google Apps instance, this option may not be available. You will need to contact your Google Apps administrator, or else use a Gmail account.) Now click Deploy. You may be asked to review permissions now.
> 
>     * The URL that you get will be the webhook that you can use in your elementor form, You can test this webhook in your browser first by pasting it. It will say "Yepp this is the webhook URL, request received".
> 
>     * Last all you have to do is setup and Elementor Pro Form with a form name and Webhook action pointing to the URL from above.
I followed your process and got an error-
"Webhook Error
This Message is not visible for site visitors."
How to resolve this?

**Comment by thaonio** [comment]
> @chalgerro
> 
> I have an even simpler script that can handle many forms and Field names automatically, meaning it will create a new sheet for each form and set the headers automatically based on the form fields and even send an email to notify you about it.
> 
> In order to enable this script, follow these steps:
> 
> * From your Google Sheet, from the Tools menu select Script Editor…
> * Paste the script from [this gist](https://gist.github.com/bainternet/4b539b00a4bd7490ac3809d7ff86bd14) into the script code editor and hit Save.
> * From the Publish menu, select Deploy as web app…
> * Choose to execute the app as yourself, and allow Anyone, even anonymous to execute the script. (Note, depending on your Google Apps instance, this option may not be available. You will need to contact your Google Apps administrator, or else use a Gmail account.) Now click Deploy. You may be asked to review permissions now.
> * The URL that you get will be the webhook that you can use in your elementor form, You can test this webhook in your browser first by pasting it. It will say "Yepp this is the webhook URL, request received".
> * Last all you have to do is setup and Elementor Pro Form with a form name and Webhook action pointing to the URL from above.

Thank for your tutorials.
I want to retrieve Meta Data for **Date**, **Time**, **Page URL**, User Agent and Remote IP. How can I do it?

**Comment by helloarpitgshah** [comment]
Hey @thaonio,

Hope you are doing good.

Yes, You can get this ElementorSheets Plugins, They have added Date/Time, Referrer URL and Freeze Headers for the spreadsheets as well.

Here you can have link to get more details,

https://codecanyon.net/item/elementorsheets-elementor-pro-form-google-spreadsheet-addon/25171650

Thanks,
Arpit G Shah

**Comment by the-mcnaveen** [comment]
> @chalgerro
> 
> I have an even simpler script that can handle many forms and Field names automatically, meaning it will create a new sheet for each form and set the headers automatically based on the form fields and even send an email to notify you about it.
> 
> In order to enable this script, follow these steps:
> 
> * From your Google Sheet, from the Tools menu select Script Editor…
> * Paste the script from [this gist](https://gist.github.com/bainternet/4b539b00a4bd7490ac3809d7ff86bd14) into the script code editor and hit Save.
> * From the Publish menu, select Deploy as web app…
> * Choose to execute the app as yourself, and allow Anyone, even anonymous to execute the script. (Note, depending on your Google Apps instance, this option may not be available. You will need to contact your Google Apps administrator, or else use a Gmail account.) Now click Deploy. You may be asked to review permissions now.
> * The URL that you get will be the webhook that you can use in your elementor form, You can test this webhook in your browser first by pasting it. It will say "Yepp this is the webhook URL, request received".
> * Last all you have to do is setup and Elementor Pro Form with a form name and Webhook action pointing to the URL from above.

Just now tried and not data appears in Google Sheet.

Any fix?

**Comment by camfil26** [comment]
It's not working for me either

**Comment by faizankhan1995** [comment]
Not working :-(

**Comment by charla87** [comment]
Hi! Thank you for your script! So usefull. How can I collect the data in the last row to make a new worksheet with default headers? 

thanks!

**Comment by chalgerro** [comment]
> Hi! Thank you for your script! So usefull. How can I collect the data in the last row to make a new worksheet with default headers?
> 
> thanks!

Just create your header and all new response will go below the headers, that's how appendRow works -  just appends row under the last row having data in it.
Best.

**Comment by charla87** [comment]
> > Hi! Thank you for your script! So usefull. How can I collect the data in the last row to make a new worksheet with default headers?
> > thanks!
> 
> Just create your header and all new response will go below the headers, that's how appendRow works - just appends row under the last row having data in it.
> Best.

Hi. Sorry, I wasn’t  clear...  My intention is: when a new form comes, make a new worksheet with a name given by a cell, instead of append a new row as last in the same worksheet... 

Many Thanks!

**Comment by wes1337** [comment]
Can't believe this still is not a feature..

**Comment by michumichifu** [comment]
Yo uso este script desde 2021 y me ha ahorrado mucho tiempo y sobre todo dinero. No entiendo como hay gente que dice que no les funciona, si les marca error suele ser ya problemas del hosting, lo cuento por experiencia usándolo años ya en distintos sitios web.

Luego hago un tutorial

Script completo:
`/*
 * In order to enable this script, follow these steps:
   ***   Open the Google Sheet you want to use,
    **   From the Tools menu select "Script Editor"
     *   Paste this script into code editor and hit Save.
     *   
   ***   Then click: 
    **     "Publish" & select "Deploy as web app...
   ***   Select: 
    **      Execute the app as: Me (youremail@gmail.com)
    **      Who has access to the app: Anyone, even anonymous
   *                           - Note, depending on your Google Apps instance, this option may not be available. You will need to contact your Google Apps administrator, or else use a Gmail account. 
   *
   ***    Now click Deploy. You may be asked to review permissions now.
   *                           - It will probably give you a warning, click "Advanced" on the bottom left and continue.
   *      
   ***    The URL that you get will be the webhook that you can use in your elementor form.
   *                            - You can test this webhook in your browser first by pasting it. 
   *                              It will say: "Yepp this is the webhook URL, request received".
   *         
   ***    EMAIL NOTIFICATIONS: 
            *  By default, email notifications are turned off in this script.
            *  To turn them on:
              *  on line 37 Change "false to "true"
              *  on line 40 replace "Change_to_your_Email" with, well, whatever your email is, but leave the "quotes"
              *  re-save the script. collect leades, make that $$$
 */    

function doGet(e) {}
function doPost(e) {
var o = e.parameter;
SpreadsheetApp.getActiveSheet().appendRow([ o.name, o.email, o.message, e ]);
}


// Change to true to enable email notifications
var emailNotification = false;

// Enter your email address below (keep the quotation marks!) 
var emailAddress = "Change_to_your_Email";

/**
 * Google app-script to utilise Elementor Pro Froms webhook
 * For Usage see: https://github.com/pojome/elementor/issues/5894
 * Origionally found: https://gist.github.com/bainternet/4b539b00a4bd7490ac3809d7ff86bd14
 * by bainternet
 * Minor tweaks to the directions by AvlSEONinja
 */
 
 
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT EDIT THESE NEXT PARAMS
var isNewSheet = false;
var recivedData = [];

/**
 * this is a function that fires when the webapp receives a GET request
 * Not used but required.
 */
function doGet( e ) {
	return HtmlService.createHtmlOutput( "Yepp this is the webhook URL, request received" );
}

// Webhook Receiver - triggered with form webhook to pusblished App URL.
function doPost( e ) {
	var params = JSON.stringify(e.parameter);
	params = JSON.parse(params);
	insertToSheet(params);

	// HTTP Response
	return HtmlService.createHtmlOutput( "post request received" );
}

// Flattens a nested object for easier use with a spreadsheet
function flattenObject( ob ) {
	var toReturn = {};
	for ( var i in ob ) {
		if ( ! ob.hasOwnProperty( i ) ) continue;
		if ( ( typeof ob[ i ] ) == 'object' ) {
			var flatObject = flattenObject( ob[ i ] );
			for ( var x in flatObject ) {
				if ( ! flatObject.hasOwnProperty( x ) ) continue;
				toReturn[ i + '.' + x ] = flatObject[ x ];
			}
		} else {
			toReturn[ i ] = ob[ i ];
		}
	}
	return toReturn;
}

// normalize headers
function getHeaders( formSheet, keys ) {
	var headers = [];
  
	// retrieve existing headers
    if ( ! isNewSheet ) {
	  headers = formSheet.getRange( 1, 1, 1, formSheet.getLastColumn() ).getValues()[0];
    }

	// add any additional headers
	var newHeaders = [];
	newHeaders = keys.filter( function( k ) {
		return headers.indexOf( k ) > -1 ? false : k;
	} );

	newHeaders.forEach( function( h ) {
		headers.push( h );
	} );
	return headers;
}

// normalize values
function getValues( headers, flat ) {
	var values = [];
	// push values based on headers
	headers.forEach( function( h ){
		values.push( flat[ h ] );
	});
	return values;
}

// Insert headers
function setHeaders( sheet, values ) {
	var headerRow = sheet.getRange( 1, 1, 1, values.length )
	headerRow.setValues( [ values ] );
	headerRow.setFontWeight( "bold" ).setHorizontalAlignment( "center" );
}

// Insert Data into Sheet
function setValues( sheet, values ) {
	var lastRow = Math.max( sheet.getLastRow(),1 );
	sheet.insertRowAfter( lastRow );
	sheet.getRange( lastRow + 1, 1, 1, values.length ).setValues( [ values ] ).setFontWeight( "normal" ).setHorizontalAlignment( "center" );
}

// Find or create sheet for form
function getFormSheet( formName ) {
	var formSheet;
	var activeSheet = SpreadsheetApp.getActiveSpreadsheet();

	// create sheet if needed
	if ( activeSheet.getSheetByName( formName ) == null ) {
      formSheet = activeSheet.insertSheet();
      formSheet.setName( formName );
      isNewSheet = true;
	}
	return activeSheet.getSheetByName( formName );
}


// magic function where it all happens
function insertToSheet( data ){
	var flat = flattenObject( data );
	var keys = Object.keys( flat );
	var formName = data["form_name"];
	var formSheet = getFormSheet( formName );
	var headers = getHeaders( formSheet, keys );
	var values = getValues( headers, flat );
	setHeaders( formSheet, headers );
	setValues( formSheet, values );
	
    if ( emailNotification ) {
		sendNotification( data, getSeetURL() );
	}
}

function getSeetURL() {
  var spreadsheet = SpreadsheetApp.getActiveSpreadsheet();
  var sheet = spreadsheet.getActiveSheet();
  return spreadsheet.getUrl();
}

function sendNotification( data, url ) {
	var subject = "A new Elementor Pro Froms subbmition has been inserted to your sheet";
  var message = "A new subbmition has been recived via " + data['form_name'] + " form and inserted into your Google sheet at: " + url;
	MailApp.sendEmail( emailAddress, subject, message, {
		name: 'Automatic Emailer Script'
	} );
}`
