### ISSUE TITLE
I want to change a core widgets output

### ISSUE THREAD

**Issue by Sighan** [pojome/elementor#5936]
I would like to add further content to the nav-menu widget, specifically I want to add a language switcher to the bottom of the drop down menu. Since you are not using any hooks, I tried to simply copy your widget, rename it and apply my changes. However for some reason none of the frontend listener get applied if I do that.

Please let me know how I can either replace the widget completely (without losing the functionality) or extend it.

**Comment by tristanleboss** [comment]
I am eager to know the answer too. Indeed, I wanted to create a new  widget using the original Counter widget. 

I extended the original Counter class but because the name (get_name) of the widget was different, the JavaScript of the original Counter widget was not firing because it was excepting the widget DIV class name to contain "counter" in them. Adding fields was easy but changing the template was too tricky: I had to capture the output of the parent functions and edit them using regular expression...

**Comment by bainternet** [comment]
@Sighan

In your case, Nav Menu, Elementor uses the native WordPress `wp_nav_menu` so all filter hooks that it runs are applied in the widget as well, ex:

```PHP
<?php
/**
 * Add a custom link to the end of a specific menu that uses the wp_nav_menu() function
 */
add_filter( 'wp_nav_menu_MY_MENU_SLUG_items', function( $items, $args ) {
	$items = $items . '<li><a title="Admin" href="' . admin_url() . '">Admin</a></li>';
	return $items;
}, 10, 2);
```

@tristanleboss 
You are correct, when you extend a widget and change its name the original JS handler is not aware of the new widget and that it should handle it as well, but to overcome that you can register the original handler to the new widget as well, eg:

```JS
// First get the original handler
var counterHandler = elementorFrontend.elementsHandler.getHandlers( 'counter.default' );

// Then register the handler for your new widget,
// let say your new widget is called `my_counter`
elementorFrontend.hooks.addAction( 'frontend/element_ready/my_counter.default', counterHandler );
```

Other then that you can filter the content via the filter has you have done.

thanks.
