### ISSUE TITLE
Elementor v2.2.7 issue with SVG sizes

### ISSUE THREAD

**Issue by dollhauss** [pojome/elementor#5987]
Heya,

I just updated some sites to v2.2.7 and all the SVG images on the sites disappeared.

The SVG's are still there but the size settings on the image widget no longer works correctly.
Rolled back to v2.2.6 and all is fine.

I created this ticket and it was ignored and closed as you said it didn't have the following info:
This report is missing key information:
Prerequisites.
Steps to replicate.
Isolating the problem.
System info.

So here we go:

Prerequisites.
1) Install Elementor v2.2.6
2) Install SVG plugin (Safe SVG)
3) Edit with Elementor and add Image module
4) Add SVG to image module
5) Set image size using max-width

Steps to replicate.
1) Install Elementor v2.2.6
2) Install SVG plugin (Safe SVG)
3) Edit with Elementor and add Image module
4) Add SVG to image module
5) Set image size using max-width
6) Update Elementor to v2.2.7
7) Image disappears and size settings no longer work correctly

Isolating the problem.
Same as above

System info.
PC Win 10
32GB RAM
NVIDIA 1070
Cloudways Vultr server

Let me know if you need any further info.

**Comment by Paras16699** [comment]
Working fine at my end with v2.2.7

The SVG's don't appear by default on adding (that's a WordPress issue; the way it handles SVG images by defaulting the height and width attributes to `1`), but changing the width settings in Elementor works because it applies `height` and `width` via CSS.

It has always been this way for me. The `max-width` value has never worked since the beginning because of this WP behaviour with SVG images. So, I set the `width` value and that is working fine with this latest update (`v2.2.7`).

I use the (SVG Support)[https://wordpress.org/plugins/svg-support/] plugin by Benbodhi.

**Comment by dollhauss** [comment]
I also set the width value - which does make it work on v2.2.7 however it appears to have a limitation on how large I can make the image. And this is with max-width and width set on full.

**Comment by Paras16699** [comment]
If you set it to `100%`, it should occupy the full container width. If you want to make it bigger than that, you'll have to change the width of it's container (the parent `column` or a `section`)

**Comment by dollhauss** [comment]
This is exactly what is not working correctly in v2.2.7

I had large SVG's working fine. And then after updating to v2.2.7 it would no longer fill 100% of the container width.

**Comment by bainternet** [comment]
Anyone who has this issue, make sure to give your image/SVG width and Preferably in pixels.

**Comment by arielk** [comment]
ref: https://github.com/pojome/elementor/issues/5897

**Comment by CodeBradley** [comment]
So the problem here is that SVG's won't display with width: 100% and need a defined set of pixels? Why not do 100vw instead which seems to work and do a fallback to 48px for older browsers?
