### ISSUE TITLE
Add button for preserve Elementor in English

### ISSUE THREAD

**Issue by shimsa** [pojome/elementor#5995]
While WordPress language is set to other than English and translation for Elementor in that language is exist, also Elementor is using that language.
Main target is to add button for preserve only Elementor in English, while WordPress is still in language other than English. English is universal and for lot of professionals, working with Elementor, preferred.

**Comment by black-eye** [comment]
+1
This is very needed, since some of the translations are practically unusable, e.g. Czech.

Another problem is, that when you have multilingial site, the language of the Elementor user interface uses the language of the translated page, not the language of the admin.

Imagine you are adding a page translation for Chinese, Arabic or Hebrew - which uses charset you are totally unfamiliar with and you have too use user interface is in this language!!!

**Comment by reneverschoor** [comment]
Instead of forcing to English, a better solution IMO would be to have Elementor follow the user profile language setting.
See also https://github.com/pojome/elementor/issues/5148
Check the comments in there for a workaround.

**Comment by bainternet** [comment]
I merged this issue with  #5148, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!
