### ISSUE TITLE
Global widget

### ISSUE THREAD

**Issue by born2gursikh** [pojome/elementor#6143]
After update to version 2.3.1 my global widgets pedding not working please fix it because my site stuck

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

We simply cant understand what the problem is.
