### ISSUE TITLE
Post duplication

### ISSUE THREAD

**Issue by exsilegroup** [pojome/elementor#6158]
Hey,

I develop a plugin and need help regarding the right way of the post-duplication process of post that build with Elementor.

Now I get the content of the post and then use the wp_insert_post() method to create new one.

The problem is about design, the duplicated post is not design. I understand that need to import template from Elementor library, but how possible to do it using code?

Thank you.

**Comment by bainternet** [comment]
@exsilegroup 

Most of Elementor's design and settings data is stored in the post meta so make sure you duplicate that as well.

**Comment by exsilegroup** [comment]
Hey,

I copy the post meta also and still, the duplicate post does not look with the same design.

Only if I click edit with Elementor and then click update it looks with the same design.

**Comment by bainternet** [comment]
Did you flush the css ?

**Comment by exsilegroup** [comment]
What do you mean "flush the css"?

**Comment by Sishasong** [comment]
Hi,

I develop a plugin too. I got the same issue than the OP here. I duplicate also all postmeta. But duplicate postmeta is not enough because the postmeta  _elementor_data start with an ID 
`[{"id":"3ed28cfa",... `
and made this duplication useless, all the design stay broken. 
Is this id really usefull ? :D  
I will go into your code to take a look how this id is generated, but if you tell how i can generate him into my plugin, it would be very welcome ;)

Thanks
