### ISSUE TITLE
Text Editor Widget - Image caption preview problem

### ISSUE THREAD

**Issue by bepixeld** [pojome/elementor#6196]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description
Editing an image in Text Editor Widget and insert a caption produces shortcodes in content view. 
Screenshot 2:
![screenshot2](https://user-images.githubusercontent.com/7001544/48660134-ef734580-ea5c-11e8-8b80-d6b5e03f295b.png)

## Steps to reproduce

1. Insert Text Editor Widget
2. In Editor (left) pane: Add image with caption text, or edit image and insert caption text. Screenshot 1:
![screenshot1](https://user-images.githubusercontent.com/7001544/48660189-fa7aa580-ea5d-11e8-884b-d700ca7e71e9.png)
3. After insert/update image the content pane views shortcode and not the caption. See screenshot 2.
4. If you start editing an other widget, then the preview in content pane is ok. Screenshot 3:
![screenshot3](https://user-images.githubusercontent.com/7001544/48660235-e4b9b000-ea5e-11e8-8230-09ef558fc9fe.png)

## Isolating the problem
- [ ] This bug happens with only Elementor plugin active (and Elementor Pro).
- [x] This bug happens with a default WordPress theme active.
- [x] I can reproduce this bug consistently using the steps above.

### Server Environment 
- Operating System: Linux
- Software: Apache
- MySQL version: MariaDB
- PHP Version: 7.0, 7.2
- PHP Max Input Vars: 3000
- PHP Max Post Size: 32M
- GD Installed: Yes
- ZIP Installed: Yes
- Write Permissions: All right
- Elementor Library: Connected

### WordPress Environment
- Version: 4.9.8
- WP Multisite: No
- Max Upload Size: 24 MB
- Memory limit: 256M
- Permalink Structure: /%year%/%monthnum%/%postname%/
- Language: de-DE
- Timezone: Europe/Berlin
- Debug Mode: Inactive

### Theme
- Page Builder Framework

### Active Plugins 
- Duplicator: Version: 1.2.52 Author: Snap Creek
- Elementor:  Version: 2.3.1 Author: Elementor.com

**Comment by bainternet** [comment]
@bepixeld 

This is simply the way shortcodes are handled inside a Text Widget.

If you are in an Edit mode, the shortcodes are shown as shortcodes in the preview.
Caption in WordPress is shown via a shortcode and the native TinyMCE knows how to display it as an image with caption (a TinyMCE View) instead of the shortcode, and they do that for most of the native shortcodes: https://core.trac.wordpress.org/browser/tags/4.9.8/src/wp-includes/js/mce-view.js#L942

But any other shortcode which is not listed there will show up as a shortcode, and in the editor Preview's case they are all shown as a shortcode, it's just how it works.

thanks for the feedback.
