### ISSUE TITLE
Error in Safari

### ISSUE THREAD

**Issue by paganel** [pojome/elementor#6248]
TypeError: elementorFrontend.getScopeWindow().jQuery is not a function. (In 'elementorFrontend.getScopeWindow().jQuery(".elementor-element",".elementor:not(.elementor-edit-mode)")', 'elementorFrontend.getScopeWindow().jQuery' is undefined)

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

**Comment by paganel** [comment]
Shocking support, I just bought Elementor with TheSaaS - Responsive SaaS, Startup & WebApp WordPress Theme. 

Prerequisites.
install and activate TheSaaS - Responsive SaaS, Startup & WebApp WordPress Theme
and I can assure you that I will never buy the premium of your solution, you have disgusting support .. I will demand the return of funds

Steps to replicate.
open any page for editing

**Comment by bainternet** [comment]
@paganel 	

Thanks,

Please create GitHub issues only for bugs reports and feature requests. 
GitHub issues **ARE NOT FOR SUPPORT!**

- If you have questions or need general support, Please try:

* [Elementor Community](https://www.facebook.com/groups/Elementors/) on Facebook
* [Elementor Knowledge base](https://docs.elementor.com)
* [Support forums](https://wordpress.org/support/plugin/elementor) on WordPress.org 
* [Elementor Developers docs](https://developers.elementor.com/)

If you have purchased [Elementor Pro](https://elementor.com/pro), you are entitled to personal support, please see your purchase email for details.


Now that we got that out of the way, that this is not a support channel, we can address you "issue", but we can't do that because you have failed to provide basic information. If I open a page to edit using Elementor in safari it works just fine so the reason we are asking for this data is to be able to provide proper guidance to resolving your issue.

And last just to be clear, TheSaaS - Responsive SaaS, Startup & WebApp WordPress Theme is not our product nor are we affiliated with it in any way.
