### ISSUE TITLE
Adding vw as a height unit

### ISSUE THREAD

**Issue by pegelf** [pojome/elementor#6281]
Hello,

i'm currently modifying a website with elementor pro and I'd like to use responsive heights for some contents. For example, I'm currently setting up a slider and it should have a size in vw, so the image doesn't have to be cut, because the height is measured by the width of the device. ("vw" stands for "viewport width")

At the moment, it is only possible to set the height in px vh and em. Of course it is possible to use custom css, but then the preview in elementor differs from the final web page.

So my feature request is to add the unit "vw" to the height selection especially in the slides widget.

kind regards
pegelf

**Comment by rgbink** [comment]
I am using a custom stylesheet (SCSS) and I've enqueued the resulting CSS file. Elementor preview does indeed show my custom styles. Very well.

**Comment by bainternet** [comment]
@pegelf 

We will try to add this unit to all relevant controls, if you have any specific controls, please let us know.

**Comment by gbaumbach** [comment]
Any chance we can get this back into the docket? I use VW to exclusively scale everything from font size, width, height, margins & padding. It is the most consistent method to proportionally scale everything on a responsive website and preserve the design. I use this on Webflow sites I build. I can construct complex layouts with absolute precision using vw as my unit of measure for everything. I can preserve sentence structure and eliminate widows from my headlines/body copy.

You guys currently use it consistently on items. It's good, but in order to properly layout a site design, everything needs to use vw for pixel perfection and predictability. Check out the layout I did on seguno.com to see what I'm talking about. VW is the way to go for designers who want to preserve their design on responsive layouts to a T. Thanks! -G

**Comment by andreigoea** [comment]
Agreed, VW should be an option on every slider. An immediate specific would be the height for the image widget.
