### ISSUE TITLE
Clone a content to translate

### ISSUE THREAD

**Issue by VictorCima** [pojome/elementor#6306]
I thought to do a script PHP to clone a page and to translate it. 
But my problem is that if I change the html content of the page in data base, not change the content of elementor. I see the data in metadata table, in json format, I need the way to modifiy the json information with the translation.
Are the any way to do this? 
Thanks!

**Comment by bainternet** [comment]
@VictorCima 	

Elementor saves and pulls its data from the post meta so that is why you are not seeing any changes, and yes you are correct that you need to clone the meta data as well and translate it there.

> I see the data in metadata table, in json format, I need the way to modifiy the json information with the translation.
Are the any way to do this?

You might want to look at some translations olugins and how they do that, but basiclly you need to pull the json data and iterate over it to translate.

if you are asking if Elementor has a function or method you can use, than simple answer is no, you would need to code your own.

thanks.
