### ISSUE TITLE
Lightbox width not 100%

### ISSUE THREAD

**Issue by crazypsycho** [pojome/elementor#6317]
Since elementor 2.3 the lightbox opens only with 375px width, instead of 100% like before in 2.2.x

I think this comes from a changed order of css-rules.
There is a rule for ".dialog-type-lightbox .dialog-widget-content" which sets width to 375px.
In 2.2 this rule was only in frontend.min.css.
In 2.3 this rule is also in common.min.css and overrides the 100% width from ".elementor-lightbox .dialog-widget-content" (also in frontend.min.css).

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

**Comment by crazypsycho** [comment]
The problem ocours in every wordpress installation with elementor 2.3.x.
Just add a widget which opens a lightbox (like gallery-widget) and click on an image to open the lightbox.
Than you will see the image with only 375px width.

**Comment by bainternet** [comment]
@crazypsycho 	


We can't replicate,
Please contact our support at support @elementor.com for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by yosauce** [comment]
https://imgur.com/a/Fs2s1ze

**Comment by daviedR** [comment]
I also experienced this issue on Elementor v2.5.9. Weird, because on my other sites, it works fine.

**Comment by daviedR** [comment]
The order of Elementor CSS files are what causing the issue. The `custom-frontend.css` is supposed to be enqueued after Elementor's `common.css`.

But on my problem site, `custom-frontend.css` is enqueued too early and before `common.css`. That is what makes the CSS rule overlapping and the latter rule (on `common.css`) makes the dialog width weird (375px).

Not sure what causing this. Maybe because I am on WP multisite?

**Comment by crazypsycho** [comment]
I think it comes from theme. If i change to tweentynineteen the css order is correct and it works.

**Comment by crazypsycho** [comment]
I think it comes from theme. If i change to tweentynineteen and the css order is correct and it works.

**Comment by hoodvisions** [comment]
A year later: anyone found out how to fix this? The issue still remains on a lot of themes I have tested. The lightbox is stuck at 375px width...

**Comment by LucaRosaldi** [comment]
Had the same problem, adding this CSS fixed it for me:

```
.dialog-type-lightbox .dialog-widget-content {
    width: 100%;
}
```

**Comment by DIntriglia** [comment]
@LucaRosaldi Thank you for comment. This did resolve my issue as well, but I did have to !important the tag for it to work.
```
.dialog-type-lightbox .dialog-widget-content {
    width: 100% !important;
}
```

**Comment by soulreverie** [comment]
Very frustrating that this is still an issue after having been first reported in 2018!! And the suggested CSS does not work properly for me with vertical images because they overflow. Here is what I did to get it working. No guarantees that it works crossbrowser but hopefully it will help someone get on the right path.


/* Elementor Lightbox/Swiper Bugfixes */
.elementor-lightbox.dialog-type-lightbox .elementor-lightbox-item,
.elementor-lightbox .elementor-lightbox-item .swiper-zoom-container{
		max-height: 100vh;
}
.elementor-lightbox.dialog-type-lightbox .elementor-lightbox-image{
	max-height: 90vh !important;
	max-width: 95vw !important;
	object-fit: contain;
}
.elementor-lightbox..dialog-type-lightbox .elementor-lightbox-item{
		max-height: 90vh;
}
.elementor-lightbox.dialog-type-lightbox .dialog-widget-content {
    margin: auto;
    width: 100%;
}
.elementor-lightbox.dialog-type-lightbox .elementor-thumbnails-swiper {
    max-height: 100px;
}
.elementor-lightbox.dialog-type-lightbox .swiper-wrapper{
height:100vh
}

**Comment by TarekEladly** [comment]
Dear All,
 use this 

`.elementor-lightbox .dialog-widget-content{
    width: 100% !important;
}`

so you target the image lightbox only not the popup too, thanks for the help.
