### ISSUE TITLE
image gallery

### ISSUE THREAD

**Issue by topdog1965** [pojome/elementor#633]
issues with gallery will not open up in light box  sometimes it will other times it will not

**Comment by Gudgnus** [comment]
All image widgets not functioning in elementor. Dragging image widget into section, "Choose Image" unresponsive.

**Comment by joshmarom** [comment]
We are not aware of a such an issue.
Please deactivate all of other plugins. If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.

   If you have a caching plugin, make sure you deactivate it, or even better – purge the cache.

   Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).

If you have followed all these steps and you’re still encountering difficulties, If you have followed all these steps and you’re still encountering difficulties, please contact support [at] elementor.com, with complete login information to access your website, and our support team will try to assist.

**Comment by arielk** [comment]
We are still waiting for your update. Feel free to reopen the issue and we'll be happy to help you further.

**Comment by Gudgnus** [comment]
Hi joshmarom & arielk , Sorry to not have gotten back with you. After trying your suggestions without success, I tried switching to a different browser (Safari > Firefox) and the stated problem as well as a problem with Caldera forms was resolved. I imagine a current version of Safari works fine, but mine was outdated. It seems every time Mac updates their OS a "required" Safari update is soon to follow. Because Mac OS updates creates a mess (replacing good apps with worse ones) I'm still operating on Mountain Lion. In turn, Safari can only be updated so far. Firefox, on the other hand, continues to update just fine without the Mac OS update problem. I hope my experience is helpful to someone. Elementor seems to be working fine for me now.
