### ISSUE TITLE
"Official" Mosaic Gallery

### ISSUE THREAD

**Issue by thread404cp** [pojome/elementor#6361]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

The past few days has taught me the struggle of a decent, free-solution 3rd party Mosaic-gallery plugin - especially when having to go through Elementor to add it (typically in form of a shortcode).

I would love to see a Mosaic-style gallery added to Elementor Pro with a range of customization, so that it will be easy to add those tall pictures next to more rectangular pictures without leaving a bunch of white space between.

Any other alternative is simply a paid option, but without any trial it's hard to say how compatible it is with Elementor Pro.

Here is a great sample of what a Mosaic-gallery looks like: https://d3n8kf7srwm7di.cloudfront.net/assets/images/2013/05/mosaic_thumbs-53c28e66.jpg

**Comment by bainternet** [comment]
Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

Thanks for the feedback.

**Comment by BasilBahrani** [comment]
I have made a mosaic of images page on my website, www.tinamacnaughton.co.uk , on my general portfolio page, however, the way I have done it makes it a mess when viewed on a mobile phone. I have tried the image gallery widget but that only lets me have the images in line with each other rather than a mosaic effect or the images not aligned.  So I too would very much like to see a mosaic style gallery added to Elementor open to all not just Pro and hope someone out there can develop one as it would be an amazing addition for all to use.
