### ISSUE TITLE
Post Widget Sort on ACF Field

### ISSUE THREAD

**Issue by Turanligil** [pojome/elementor#6426]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
Created a new CustomPostType -> "Event"
Also created an fild with ACF for this CPT -> "Event-Date"
Now i created a Archive Page for the Events and uses the Post Widget but i cant sort by my custom field "event-date"

**Describe the solution you'd like**
Would be nice to add the "dynamic Button" where i can select the ACF Field at the sort from the Post Widget

**Describe alternatives you've considered**
As workaround i installed the Post Types Order Plugin and ordered the post manually in backend and selected "Order by Menu" in Post Widget

**Comment by bainternet** [comment]
@Turanligil 

You can already sort the posts widget any way you want via [Custom Query Filter](https://developers.elementor.com/custom-query-filter/)

thanks.

**Comment by thecreativeoffices** [comment]
^ The Custom Query Filter is great, but closing a topic because you can hack some code in functions.php doesn't seem like a fruitful response. I'd like to see the issue re-opened and a genuine response as to how to do this from within Elementor -- or at least directions on how such a feature could be added to the roadmap.
