### ISSUE TITLE
Feature Request - Div Element

### ISSUE THREAD

**Issue by mauritzbotha92** [pojome/elementor#6434]
Hi all,

I would like to request this feature.

Currently the only way to get more divs into your design would be to create a new section, select the 2 column section, and then delete one column. This allows you to have an additional div in your design which can be styled.

It would be better to have the "innersection" element be replaced with a div element, that allows you to keep nesting divs inside of divs (as complex as you want to make it). This allows you have a lot more styling functionality as I often find I am restricted with not enough divs on the webpage that I can work with. Or if you could just have a separate div element which can be dropped inside itself as many times as you need within a normal section.

Many thanks!

**Comment by black-eye** [comment]
+1

**Comment by bainternet** [comment]
@mauritzbotha92 

can you explain better what you are asking?

**Comment by mauritzbotha92** [comment]
As long as you can keep putting content boxes inside content boxes and apply a style to each one individually, then yes, it would be the same concept.

**Comment by parfilov** [comment]
1+

**Comment by bainternet** [comment]
Thanks for clarifying,

Nested elements.

I merged this issue with  #2587, which is on the same subject so we could deal with it more efficiently. 
Please feel free to continue the conversation there.

Thanks for your feedback!

**Comment by black-eye** [comment]
@bainternet 
Well yes, nested elements (sections?) would be the solution, but I would still consider this div/content box element for a special use-case scenario as @mauritzbotha92 proposed.

Why?

`<div>
   ...
</div>`

vs 

`<section class="elementor-element elementor-section" data-element_type="section">
	<div class="elementor-container elementor-column-gap-default">
		<div class="elementor-row">
			<div class="elementor-element elementor-column" data-element_type="column">
				<div class="elementor-column-wrap elementor-element-populated">
					<div class="elementor-widget-wrap">
						<div class="elementor-element elementor-widget">
                                                     ...
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>`

That's why. Yes, I understand, there would be propably more divs for further formating even for a simple div widget, but you've got the point, right?

And this is just ONE column - imagine this section nested to several more levels.

**Comment by Flipback8** [comment]
How come you guys don't introduce Div Wrappers so we can use Flexbox? 

Check out how the Oxygen Builder Does it: https://youtu.be/LpJgevZfcdQ
We need Div wrappers. I don't want to use columns.

**Comment by antoine-piarou** [comment]
+1 dont undertstand why inner div doesn't exist...

**Comment by AliHussain85** [comment]
+1

**Comment by creazy231** [comment]
+1!

**Comment by AbrahamBrookes** [comment]
+1 the amount of junk injected when using the 'inner section' widget makes styling some things actually impossible.

I have been trying to make an image that gets cropped by its wrapping fullwidth section on the y axis, but overflows into it neighbouring column on the x axis - something I can easily achieve with a single nested div. Can't do it with the inner section though as it injects an extra three divs that I can't apply styles to without some seriously hacky css.

Just let me insert a div and apply my own classes please, stop forcing your layout on me.

**Comment by lllopo** [comment]
+10000000000 This would save tons of absolutely unnecessary junk HTML that Elementor generates with it's inner sections. What is needed is a fully controllable DIV, that allows for defining it's display conditions for grid and flex and you can just throw away your inner section nonsense in the bin. This will free a lot of people to create really clean looking HTML with far better end results than what is possible now (which is honestly not much).

**Comment by Flipback8** [comment]
> +10000000000 This would save tons of absolutely unnecessary junk HTML that Elementor generates with it's inner sections. What is needed is a fully controllable DIV, that allows for defining it's display conditions for grid and flex and you can just throw away your inner section nonsense in the bin. This will free a lot of people to create really clean looking HTML with far better end results than what is possible now (which is honestly not much).

Elementor doesn't listen to it's users. The short answer is, this feature will never come to Elementor:
https://snipboard.io/gUFvTD.jpg

Here is the best solution: https://oxygenbuilder.com/

**Comment by lllopo** [comment]
@Flipback8 Yes, Oxygen is head and shoulders above Elementor ... no, they can't even compare ... Oxygen is that better. I own it and would've using it everywhere, but it has one major drawback and that is lack of compatibility with many plugins like WPML, SearchWP etc. ... if it wasn't for that, I wouldn't come even close by Elementor ... so bloated, so limited ... but popular - you can't beat this. I guess that's why these guys do not put too much effort to optimize the thing and make it more flexible - they get the money as is anyway.

**Comment by Flipback8** [comment]
> @Flipback8 Yes, Oxygen is head and shoulders above Elementor ... no, they can't even compare ... Oxygen is that better. I own it and would've using it everywhere, but it has one major drawback and that is lack of compatibility with many plugins like WPML, SearchWP etc. ... if it wasn't for that, I wouldn't come even close by Elementor ... so bloated, so limited ... but popular - you can't beat this. I guess that's why these guys do not put too much effort to optimize the thing and make it more flexible - they get the money as is anyway.

I have been using Ajax Search Pro and it works great with Oxygen. Post your issues in their facebook group. They actually listen to the community.

**Comment by nicholaszein** [comment]
Hello there!

We have great news! 🙌 

### 📢 We're happy to announce that this feature was introduced with Elementor **v3.6** and is now a stable experiment since v3.8 as the Flexbox Container! 🥳 

By default, the Container tag is a Div, but you can also change the tag to many other values, including anchor `<a>` tags.

You can learn more about the Flexbox Container [here](https://elementor.com/help/what-is-a-container/).

✔️ Feel free to check it out and update your plugin to the new version!

Cheers 🥂
