### ISSUE TITLE
Cannot revert back to WordPress

### ISSUE THREAD

**Issue by SniffleValve** [pojome/elementor#6437]
Howdy,

As the title mentions, I am not able to revert Elementor content back to WordPress content. When you select Back to WordPress Editor, the content is displayed as expected without the Elementor styling. Select Update and it shows as expected in the backend. 

However, on the frontend, the Elementor version remains. No caching plugin, no server cache, Incognito window the same.

As well, when you exit the WP editor for that page and then open the page again, the content has reverted back to Elementor. Sort of an Elementor "lock-in" :) 

- local host, PHP 7.2.2, 256MB
- 2019 theme, Astra, GeneratePress
- WP 5.0.1
- Elementor 2.3.5 (only plugin installed)

Cheers!
Lyle

**Comment by bainternet** [comment]
Thanks for reporting, should be fixed in next version.

**Comment by arielk** [comment]
We just released a patch for this issue (v2.3.6), please update the plugin and let me know if it fixes your problem.

Thanks

**Comment by scottwyden** [comment]
that worked!

**Comment by SniffleValve** [comment]
That did it ! :) Thank you!
Cheers!
Lyle

**Comment by KesslerBeth** [comment]
I'm using v3.4.8 and have the exact same issue. I realize this is not the latest version but I need to find a temporary workaround until I can safely upgrade. Looking at v2.3.6 to try and understand what causes this behavior, I can't tell what's going on. Is this the mentioned patch? https://github.com/elementor/elementor/commit/7c55ba65f4ff39216b68d56e30e6d45ce5139c75

Where is wordpress getting the html markup from? Some file upload? The php session? I've verified it's not in the database, not the browser cache, not the cdn, nor in any browser local storage because remote users are seeing the same thing I am.
