### ISSUE TITLE
Custom slider widget not displaying correctly in editor.

### ISSUE THREAD

**Issue by enkota** [pojome/elementor#652]
Hey,

I am using a modified flexslider as a slider widget in an upcoming theme. When I drag the widget into the editor as far as I can tell it's not loading my external js file and stops the slider appearing correctly, is this intended? Is there any way to allow custom js to be enqueued in the editor?

Cheers,

Scott

**Comment by enkota** [comment]
So I've tried to load in the js through the following. I've tried post type as page and it works in the normal editor but not elementor.

`add_action( 'admin_print_scripts-post-new.php', 'elementor_admin_script', 11 );
add_action( 'admin_print_scripts-post.php', 'elementor_admin_script', 11 );

function elementor_admin_script() {
    global $post_type;
    if( 'page' == $post_type )
    wp_enqueue_script( 'elementor-admin-script', get_stylesheet_directory_uri() . '/assets/js/admin.js' );
}`

I'm now wondering if it's possible to hook into the elementor function via `add_action` ?

**Comment by arielk** [comment]
We will look into it, but meanwhile please check our development version.
We are working on it at the moment and we made few changes in the way we call scripts.

You can find it here:
https://github.com/pojome/elementor/tree/develop

Make sure you are testing it **only** in a DEV environment, because this is still a beta version. And in any case it’s better you will backup your site first.

**Comment by enkota** [comment]
@arielk awesome, thanks for the update!
