### ISSUE TITLE
Elementor & Gutenberg editor: Syntax error, unrecognized expression: #/

### ISSUE THREAD

**Issue by dameer** [pojome/elementor#6587]
Wordpress 5.0.2
Elementor 2.3.8

Whenever Elementor is activated as a plugin, Post, Page or Custom Post Type edit screen (Gutenberg, of course) runs with javascript error `Syntax error, unrecognized expression: #/`

It's not the theme related issue, Browser's Console does register it always. The problem persists since WordPress 5 released.

It does affect MetaBoxes or any other non-standard, javascript driven addition to WordPress editor (Gutenberg).

Video: http://bit.do/eEo8C

Happy New Year!!!

**Comment by bainternet** [comment]
Thanks for reporting,
Please follow guidelines for opening a new [issue report](https://github.com/pojome/elementor/issues/new?template=Bug_report.md), so we can help you better.
This report is missing key information: 

* Prerequisites.
* Steps to replicate.
* Isolating the problem.
* System info.

We can't replicate, try to enable Script Debug and disable concatenation to understand better whats the cause and where the issue is coming from by setting:

```PHP
define( 'SCRIPT_DEBUG', true );
define( 'CONCATENATE_SCRIPTS', false );
```

in your wp-config.php.

if the issue still persists feel free to reopen.

thanks
