### ISSUE TITLE
Please add a link into the sidebar to the pages overview

### ISSUE THREAD

**Issue by kakojak** [pojome/elementor#6670]
**What problem is your feature request going to solve? Please describe.**
To faster edit different sites.

**Describe the solution you'd like**
At the Elementor-sidebar it needs the link back to the wp pages overview -> 
/wp-admin/edit.php?post_type=page
It would be very nice if it has this button between the button "See page" and "Exit Elementor".

**Comment by deckerweb** [comment]
@kakojak
While in general I get where you coming from, however, I am against stuffing this footer area in the Elementor Panel with more options. It is already at a limit in my opinion. Please also consider a translated Elementor, German for example, where the "Save" button is wider because of a longer translation ("Save" --> "Speichern"). All this takes away precious space.

This all said, there are already plugins to achieve what you want, the most popular and current one is "Flexible Elementor Panel" https://wordpress.org/plugins/flexible-elementor-panel/

(disclaimer: I am just a user/plugin dev, not from Elementor team!)

**Comment by kakojak** [comment]
@deckerweb 
Yes I understand your objection. But I do not mean there but in the submenu if you click on the top left in the elementor-sidebar. There it has enought space in the subtitle "Go to" or in German "Gehe zu".

**Comment by bainternet** [comment]
@kakojak 	

Currently, this feature is not supported, but we will look into it in the future if we see a large demand for it.

But you can use the [Finder](https://elementor.com/blog/introducing-finder/).


Thanks for the feedback.
