### ISSUE TITLE
Updating Elementor Pro to v2.4.2 has DEACTIVATED my Website =/

### ISSUE THREAD

**Issue by enviedbymost** [pojome/elementor#6896]
Hi guys and gals,

I've just updated to the latest version of Elementor Pro, and the plugin has randomly deactivated itself.

Elementor is not acknowledging my pro license—and whenever I 'Activate' pro via WP-Admin, it's not activating.

I've tried de-authorising my website from elementor.com but it's not working. Here's a video of the issue.

https://www.youtube.com/watch?v=UGNCvgqBfVo&feature=youtu.be

I've done nothing other than upgrade from v2.4.1 to v2.4.2! Any ideas why this is? It's a big problem as it's deactivated all the pro features I use.

Please help!

Look forward to hearing from you.

Cheers, Jamie.

**Comment by shilo-ey** [comment]
Hi @enviedbymost 

There are some missing details we need to know in order to debug this issue.

Please try:

- Clearing any cache that is in your website.
- Deactivate all your plugins besides Elementor (and Elementor Pro). If this solves the problem, gradually activate your plugins one by one, until you spot the problematic plugin.
 - Change your WordPress theme to WordPress TwentySixteen (or other default WordPress theme).

And see if the issue still persists.
If it does, please contact our support from your Elementor accout for guidance in resolving this issue and mention that you were directed by me and reference this issue.

thanks.

**Comment by enviedbymost** [comment]
Hi Shilo,

Appreciate your reply!

To confirm, it was the Envato Elements - Template Kits (Beta) plugin causing the issue.

Deactivating that, then reactivating Elementor Pro solved the problem. :)

Cheers.
