### ISSUE TITLE
Popup conditions UI too narrow

### ISSUE THREAD

**Issue by innoforce-dev** [pojome/elementor#6931]
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest stable version of Elementor.

## Description

The UI for configuring the conditions for popups is way too narrow. It's hard to find the right page if the page name is spread across multiple lines. Please see the screenshot here: https://postimg.cc/7bJkcqDY

## Environment

WP: 5.03
Elementor v2.4.5
Elementor Pro v2.4.3

**Comment by shilo-ey** [comment]
Hi @innoforce-dev 

This issue occurs because you are using long page names.

Currently we will not change this, but we created a small snippet for you to use when you need it.

Please add this URL to your bookmarks bar (paste the code as the URL and name it whatever you want), when you need - just click on this bookmark and the conditions area will expand to the maximum.

```JS
javascript:(function()%7BjQuery( '%23elementor-theme-builder-conditions .elementor-repeater-fields-wrapper' ).css( 'width'%2C '100%25')%7D)()
```

Thanks
