### ISSUE TITLE
Pop up to a logged-in user only

### ISSUE THREAD

**Issue by sbc640964** [pojome/elementor#6967]
- [x] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

**What problem is your feature request going to solve? Please describe.**
In a pop-up window there is a condition that will not appear to a logged-in user, I want an inverse condition that will only appear to a logged-in user.. In many cases I would like to inform the user about a new feature on my site or a new product or special benefit. Which is not possible at this stage.

**Comment by shilo-ey** [comment]
@sbc640964 

Thanks for your feedback.

Currently we do not support this feature, and we will soon update the developer documentation to explain how you can add custom triggers.

As for your request, we do not recommend this because the popup is present in every page that you set it to be (condition) and is triggered just when the requirements met.

Thanks.

**Comment by zeinnicholas** [comment]
I never thought I would need this, but turns out I do need this. So I'm definitely +1 this request. I can see a few ways of using this.

**Comment by Joe-Bloggs** [comment]
Is there any update on this?

**Comment by JudithK87** [comment]
I also need this.

**Comment by arcticash** [comment]
This definitely needs to be implemented, if there is an option to show pop-ups to ONLY logged out users, there should be an option to do the opposite!
