### ISSUE TITLE
PHP Code widget not working on phones and tablets

### ISSUE THREAD

**Issue by serbon91** [pojome/elementor#6977]
I have a problem with the Safe PHP code widget ,I'm trying to display the post tags within the page elementor template, and I'm using the PHP code widget with the code it works on desktop and laptop, however it wont show the post tags on mobile or tablet. i'm using elementor pro with ocean wp theme. Here is the link to the page, where it says features & amenities the post tags should show there: http://luxury.earthboundentertainment.com/oak/

They show on desktop and laptop but not on mobile devices

**Comment by shilo-ey** [comment]
Hi @serbon91 

We do not support or recommend you to use any PHP widget. 

You cannot add PHP code to Elementor, since this would pose a security risk for websites. You can create shortcodes that run PHP and add the shortcode to Elementor, or use our hooks. [see documentation](https://code.elementor.com/hooks/).

Thanks.
