### ISSUE TITLE
Setting Default Scheme Programmatically

### ISSUE THREAD

**Issue by emaildano** [pojome/elementor#7009]
I'm using pro and I have a question about setting the default scheme programmatically.

Here are the default colors that ship with Elementor. How do I change these in my functions.php without using the GUI.
```
public function get_default_scheme() {
	return [
		self::COLOR_1 => '#6ec1e4',
		self::COLOR_2 => '#54595f',
		self::COLOR_3 => '#7a7a7a',
		self::COLOR_4 => '#61ce70',
	];
}
```

I'd like to do this for a few reasons.

1. Defaulting to reset colors will always fall back to the Elementor default, not defaults we set.
2. We'd like to make this portable across sites.

**Comment by shilo-ey** [comment]
@emaildano 	
You should already be able to change the defaults like so:

```PHP
add_filter('elementor/editor/localize_settings', function ($config) {
	$config['default_schemes']['color']['items'] = [
		'1' => '#6ec1e4',
		'2' => '#54595f',
		'3' => '#7a7a7a',
		'4' => '#61ce70'
	];

	return $config;
}, 99);
```

**Comment by suganyaselvakumar** [comment]
Even though the above code is not work.

**Comment by suganyaselvakumar** [comment]
core/kits/documents/tabs/global-color.php  - default_colors array variable. Global default color comes from above specified file.

I go through https://github.com/elementor/elementor/issues/7009 this ticket but that solution does n't work because default colors comes from the above file. 

so during the next update kindly add a filter in $default_colors array elementor/core/kits/documents/tabs/global-color.php line 63.

I am very eagerly looking in to this during your next update.
