### ISSUE TITLE
Vertical nav menu needs option to disable collapse to hamburger

### ISSUE THREAD

**Issue by knireis** [pojome/elementor#7014]
## Prerequisites

- [x ] I have searched for similar features requests in both open and closed tickets and cannot find a duplicate.
- [ x] The feature is still missing in the latest stable version of Elementor ( Elementor Pro. )

The vertical menu layout needs an option to not collapse on mobile or tablet. I use a vertical menu in a off canvas situation, and in the design there is a hamburger menu already. On mobile i now see 2 hamburgers which is not necessary. See screenshots for clarification.

![schermafdruk van 2019-02-08 09-22-14](https://user-images.githubusercontent.com/2702064/52470221-d676be00-2b8d-11e9-8194-95db23e2100e.png)
![schermafdruk van 2019-02-08 09-22-08](https://user-images.githubusercontent.com/2702064/52470222-d676be00-2b8d-11e9-8d5b-4884ff623ac8.png)
![schermafdruk van 2019-02-08 09-21-41](https://user-images.githubusercontent.com/2702064/52470223-d70f5480-2b8d-11e9-897c-eb8200ba3222.png)
![schermafdruk van 2019-02-08 09-21-37](https://user-images.githubusercontent.com/2702064/52470224-d70f5480-2b8d-11e9-8d4c-4a07444a1947.png)

**Comment by shilo-ey** [comment]
Hey @knireis 

I'm assuming you are using Elementor Popup Builder in order to achieve the off-canvas effect.
Simply set your nav-menu to `none` on the Toggle Button option.
![image](https://user-images.githubusercontent.com/45009641/52534032-e1278380-2d44-11e9-82c7-6454f26b7c44.png)


This should hide it all the time and set the menu to "Open" state.

Thanks.
