### ISSUE TITLE
Heading css class bug?

### ISSUE THREAD

**Issue by mizejewski** [pojome/elementor#707]
I've applied a CSS class to a heading widget with the aim of changing the style of my H2 headings in certain cases.

It seems like the logical place for the class `style-like-h3` to appear would be at the level of the H2 so that this addition to my style sheet would work:

`h2.elementor-heading-title.elementor-size-default.style-like-h3 {
font-size: 24px
}`

However, the widget applies the style at a higher level which does not allow me to affect the H2 styles. (see attached)

Is this a bug, or am I missing something? Grateful for any insights.

<img width="839" alt="heading_class" src="https://cloud.githubusercontent.com/assets/974442/19205952/4d52853a-8c9a-11e6-90d9-8ee55e33eaa9.png">

**Comment by mizejewski** [comment]
I finally got it to work like this, but it would be more intuitive if the custom class were applied to the heading tag, since that's what they user sees in the Elementor interface. 

`.style-like-h3 .elementor-widget-container h2 {
font-size: 24px;
}`

**Comment by joshmarom** [comment]
I see what you are saying and you do make sense, but you need to consider the fact that it is one of the only widgets that consist of just a single element. Almost all widgets are made up of a number of elements, which means the css class needs to be applied to a wrapper element. So if we want to keep things consistent, maybe we should not apply the class to the heading element itself.

What do you reckon?

**Comment by mizejewski** [comment]
I see your point too, but from a user perspective, I can tell you it was not intuitive. I added a class and expected to be able to use it to affect the heading, but upon inspecting the element in the browser, at first it looked like my class was not being applied (when in fact it was 2 divs higher up and not selected via Chrome > Inspect.) See image for an example. 

I suggest you test with a few more end users with only basic css knowledge, especially since Heading is likely to be a high use widget.

<img width="633" alt="screen shot 2016-10-10 at 10 37 29 am" src="https://cloud.githubusercontent.com/assets/974442/19245426/e6b53730-8ed5-11e6-8c9f-bd0d963fbff5.png">

**Comment by pingram3541** [comment]
This is not an issue and is very intuitive from the perspective of using CSS as it was designed. What your are asking for is actually more limiting to our design freedom.

In CSS one can target any child from the parent but not the other way around.

Just add your classes and then write your CSS, ".parent-class element" it's very simple.

**Comment by mizejewski** [comment]
@pingram3541 so are you saying my classes shuld be entered like this in order to work properly in Elementor? 

![classes](https://cloud.githubusercontent.com/assets/974442/24011720/c6833190-0a38-11e7-8789-710f3275b967.png)

**Comment by pingram3541** [comment]
No, in your custom css specifically, when targeting your Elementor element.  CSS hierarchy always comes into play and here is a great read of how it works here: [https://css-tricks.com/specifics-on-css-specificity/](https://css-tricks.com/specifics-on-css-specificity/)

So in your Elementor heading element, just give it a single descriptive class name like `blue-medium`.  This get's applied to the div wrapper around whichever heading type you chose, i.e. h2, h3 etc.

The simplest css rule would be `.blue-medium h2 { ...your styles... }`

If you used the above classes as in your screen shot the result would be as follows and very much, overkill.  `.parent-class.element.style-like-h5 h2 {  ...your styles... }`

Spaces in the elementor CSS Classes field create multiple classes that are concatenated.

.parent-class.element.style-like-h5 <- single element with many classes

Spaces in a css stylesheet denote nesting and tells the browser where specifically to apply the rules, i.e. only elements of X type, nested within X parent(s), etc.

.parent-class
  .element
    .style-lik-h5

There are often other components inside the div wrapper for other Elementor elements such as forms, sliders, galleries and since the custom class is applied to the wrapper we can also target these elements, i.e. `blue-medium img` or `blue-medium p`

This is why it is important for the class to be applied as high up in the chain as possible because there is no way to style those other elements if the class landed for example on the heading element itself such as `h2.blue-medium` <<<--- no way to apply rules to what this is inside of

CSS styles become stronger the higher up the rules are sent down. (see next sentence)

When you have other plugins or themes messing with these rules you just need to find the higher specificity in your custom css, i.e. `body.home #Wrapper .blue-medium h2` would override `#Wrapper h2`, each space represents how they are nested, i.e. #Wrapper is inside of body.home just as is .blue-medium is inside #Wrapper.

Also adding element types help make a rule stronger.  For example, `body.home` will beat out `body` or `.home` even though all 3 apply to the same element.  `div#id` is stronger than `#id`, `body p#id` is stronger than `p#id` and never forget for these rules to work, they have to actually match what is in the html nesting structure.

Anyway hope this helps explain it better.  The article above will surely help and then you'll be on your way to web ninja status amazing all your friends how you can use the browser inspector css tools to make facebook have a very different shade of blue. =)
