### ISSUE TITLE
Blank page contains no Elementor edit button.

### ISSUE THREAD

**Issue by paaljoachim** [pojome/elementor#708]
Hi

I made multiple pages. Building one at a time. Checking them on the frontend.
As I click the links and go to a blank page there is no Elementor Edit button on the page.

![screen shot 2016-10-07 at 23 04 04](https://cloud.githubusercontent.com/assets/5323259/19209905/60fcfc08-8ce2-11e6-9b51-3e8f5bafd9a3.png)

I have to click edit page -> goes to backend -> Then click Edit with Elementor to go back to the frontend page.

**Comment by agusmu** [comment]
I think it is expected behavior. 

"Edit With Elementor" link on top admin bar is available only when you have clicked "Edit with Elementor" red button on backend and make this page is on Elementor mode. 

When no "Edit With Elementor" link on top admin bar, it means that you currently use default WordPress editor.

**Comment by paaljoachim** [comment]
As the Elementor plugin is in use it would be natural to have Edit page AND Edit with Elementor link as well.

But I do agree it is very likely expected behavior.

**Comment by arielk** [comment]
Please read this issue in the same subject: https://github.com/pojome/elementor/issues/539#issuecomment-245685684

**Comment by paaljoachim** [comment]
Thanks for the link!
