### ISSUE TITLE
custom query and post content on page

### ISSUE THREAD

**Issue by matthiaswagnerwy** [pojome/elementor#856]
hy,
i think i found an issue when a page template does not only display the content for this page. i have a custom WP_Query and display these posts directly underneath each other in this page (above the page content itself). when i open elementor for this page, it "hooks" inside the first post out of my query. i did not try to place any content or save the page.

hope you can reproduce the issue and solve it in future versions :)
matt

**Comment by arielk** [comment]
This issue is already resolved in V0.11 please update your plugin and let me know if is resolve the problem

**Comment by p-realinho** [comment]
Hey!
First, thanks for the awesome plugin!

So, I think I'm running into this issue.

I'm developing a theme, with a custom post type for Slides, and in one of the page templates I have a `WP_Query` / loop for this CPT before the main post / page loop.
When I try to edit said page using Elementor, the area with the "Add New Section" and "Add Template" buttons shows where the `the_content()` of the first slide is, instead of the page's `the_content()`.

Still, the content shown is the right one (just misplaced), and if I try to edit and save it, all is correctly shown (placed) in the front-end.

Not sure if I'm doing something wrong, or not doing something I should be, or this issue has actually surfaced again.

I made a [repo](https://github.com/p-realinho/elementor-test) with just the code needed to reproduce the issue, in case you'd like to test it out.
Just install the theme, add at least one Slide, add a Post and edit with Elementor.

Thank you in advance!
