### ISSUE TITLE
Colums in toggle and tabs

### ISSUE THREAD

**Issue by iameviliam** [pojome/elementor#911]
It will be cool to have the possibility to add columns insige toggle and tabs.

**Comment by SniffleValve** [comment]
You can do that right now by using the very handy plugin called AnyWhere Elementor:

https://wordpress.org/plugins/anywhere-elementor/

Basically, create the content you want for your Toggles and Tabs as usual with Elementor. Either save to the Elementor Library or just save as a page. Then place the AWE shortcode within the Tab or Toggle editor.

Cheers!
Lyle

**Comment by arielk** [comment]
This is a very useful feature and it is one of the cool features included in the upcoming Elementor Pro. You can follow our updates in [elementor.com](https://elementor.com)

**Comment by iameviliam** [comment]
@arielk When it will be released?

**Comment by arielk** [comment]
December 12th. You can read more here: https://elementor.com/pro/

**Comment by TheMangoTrain** [comment]
Shortcodes isn't a feasible solution to the original request. Of course you can place a shortcode anywhere there's HTML input; that's a fundamental WordPress feature.

As it stands, Elementor tabs are only useful for basic content, only because to do anything more is too annoying or inconvenient.

Ideally what's needed is the ability to fully design a layout within a tab, as if the tabs were sections. Drag any column or widget into them.

The thinking needs to be bigger than plain old tabs. Think along the lines of "Paged Sections" where tabs is just one way to navigate the paged sections. Add an optional progress bar and you now have big possibilities for story telling or multi-part forms.

**Comment by sherlanova** [comment]
Thank you!

This is very much true. I'm building website for online recruitment that's a little bit complex than just collecting basic informations from simple form. I'm trying to make a multi-sections form instead of one-darn-long form from top to bottom (just started using Elementor 2 days ago). 

Even a simple section break between group-questions will be nice. To put those sections in multi-tabs would be one great way from design's point of view. The main goal is to have forms with multi-sections feature.

Hopefully this can get real soon!

**Comment by TheMangoTrain** [comment]
**Section breaks:**
Surprise! There's a form item called "html".
Just insert that anywhere in your form stack, and inside it build whatever separator you wish, like the classic <hr> bar. Have fun =).

**Use columns widths:**
Each form item has width control (column percentage). Use this to make the form less boring. For example make two adjacent fields 50% width so they appear side by side like in the case of having first and last name appear side by side.

**Experimental form groups**
I'll probably attempt this soon, in my head I see it should work.

1. Make multiple form widgets around your page, anywhere you'd like... in sections or columns, anywhere. Make sure they all have unique ID's and their submit buttons should all be hidden from view using CSS display:none. FYI, there are some 3rd-paarty tab widgets that allow Elementor templates inside of tabs.

2. Make a custom button act as your universal submit button, which will run a short script gathering all the data from each form widget and making a your submission with that. Because all your form widgets have unique ID's, you can target them all with Javascript. The downside is this pseudo-super-form won't work if the user has Javascript disabled... but we dont care about those users, right? Especially in the land of Javascript page-builders we're all addicted to like crack-cocaine =).

**Comment by sherlanova** [comment]
Oh wow, wow, wow.

Thank you for the ideas. Let me implement and tweak it around my form page. Lots and lots of possibilities.

Cheers!

**Comment by musicmxn** [comment]
> December 12th. You can read more here: https://elementor.com/pro/

Where is this feature?

**Comment by S-Simon** [comment]
Is there an update on this? How can we add sections to columns?
